### ISSUE TITLE
[Proposal] Make log files sortable

### ISSUE THREAD

**Issue by glatzert** [aspnet/AspNetCoreModule#103]
If you have log file from multiple applications in a single folder, sorting the files is cumbersome, since the log file Format is Name_Port_Date - this makes the files badly sortable.

If the default log file name format would be Name_Date_Port the files would nicely sort. So please consider changing the filename logic to a sortable format.

**Comment by shirhatti** [comment]
This is currently achievable as you can specify a prefix for log files in the `stdoutLogFile` attribute in your `web.config`.
Feel free to re-open if you still have questions

**Comment by glatzert** [comment]
Hi @shirhatti can you make an example how to include the current date (and probably time) in the file-name-prefix?
