### ISSUE TITLE
Aspnet Core 1.1.0 does not properly add forwardWindowsAuthToken="true" to web.config when deploying

### ISSUE THREAD

**Issue by shirhatti** [aspnet/AspNetCoreModule#104]
_From @mackayj on May 19, 2017 5:37_

I noticed that when publishing my new Aspnet Core 1.1 (just updated to VS 2017) project it is always missing the forwardWindowsAuthToken="true" from the web.config.

More info and the fix I found was here:

https://developercommunity.visualstudio.com/content/problem/26751/publish-aspnet-core-to-iis-with-windows-authentica.html

I also tried adding:

services.Configure<IISOptions>(options => { options.ForwardWindowsAuthentication = true; });

to my ConfigureServices method but it didn't help.

So my question is, is there a way to get this to work properly? Some command line argument or other way to automate it other than having to manually edit the web.config after it has been deployed?

I don't think it matters, but this is a asp.net core 1.1 targeting 4.6.2 not core.

http://stackoverflow.com/questions/44057005/aspnet-core-1-1-missing-windows-authentication-when-published

Since we have the deploy automated its annoying to have to manually edit the web.config file, is it possible to automate that? Is it a known issue? Our older 1.0 core projects do properly add forwardWindowsAuthToken="true" in the web.config.

_Copied from original issue: dotnet/core#661_

**Comment by shirhatti** [comment]
_From @Petermarcu on May 22, 2017 14:33_

@Eilon @DamianEdwards

**Comment by shirhatti** [comment]
_From @Eilon on May 22, 2017 15:46_

@Tratcher - any idea where this issue should go?

**Comment by shirhatti** [comment]
_From @Tratcher on May 22, 2017 22:2_

https://github.com/aspnet/aspnetcoremodule
@shirhatti 
Note that forwardWindowsAuthToken's default value was changed to true so most apps no longer need it in the web.config.

**Comment by shirhatti** [comment]
_From @mackayj on May 22, 2017 22:54_

@Tratcher when was it changed? In the 1.1 version with VS 2017 I have to manually set it in the web.config or it doesn't authenticate properly.

For example deploying the default project will show:

"Hello, !" in the top right where its supposed to show the username, with anon, asp.net impersonation, forms disabled and windows auth enabled in IIS

**Comment by shirhatti** [comment]
_From @Tratcher on May 22, 2017 22:56_

I'll defer to @shirhatti and @BillHiebert.

**Comment by shirhatti** [comment]
@mackayj I just looked into what you said. The version of ANCM that shipped in VS 2017 was [1.0.1971](https://github.com/aspnet/AspNetCoreModule/releases/tag/1.0.1971). The change to the default value of `forwardWindowsAuthToken` was only made in [1.0.1972](https://github.com/aspnet/AspNetCoreModule/releases/tag/1.0.1972).

We will ship a new version of ANCM which has this change in the next update of Visual Studio.

**Comment by shirhatti** [comment]
@joeloff

**Comment by mackayj** [comment]
@shirhatti Hey thanks for the update. Is there a way I can update our build server with a version that will correctly add it? We are using on prem TFS 2017 Update 1 and installed the latest VS 2017 on it the other day.

Is the best option for now to install the latest (what is the preferred method to do that?) or include a web.config in our project instead of having it auto generated or is there something else we can do as a workaround for now instead of having to manually update post deployment?

**Comment by shirhatti** [comment]
@mackayj Sorry for the late response. If you do not want to include a `web.config` in your project, you can change the default value of `forwardWindowsAuthToken` in the ASP.NET Core schema file. I'd still recommend against it though and rather carry the `web.config` with my app.

Feel free to re-open if you still have questions.

**Comment by pamanes** [comment]
I just found out about this problem when I realized User.Identity.Name was null. I ended up adding forwardWindowsAuthToken="true" to the web config's aspNetCore element. I am targeting full .net framework 4.6.1 using Core 2 (installed the latest SDK). Also ForwardWindowsAuthentication is no longer an available option in IISOptions

Will this get pushed soon?

thanks

**Comment by shirhatti** [comment]
@pamanes What version of the ASP.NET Core Module do you have installed?
`(Get-Item C:\Windows\System32\inetsrv\aspnetcore.dll).VersionInfo`

**Comment by Tratcher** [comment]
forwardWindowsAuthToken's default was changed to `true` a long time ago, you shouldn't need this setting anymore. Is this for IIS Express or IIS? For Express check: `C:\Program Files\IIS Express\config\schema\aspnetcore_schema.xml`. For IIS check `C:\Windows\System32\inetsrv\Config\Schema\aspnetcore_schema.xml`.

**Comment by pamanes** [comment]
@shirhatti I have 7.1.1967.0 and this is on IIS (not express). @Tratcher I do see the forwardWindowsAuthToken attribute in the aspnetcore_schema.xml but it's not being injected when publishing for some reason. thanks for the help.

**Comment by Tratcher** [comment]
forwardWindowsAuthToken isn't supposed to be added to your web.config when publishing anymore. What did your aspnetcore_schema.xml show as the default value?

**Comment by pamanes** [comment]
it shows true, if it isn't supposed to be added, what adds it then?

**Comment by shirhatti** [comment]
Default value of forwardWIndowsAuthToken has changed in 7.1.1972.0- https://github.com/aspnet/AspNetCoreModule/releases/tag/1.0.1972
I don't know how your schema and dll got out of sync. Could you try upgrading ANCM first?

**Comment by pamanes** [comment]
I re-installed the 2.0 SDK, my DLL version is now 7.1.1982.0. There is no forwardWIndowsAuthToken in the web.config file of the published project and windows authentication is working! thanks a lot for the help.
