### ISSUE TITLE
Disable backend restart when web.config changes

### ISSUE THREAD

**Issue by LarsAndreasEk** [aspnet/AspNetCoreModule#111]
Hi,

Can I disable the feature that restart the backend process whenever web.config is changed?

Best regards,
Lars Andreas

**Comment by shirhatti** [comment]
@LarsAndreasEk Just curious what you are trying to achieve here? It is unlikely we'll make this change, but I want to make sure we've given enough consideration to your request.

**Comment by LarsAndreasEk** [comment]
I have an app that needs to aggressively cache a lot of data into memory at
startup. Takes about a minute. When it's deployed to IIS, we have a minute
of downtime.

I've considered various approaches, including taking the app in/out of the
load balancer, blue/green deploy on a per machine basis with IIS web
farm+URL rewrite, and so on.

My idea at the time when I posted was this:
- Have the IIS Application serve files from a static folder, which contains
only the web.config with aspNetCore module config.
- On deploy, place the new version of the app in a new folder somewhere
else. Then modify the aspNetCore element web.config to point at the app's
new location.
- If touching the web.config wouldn't case the app to restart I could
trigger an application pool recycle. Overlapped recycle would do its magic
and let us deploy without that minute of downtime.

I have, however, found a workaround: By placing the aspNetCore config in a
separate file and referencing it from web.config via the configSource
attribute, I'm able to modify that file without causing a restart.

Thoughs? Suggestions for improvement?

:)

**Comment by shirhatti** [comment]
cc @pan-wang

**Comment by LarsAndreasEk** [comment]
Me being curious: What exactly is the mechanism that restarts an app when web.config is changed? Is the mechanism the same for asp.net core applications as for pre-core web apps?

**Comment by pan-wang** [comment]
For traditional asp.net application, both IIS and ASP.NET monitors the web.config. If there is a change, IIS will recycle the corresponding IIS application, ASP.NET will upload AppDomain (i.e., the managed application gets recycled). For ASP.NET, ASP.NET core module listen on IIS application recycle. Once the recycle, is triggered (e.g., Web.config change), Asp.net core module will notify the backend to exit to mimic the AppDomain unload behavior.

**Comment by pan-wang** [comment]
if you have to cache a lot of data for your app, you may want to use some cache service and run as an independent service. Your app just communicate with the cache service to retrieve the data.
using configSource can cheat the monitoring mechanism, but new configuration for your asp.net core app may not be adopted.

**Comment by LarsAndreasEk** [comment]
We've considered an external cache, but decided against it for performance reasons.

I'm trying to understand your last statement. In what way do you mean new configuration may not be adopted?

**Comment by LarsAndreasEk** [comment]
Also, any tips on how to achieve something similar for a traditional asp.net application/wcf?

**Comment by PonchoPowers** [comment]
See issue https://github.com/aspnet/AspNetCoreModule/issues/84 which is a prime example of why we should be able to avoid a restart of the .NET Core process when the web.config file is changed.

**Comment by shirhatti** [comment]
Closing this issue as there's nothing actionable here. I suggested an alternative in #84 in how to possibly achieve what ~~you're doing~~ you want.
