### ISSUE TITLE
Trouble Building the Core Module

### ISSUE THREAD

**Issue by DragonOsman** [aspnet/AspNetCoreModule#112]
I downloaded the latest Release version and tried to build it, but I got errors when trying to run the ".\build /target:clean" command.  Build output log is on OneDrive here: [https://1drv.ms/u/s!As6LkLqTe7Ps-EHmnF72fQDDn9mp](https://1drv.ms/u/s!As6LkLqTe7Ps-EHmnF72fQDDn9mp).  I tried it in both Elevated Developer Command Prompt for VS2017 and PowerShell.  Same result both ways.  

Why does it think I'm giving it an empty parameter when I'm clearly not?  What do I need to do that I'm not doing?

**Comment by shirhatti** [comment]
@DragonOsman This sounds like a point-in-time error with `build.cmd`. Do you mind trying again and see if you still have this error?

**Comment by muratg** [comment]
No repro
