### ISSUE TITLE
Turn Microsoft.AspNetCore.AspNetCoreModule.nupkg into an Azure Site Extension

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCoreModule#116]
https://github.com/projectkudu/kudu/wiki/Azure-Site-Extensions

The Microsoft.AspNetCore.AspNetCoreModule package is currently built to deploy the nightly dlls to myget so we can run integration tests with ASP.NET Core (e.g. ServerTests, IISIntegration, MusicStore). We could extend this test approach to Azure by adding the necessary scripts to this package to make it an Site Extension. On install the xdt script would edit the applicationhost.config to change the aspnetcore.dll reference from the installed copy to the nuget deployed copy. This would facilitate manual and automated testing of nightly bits prior to a full Azure deployment.

If this works out well we could also extend the concept to release stable versions of the site extension that customers could opt into in order to get ahead of the latest azure MSI deployment that can take multiple weeks. Note the schema file could not be replaced with this mechanic, so we'd still want to do the full MSI roll-out periodically.

**Comment by muratg** [comment]
@pakrym could you link the SiteExtensions bug + the current status here?

**Comment by pakrym** [comment]
@muratg ANCM dll's are already included in runtime site extension that I'm currently finishing building on CI. @jkotalik  was investigating XDT transformations required to run ANCM from site extension on Antares.

**Comment by pakrym** [comment]
https://github.com/aspnet/AzureIntegration/issues/105

**Comment by muratg** [comment]
@pakrym Sounds good, that's what I thought.  

Closing this one as the overall work is tracked there: aspnet/AzureIntegration#105
