### ISSUE TITLE
Exclude Virtual Directory

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCoreModule#123]
_From @dotnetshadow on May 31, 2017 7:12_

Hi there,

I currently have an asp.net core 1.1.1 application hosted on a Windows IIS shared server.

```
http://www.foo.com
```

My hosting company has a virtual directory for stats that points off my domain 

```
http://www.foo.com/stats
```

The issue I'm facing is that **/stats** thinks it's a route from my asp.net core application. I've tried to exclude the directory through IIS web.config. I'm unsure how to make that virtual directory just process without asp.net core interferring with it?

Can web.config use <location> to exclude directories?

**Startup.cs*
```
 app.UseFileServer();
            app.UseDefaultFiles();
            app.UseStaticFiles();

            app.UseIdentity();
            
            app.UseMvc(routes =>
            {
                // Areas support
                routes.MapRoute(
                    name: "areaRoute",
                    template: "{area:exists}/{controller=Home}/{action=Index}/{id?}");

                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
```

**Web.config**
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <rewrite>
      <rules>
        <clear />
        <rule name="Redirect to https" stopProcessing="true">
          <match url=".*" />
          <conditions>
            <add input="{HTTPS}" pattern="off" ignoreCase="true" />
          </conditions>
          <action type="Redirect" url="https://{HTTP_HOST}{REQUEST_URI}" redirectType="Permanent" appendQueryString="false" />
        </rule>
        <rule name="Redirect domain.com to www" patternSyntax="ECMAScript" stopProcessing="true">
          <match url=".*" />
          <conditions>
            <add input="{HTTP_HOST}" pattern="^foo.com.au$" />
          </conditions>
          <action type="Redirect" url="https://www.foo.com.au/{R:0}" />
        </rule>
        <rule name="Convert to lower case" stopProcessing="true">
          <match url=".*[A-Z].*" ignoreCase="false" />
          <action type="Redirect" url="{ToLower:{R:0}}" redirectType="Permanent" />
        </rule>        
      </rules>
    </rewrite>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="dotnet" arguments=".\foo.Web.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" />
  </system.webServer>
</configuration>
```

_Copied from original issue: aspnet/Mvc#6340_

**Comment by Tratcher** [comment]
_From @pranavkm on July 24, 2017 18:48_

cc @Tratcher

**Comment by Tratcher** [comment]
The trick is to make /status a sub application (not just a virtual directory) and then add a web.config to that folder that removes the aspNetCore handler.

**Comment by guardrex** [comment]
@Tratcher Quick ? ...

> trick is to make /status a sub application (not just a virtual directory)

I understand (and we've documented) that you can disable the handler for a sub-app, but can u clarify for a **_vdir_** based on pan-wang's comment ...

> under the vdir "healthcheck", you can add a web.config which remove the asp.net core handler defined in the site web.config.

https://github.com/aspnet/IISIntegration/issues/110#issuecomment-204014231

Did he mean to say "sub-dir" and not "vdir" there? It's come up on another doc issue dealing with Swagger endpoints hosted under the root domain.

**Comment by Tratcher** [comment]
Yes, he should have said sup app, vdirs do not honor web.config. People often use the terms vdir and sub app interchangeable, but for ANCM the difference is important.
