### ISSUE TITLE
Considering exposing binding information via environment variables

### ISSUE THREAD

**Issue by shirhatti** [aspnet/AspNetCoreModule#127]
cc @danroth27

**Comment by Tratcher** [comment]
No. I spoke to Dan and he only wants the ssl port and he only needs it for dev scenarios. He can get the value directly from VS via environment variable. There's no reason to involve ANCM.

**Comment by shirhatti** [comment]
@danroth27 @Tratcher can I close this?

**Comment by shirhatti** [comment]
@javiercn
