### ISSUE TITLE
Sortable log files with stdoutLogFile

### ISSUE THREAD

**Issue by bgever** [aspnet/AspNetCoreModule#130]
Opening a new issue, since [the previous one was closed without a proper solution and ignoring the problem](https://github.com/aspnet/AspNetCoreModule/issues/103).

The stdout logging is awesome and it works great.
However, when I look in my App Service folder, I see the following. 🤔 

```
> ls logs
D:\home\site\wwwroot
stdout_10652_20178414246.log
stdout_316_20178415450.log
stdout_6504_201783143517.log
stdout_8068_20178525714.log
stdout_9224_201784122443.log
```

I challenge you to try to find the latest file. 😉 (my personal record stands at 15 sec)
I'm already struggling to read timestamps with just 5 files. This becomes *utterly unmanageable* over time.

- The first digit seems to be the process ID (PID) as it doesn't match the port the server is binding to?
- And the timestamp uses a *short* date and time (?!) format. (not sure if date or time digit? 😨)

**I suggest to change to the following format: *prefix*\_*date*\_*pid***

Where the date uses the [format](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings) yyyyMMddhhmmss.

Example of the same files with the suggested format:

```
> ls logs
D:\home\site\wwwroot
stdout_20170803143517_6504.log
stdout_20170804122443_9224.log
stdout_20170804140246_10652.log
stdout_20170804150450_316.log
stdout_20170805025714_8068.log
```

Much better! 😄
And now it's sortable I can spot that on the 4th there were 3 files created and in what order. Useful!

Oh, and please document this filename behaviour on this page: https://docs.microsoft.com/en-us/aspnet/core/hosting/aspnet-core-module

For reference, this is my Web.config file:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified"/>
    </handlers>
    <aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false"/>
  </system.webServer>
</configuration>
```

CC: @glatzert

**Comment by shirhatti** [comment]
@bgever I do like your suggestion and I'm personally leaning towards make this change.
I'm going to leave this issue open to solicit more feedback especially since I'd want to know if the naming change breaks anyone.

**Comment by bgever** [comment]
@shirhatti That's great, thanks! Not sure if you meant internal feedback, but if the intent is to get public feedback, maybe it would be good to propose the change in the https://github.com/aspnet/Announcements repo, as many are watching it at it is likely relevant to them. You could link it back here for comments.

**Comment by pan-wang** [comment]
I think we can even add app name (or app path) as part of the log file name. This will help to sort the log files better. We need to change the order of some calls.

**Comment by bgever** [comment]
The app name can be handled manually in defining the `stdoutLogFile`. Also, it's unlikely two applications will be run from the same directory by default.

**Comment by bgever** [comment]
Thanks a lot @pan-wang & @guardrex. 👍
