### ISSUE TITLE
ANCM fails to proxy request to Kastrel on IPv6-only machine

### ISSUE THREAD

**Issue by glatzert** [aspnet/AspNetCoreModule#133]
On a Windows Server 2016 machine, with non-available IPv4 ANCM Fails to pass the request to Kestrel.

The protocol was removed via `netsh interface IPV4 uninstall`
After reenabling IPv4 via `netsh Interface IPV4 install` ANCM proceeds as expected.

**Comment by Tratcher** [comment]
Yes, it's hard-coded to send to `127.0.0.1`. I'd suggest changing it to localhost which prefers `::1` but Azure app services still disables ipv6. We could special case azure..

**Comment by glatzert** [comment]
Wouldn't using localhost work for azure as well?

**Comment by Tratcher** [comment]
It might, but since `::1` is prefered over `127.0.0.1` it may cause delays or errors.

**Comment by glatzert** [comment]
I'd assume the DNS resolve to not return the `::1`, but you probably should ask someone with Azure experience. I worked around the Problem by activating the IPv4 Protocol.
The IIS Hosting docs should probably mention the requirement of IPv4, so others will not be blocked, by the same error.

**Comment by shirhatti** [comment]
Glad to know @glatzert  was able to workaround his issue by enabling IPv4. At least for the time being, having only IPv6 enabled seems esoteric enough that we're not going to do anything about it.
