### ISSUE TITLE
Kestrel config binder should understand * and localhost

### ISSUE THREAD

**Issue by muratg** [aspnet/AspNetCoreModule#136]
_From @danroth27 on June 1, 2017 16:28_

_From @Tratcher on April 27, 2017 17:0_

The templates are going to enable SSL via config in dev and production. They need to set up the rest of the endpoints when they do this. https://github.com/aspnet/MetaPackages/pull/44 added the ability to bind to IPs and ports, but that makes for a poor user experience. In dev the templates want localhost, but will have to specify 127.0.0.1 (and ::1) if they want IPv6 support. In production they'll need to specify a public IP (0.0.0.0 and ::0).

Config should allow `localhost` that binds to 127.0.0.1 and ::1, and * that binds to 0.0.0.0 and ::0, using the same logic that kestrel applies to UseUrls values. Even better, implement this in Kestrel with a Listen that takes the string ip/host so you don't have to duplicate all of the logic.

_Copied from original issue: aspnet/MetaPackages#73_

_Copied from original issue: aspnet/KestrelHttpServer#1879_

**Comment by muratg** [comment]
_From @danroth27 on June 1, 2017 16:28_

_From @Tratcher on April 27, 2017 17:14_

@danroth27

**Comment by muratg** [comment]
_From @danroth27 on June 1, 2017 16:28_

@muratg @DamianEdwards @Eilon We chatted about this one and we think we need to get this into preview1. @muratg please assign.

**Comment by muratg** [comment]
_From @danroth27 on June 1, 2017 16:28_

We chatted *even more* and the fix is more complicated than we want to take right now. We'll have to tell folks to browse to localhost.

**Comment by muratg** [comment]
_From @danroth27 on June 1, 2017 16:28_

_From @muratg on May 25, 2017 22:14_

Assigning to @cesarbs for post preview2.

**Comment by muratg** [comment]
_From @danroth27 on June 1, 2017 16:28_

@glennc This issue is also the first in a series of issue that prevents enabling docker for out templates that use authentication.

**Comment by muratg** [comment]
_From @danroth27 on June 1, 2017 16:28_

_From @Tratcher on June 1, 2017 16:15_

Note this code is moving to Kestrel. https://github.com/aspnet/KestrelHttpServer/pull/1878

**Comment by muratg** [comment]
_From @pflannery on July 18, 2017 16:13_

> @glennc This issue is also the first in a series of issue that prevents enabling docker for out templates that use authentication.

I'm also seeing a port forwarding issue with the "dotnet new web" template and the current docker image "microsoft/dotnet"

I also see the warning with "Unable to bind to http://localhost:5000 on the IPv6 loopback interface: (Error -99 EADDRNOTAVAIL address not available)".

```console
root@24cf43adf652:~# dotnet new web -o www
Content generation time: 74.6508 ms
The template "ASP.NET Core Empty" created successfully.
root@24cf43adf652:~# cd www/
root@24cf43adf652:~/www# dotnet restore
  Restoring packages for /root/www/www.csproj...
  Generating MSBuild file /root/www/obj/www.csproj.nuget.g.props.
  Generating MSBuild file /root/www/obj/www.csproj.nuget.g.targets.
  Writing lock file to disk. Path: /root/www/obj/project.assets.json
  Restore completed in 680.72 ms for /root/www/www.csproj.

  NuGet Config files used:
      /root/.nuget/NuGet/NuGet.Config

  Feeds used:
      https://api.nuget.org/v3/index.json
root@24cf43adf652:~/www# dotnet run
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to bind to http://localhost:5000 on the IPv6 loopback interface: (Error -99 EADDRNOTAVAIL address not available)
Hosting environment: Production
Content root path: /root/www
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
```

My current solution is amending the Program.cs file to include `.UseUrls("http://*:5000")` which fixes port forwarding and removes the warning

```csharp
public static void Main(string[] args)
{
    var host = new WebHostBuilder()
        .UseUrls("http://*:5000")
        .UseKestrel()
        .UseContentRoot(Directory.GetCurrentDirectory())
        .UseIISIntegration()
        .UseStartup<Startup>()
        .Build();

    host.Run();
}
```

**Comment by muratg** [comment]
_From @natemcmaster on July 18, 2017 17:1_

@pflannery try using the `microsoft/aspnetcore` image instead. This image is designed to host web apps, and contains settings, such as [ASPNETCORE_URLS](https://github.com/aspnet/aspnet-docker/blob/e6e3dabb7c4f27509a378e65067a1439b62edc6d/2.0/stretch/runtime/Dockerfile#L4), that solve this issue for you.

**Comment by muratg** [comment]
_From @pflannery on July 18, 2017 17:53_

@natemcmaster Thanks. I just tried that and get blocked when running `dotnet --info`

```console
root@29095298643c:~# dotnet --info
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
```

Following that link didnt seem to solve my issue so I tried to run through the linux debian sdk commands here https://www.microsoft.com/net/core#linuxdebian but still same problem.

Following https://www.microsoft.com/net/core#dockercmd gets me as far as the EADDRNOTAVAIL error I reported above.

**Comment by muratg** [comment]
_From @natemcmaster on July 18, 2017 17:56_

@pflannery If you need to build an app in the container, use `microsoft/aspnetcore-build`. Let's continue this discussion here <https://github.com/aspnet/aspnet-docker> as this is separate from the intent of this issue.

**Comment by halter73** [comment]
@muratg I don't think *this* issue should be moved here. In triage we discussed whether ANCM could pick one of `127.0.0.1:{port}` or `[::1]:{port}` to bind to instead of `localhost:{port}`. This could potentially lead to less warnings, confusion and even possibly bugs.

The issue that was moved here seems to be discussing supporting `localhost` with Kestrel new `Listen()` methods. This is something we don't want to do because it's a bit of a leaky abstraction.

**Comment by muratg** [comment]
@halter73 Could you file one that recommends that then?  Closing this one.

**Comment by halter73** [comment]
#137

**Comment by Tratcher** [comment]
Why do you persist in making kestrel hard to use in standard usage scenarios?

**Comment by YUxiangLuo** [comment]
> _From @pflannery on July 18, 2017 16:13_
> 
> > @glennc This issue is also the first in a series of issue that prevents enabling docker for out templates that use authentication.
> 
> I'm also seeing a port forwarding issue with the "dotnet new web" template and the current docker image "microsoft/dotnet"
> 
> I also see the warning with "Unable to bind to http://localhost:5000 on the IPv6 loopback interface: (Error -99 EADDRNOTAVAIL address not available)".
> 
> ```
> root@24cf43adf652:~# dotnet new web -o www
> Content generation time: 74.6508 ms
> The template "ASP.NET Core Empty" created successfully.
> root@24cf43adf652:~# cd www/
> root@24cf43adf652:~/www# dotnet restore
>   Restoring packages for /root/www/www.csproj...
>   Generating MSBuild file /root/www/obj/www.csproj.nuget.g.props.
>   Generating MSBuild file /root/www/obj/www.csproj.nuget.g.targets.
>   Writing lock file to disk. Path: /root/www/obj/project.assets.json
>   Restore completed in 680.72 ms for /root/www/www.csproj.
> 
>   NuGet Config files used:
>       /root/.nuget/NuGet/NuGet.Config
> 
>   Feeds used:
>       https://api.nuget.org/v3/index.json
> root@24cf43adf652:~/www# dotnet run
> warn: Microsoft.AspNetCore.Server.Kestrel[0]
>       Unable to bind to http://localhost:5000 on the IPv6 loopback interface: (Error -99 EADDRNOTAVAIL address not available)
> Hosting environment: Production
> Content root path: /root/www
> Now listening on: http://localhost:5000
> Application started. Press Ctrl+C to shut down.
> ```
> 
> My current solution is amending the Program.cs file to include `.UseUrls("http://*:5000")` which fixes port forwarding and removes the warning
> 
> ```cs
> public static void Main(string[] args)
> {
>     var host = new WebHostBuilder()
>         .UseUrls("http://*:5000")
>         .UseKestrel()
>         .UseContentRoot(Directory.GetCurrentDirectory())
>         .UseIISIntegration()
>         .UseStartup<Startup>()
>         .Build();
> 
>     host.Run();
> }
> ```


**Thank you, this question wasted my day.**
