### ISSUE TITLE
Specifically forward request to either IPv4 or IPv6 loopback

### ISSUE THREAD

**Issue by halter73** [aspnet/AspNetCoreModule#137]
ANCM could pick one of 127.0.0.1:{port} or [::1]:{port} to bind to instead of localhost:{port}. This could potentially lead to less warnings, confusion and even possibly bugs when Kestrel can bind to one loopback adapter or not the other.

This would also probably require some changes to IISIntegration, since AFAIK only a port is currently set in the environment variable.

**Comment by shirhatti** [comment]
FYI @Tratcher

**Comment by Tratcher** [comment]
If it weren't for azure I would say always use `::1`. Have we tried using localhost?

**Comment by Tratcher** [comment]
Note it's already hard coded to 127.0.0.1

**Comment by halter73** [comment]
@Tratcher So we only need to change IISIntegration to specify 127.0.0.1?

**Comment by Tratcher** [comment]
Going backwards is not really an option (https://github.com/aspnet/AspNetCoreModule/issues/133). ANCM and Azure need to become IPv6 aware.

**Comment by halter73** [comment]
I figured we wouldn't want ANCM to support only IPv4. That's why I recommended that ANCM set *both* an IP address and port in an environment variable. ANCM could choose `::1` or `127.0.0.1` based on what's available.

**Comment by Tratcher** [comment]
How it chooses one or the other will be an interesting question Kestrel's the only one that really knows if bind fails. We should start by having ANCM test localhost to see if there's any lag if one or the other address isn't available, especially with Azure's unique sandbox. If not then we should implement the choice as close to kestrel as possible, reducing the complexity. E.g. we could have kestrel log that IPv6 error only as debug/trace.

**Comment by jkotalik** [comment]
@shirhatti let's make sure to triage this today.

**Comment by shirhatti** [comment]
This is already done https://github.com/aspnet/IISIntegration/pull/470
