### ISSUE TITLE
Question: ANCM with .NET Core 1.0 and 2.0

### ISSUE THREAD

**Issue by kimbell** [aspnet/AspNetCoreModule#140]
We currently have production servers running .NET Core 1.1 behind IIS using the ANCM. In the not to distant future we want to start supporting .NET Core 2.0 based applications. 

Will the original ANCM function with 2.0 based applications? Are we ready to rock now, or do we have to wait for an update?

**Comment by Tratcher** [comment]
ANCM is designed to be forwards and backwards compatible. There was a new version released with 2.0, what are you waiting for?

**Comment by kimbell** [comment]
I'm just working out what needs to be installed in order to support both 1.1 and 2.0 applications. When installing ANCM for 2.0, will this replace the 1.1 version or will they run side-by-side.

**Comment by Tratcher** [comment]
ANCM is always an in place backwards compatible update.

**Comment by jkotalik** [comment]
You should just need to install the Windows Server Hosting bundle, see [the 2.0 downloads page at the bottom](https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.0-download.md). These do not need to run side by side.

**Comment by kimbell** [comment]
Thanks for the information.
