### ISSUE TITLE
Failed to start process with commandline on IIS

### ISSUE THREAD

**Issue by MasDevProject** [aspnet/AspNetCoreModule#142]
Hi,
I'm trying to run my `aspnet core` on IIS.

This is my **web.config**:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>       
       <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>

    <aspNetCore processPath="" arguments=".\my.exe" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false" />
  </system.webServer>
</configuration>
```

and this is my **.csproj**:
```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <AssemblyName>Server</AssemblyName>
    <RootNamespace>Server</RootNamespace>
    <RuntimeIdentifier>win10-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup> ...
```

When I tried to contact my server I got a **HTTP Error 502.5 - Process Failure**.
And in my server manager I found this log:
```
Application 'MACHINE/WEBROOT/APPHOST/DEFAULT WEB SITE' with physical root 'C:\inetpub\wwwroot\' failed to start process with commandline ' .\my.exe', ErrorCode = '0x80070057 : 0.
```

- Windows server 2012 R2
- IIS 8.5 with the Aspnet module
- The target framework is **net462** because of I use net462 libs
- If I try to run the **my.exe** file with a cmd, it works correctly

**Comment by Tratcher** [comment]
Is `C:\inetpub\wwwroot\` the right directory?
Enable stdoutLogEnabled and see what it says in the logs.

**Comment by MasDevProject** [comment]
Yes, it is. I'm using the Default Web Site of IIS.
I tried to enable the logger but it does not write anything.
It looks like the process **my.exe** is not started (maybe because it is an exe and not a dll?)

`<aspNetCore processPath="" arguments=".\my.exe" ...  />`
**Process path** is void because it is an exe but I dont know if this is the right way, cant find documentation online

**Comment by Tratcher** [comment]
You also have to create the logs folder.

**Comment by MasDevProject** [comment]
Found the problem.
**.\my.exe** is a process and not an argument anymore.
Putting it as **processPath** make everything work as expected
`<aspNetCore processPath="" arguments="" ...  />`

**Comment by Thomasrnunez** [comment]
I've tried all the possible solutions that helped others from this forum post but nothing worked for me.
If you do all of the above and still see the same issue then open a command prompt window and navigate to your project and run "dotnet ". If you see an error like the one shown in this link: https://helpx.adobe.com/download-install/kb/error_on_launch.html

Then go to this link : https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows and download the right file for your OS and you application should startup.

**Comment by AmrTealeb** [comment]
This error might occur due to invalid json in your appsettings.json file

**Comment by ruchikaparikh** [comment]
> Hi,
> I'm trying to run my `aspnet core` on IIS.
> 
> This is my **web.config**:
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <configuration>
>   <system.webServer>
>     <handlers>       
>        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
>     </handlers>
> 
>     <aspNetCore processPath="" arguments=".\my.exe" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false" />
>   </system.webServer>
> </configuration>
> ```
> and this is my **.csproj**:
> 
> ```
> <Project Sdk="Microsoft.NET.Sdk.Web">
>   <PropertyGroup>
>     <TargetFramework>net462</TargetFramework>
>     <AssemblyName>Server</AssemblyName>
>     <RootNamespace>Server</RootNamespace>
>     <RuntimeIdentifier>win10-x64</RuntimeIdentifier>
>   </PropertyGroup>
> 
>   <ItemGroup>
>     <Folder Include="wwwroot\" />
>   </ItemGroup> ...
> ```
> When I tried to contact my server I got a **HTTP Error 502.5 - Process Failure**.
> And in my server manager I found this log:
> 
> ```
> Application 'MACHINE/WEBROOT/APPHOST/DEFAULT WEB SITE' with physical root 'C:\inetpub\wwwroot\' failed to start process with commandline ' .\my.exe', ErrorCode = '0x80070057 : 0.
> ```
> * Windows server 2012 R2
> * IIS 8.5 with the Aspnet module
> * The target framework is **net462** because of I use net462 libs
> * If I try to run the **my.exe** file with a cmd, it works correctly

Please do as per https://github.com/aspnet/IISIntegration/issues/616#issuecomment-409182438.
This solution works for me.
