### ISSUE TITLE
Running ASP.net Core 2.0 in a server cluster with IIS and Shared Configuration

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCoreModule#145]
_From @scionwest on September 2, 2017 18:2_

We are working towards deploying an ASP.Net Core 2.0 project onto our existing server cluster in AWS. The cluster uses IIS Shared Configuration and has _n_-App Pools. While reading [the documentation](https://docs.microsoft.com/en-us/aspnet/core/hosting/aspnet-core-module#aspnet-core-module-with-an-iis-shared-configuration), we found this little nugget of information that is a little vague.

> The ASP.NET Core Module installer runs with the privileges of the SYSTEM account. Because the local system account does not have modify permission for the share path which is used by the IIS Shared Configuration, the installer will hit an access denied error when attempting to configure the module settings in applicationHost.config on the share.
> The unsupported workaround is to disable the IIS Shared Configuration, run the installer, export the updated applicationHost.config file to the share, and re-enable the IIS Shared Configuration.

Does this mean the work-around is not supported, but running ASP.Net Core with Shared Configuration on (regardless of how that's achieved) _is_ supported? Or is this meant to be read as ASP.Net Core not being supported at all by Microsoft with Shared Configuration?

If it is not supported at all, what is Microsofts recommendation for shops that have an existing infrastructure running on a server cluster? We would prefer not to have to manage the deployment across multiple virtual machines manually and using Shared Configuration gives us a simple means to deploy once and let the new version scale out across _n_-server instances.

_Copied from original issue: aspnet/IISIntegration#412_

**Comment by Tratcher** [comment]
_From @guardrex on September 2, 2017 18:5_

@Tratcher I'll open a doc issue if we need a topic revision when this is resolved.

**Comment by scionwest** [comment]
Thanks for moving this to the right location

**Comment by kirankc** [comment]
Any update on this issue? We are in a similar situation and could use guidance on it.

**Comment by Tratcher** [comment]
@shirhatti ?

**Comment by scionwest** [comment]
Should I just open a support ticket with Microsoft on my enterprise msdn? We kind of need to deploy and can't get anything through GitHub it seems.

**Comment by HansHammel** [comment]
any progress?

**Comment by shirhatti** [comment]
The current solution is to disable IIS shared configuration before attempting to install ANCM.

The only way we'd work around it would be to impersonate the shared configuration identity and update the IIS configuration in the shared location which can have unintended consequences for scenarios like Web Farms. While some folks might be cognizant of the risks and still want to proceed we definitely can't force this change on everyone. We've grappled with this decision on multiple occasions in the past with other IIS modules as well such URL Rewrite and ARR and consistently come to the same conclusion.

@joeloff I'm currently aware that the msi fails and clearly indicates shared configuration is not supported, I'd be curious to know if the ServerHostingBundle clearly surfaces that information to the end user?

**Comment by joeloff** [comment]
@shirhatti The hosting bundle will show a message when IIS is not configured. The bundle essentially mimics the launch conditions from the MSI to surface the message and skip running it. If the launch conditions in the MSI changes your team will need to let us know so that we can update the hosting bundle conditions for the MSI to match.

**Comment by shirhatti** [comment]
I don't follow, this is not a launch condition. The custom action that modifies applicationHost.config fails with a well-known error code which is evident from the msi logs

**Comment by joeloff** [comment]
Ah, you mean the error from the MSI? No - it will only report that a package in the bundle failed to install, the detail is kept in the individual MSI log. However, if there is a way to detect this invalid condition, we could surface the warning earlier stating that we won't install ANCM. Not installing ANCM is better than not installing the bundle at all I think.

So this is something that the MSI only detects when it's busy installing, not before it installs?

**Comment by shirhatti** [comment]
@joeloff I'm missed your response. Currently, the msi doesn't even attempt to detect it. It attempts the custom action to update applicationHost.config and fails since it doesn't have access.

I'm closing this bug since it's not a common scenario to want to add a global module after you've already setup shared config and I've already shared a workaround.

Given that the docs already mention this as a known limitation of the installer there's nothing else actionable here.
