### ISSUE TITLE
AspnetcoreModule performance

### ISSUE THREAD

**Issue by baenziger** [aspnet/AspNetCoreModule#146]
We publish our .net core 2 app and .net core 2 WebApi to IIS 10 and experience slow performance. 
The AspNetCoreModule is not passing fast enough the requests to asp.net core application. The requests get queued which brings the app to a halt. 

If Kestrel is directly handling the requests (without IIS), none of these issues appear. Kestrel does not restart and the application is performing as expected.

In IIS, we set Queue Length to 10000. Practically no limit. In our application, we use Libuv with the option of thread count set to 50. Leaving default configuration makes Kestrel to be slow as well. 

The issue is that asp.net core module in IIS doesn't forward calls faster to the application. Any idea?

**Comment by Tratcher** [comment]
Can you quantify `very slow`? How many requests per second is Kestrel alone handling vs IIS + Kestrel? We know the reverse proxy setup adds significant overhead.

Is there anything interesting about the requests? E.g. large request or response bodies, lots of WebSockets, etc..

**Comment by baenziger** [comment]
We are testing using ApplicationInsights Performance testing, running a set of 50 URLs with 10, 50, 100, 500 and 1500 users.

Using kestrel, standalone we have good result. No failure for all sets – however, this only after changing the threadCount of Libuv. With the default value we also ran into some performance issues around the 500 user mark.

Using reverse proxy, requests aren’t processed when it crossed about 50-150 requests/second. Interestingly, when sending a large load of requests, they don’t show up at all in ApplicationInsights, but the site just times out. 
After cancelling the load test, it takes a few minutes and then the requests suddenly show up and the site is working again. In the meantime, browsers receive 502 errors. Thus, AspNetCoreModule seems to be ‘holding’ the requests – even though the HW resources are barely used.

**Comment by baenziger** [comment]
We have just run it using http.sys as Server and face the same issue.

**Comment by davidfowl** [comment]
> Using kestrel, standalone we have good result. No failure for all sets – however, this only after changing the threadCount of Libuv. With the default value we also ran into some performance issues around the 500 user mark.

Do you have machine specs? Where is your service running? What is it doing? Bumping the thread count can make things worse and might be hiding the actual problem.

**Comment by baenziger** [comment]
> Do you have machine specs? Where is your service running? What is it doing? Bumping the thread count can make things worse and might be hiding the actual problem.

The service is running on a 4 core cloud server with 8GB Ram on Windows Server 2016 in a European Datacentre. 
One part is a public facing website (in development) talking to a Webapi which in turn is connected to a Database.
In terms of problems in our application, the monitoring tools don't show anything really.

**Comment by ghost** [comment]
I have the same issues.

**Comment by baenziger** [comment]
@taoli0124, our issue was because we were starving the thread pool, as discussed in this issue https://github.com/aspnet/KestrelHttpServer/issues/2104. Changing all methods to async resolved it.
