### ISSUE TITLE
How do I get both DLL and XML schema file for manual installation

### ISSUE THREAD

**Issue by artisticcheese** [aspnet/AspNetCoreModule#147]
Hello,

Need to install this into nanoserver server via docker build and can not afford to run full installation and then copy file over, file sharing etc. Is there a proper way to handle installation in nanoserver where binaries are downloaded and extracted into image?

**Comment by shirhatti** [comment]
Simply put, you can't.
The only official distribution for ANCM for IIS is via the ServerHostingBundle.

**Comment by shirhatti** [comment]
If you want to MacGyver it, you can build from source or perhaps do a multistage container build where you install the exe and copy over the binary and schema file?

**Comment by artisticcheese** [comment]
Will it work in multistage build between servercore and nanoserver as destination?

**Comment by shirhatti** [comment]
It should work, but I haven't tried it myself

**Comment by artisticcheese** [comment]
Confirmed this is working as expected. For anybody who needs to do the same thins example is below 
```
From microsoft/iis as WindowsBuild
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'Continue'; $verbosePreference='Continue';"]
ADD https://download.microsoft.com/download/B/1/D/B1D7D5BF-3920-47AA-94BD-7A6E48822F18/DotNetCore.2.0.0-WindowsHosting.exe ".\hosting.exe"
RUN start-process -Filepath .\hosting.exe -ArgumentList @('/install', '/quiet', '/norestart') -Wait 


FROM microsoft/iis:nanoserver
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'Continue'; $verbosePreference='Continue';"]
COPY --from=WindowsBuild ["c:\\Windows\\System32\\inetsrv\\aspnetcore.dll", "c:\\Windows\\System32\\inetsrv\\"]
COPY --from=WindowsBuild ["c:\\Windows\\System32\\inetsrv\\config\\schema\\aspnetcore_schema.xml",  "c:\\Windows\\System32\\inetsrv\\config\\schema\\"]
```

**Comment by artisticcheese** [comment]
Here is full details how to do IIS + ASP.NET core + nanoserver
https://artisticcheese.wordpress.com/2017/09/10/using-multistage-docker-build-to-create-iis-asp-net-core-image-nanoserver/
