### ISSUE TITLE
space character in .NET core application name gives HTTP Error 502.5 - Process Failure error

### ISSUE THREAD

**Issue by grzech1983** [aspnet/AspNetCoreModule#148]
Hello,

I'm running Windows shared hosting and I had already few customers which uploaded their .NET Core 2.0 apps which contained space in their .NET application name (Some Application.dll).

Their web.config aspNetCore part look like:

```
<aspNetCore processPath="dotnet" arguments=".\Some Application.dll" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" />
```

When they are trying to run this app on IIS using aspNetCore handler they are getting:
```
HTTP Error 502.5 - Process Failure
```
error in browser and log file contains
```
Did you mean to run dotnet SDK commands? Please install dotnet SDK from: 

  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
```
Now if they change application file name to SomeApplication.dll the same application works just fine on IIS. The same application with space can be runned without any trouble from command line using:
```
dotnet "Some Application.dll"
```
so it is for sure something wrong with aspNetCore IIS handler.

Thanks

**Comment by Tratcher** [comment]
`arguments` needs the same quotes that you added for the command line. `arguments="&quote;.\Some Application.dll&quote;"` i think. That said, the publish tools should be doing this for you.

**Comment by shirhatti** [comment]
@vijayrkn Is this not already handled as part of the publish tooling?

**Comment by vijayrkn** [comment]
Doesn't look like it - https://github.com/aspnet/websdk/blob/c4d0ae7e2a897870c82b9ee289e2046fb0876fce/src/Publish/Microsoft.NET.Sdk.Publish.Tasks/WebConfigTransform.cs#L88. 

Can you please move the bug to websdk?

**Comment by shirhatti** [comment]
This issue was moved to aspnet/websdk#237
