### ISSUE TITLE
Does Kestrel server keep running when IIS / App pool craches

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCoreModule#149]
_From @sanjaycedti on September 11, 2017 8:33_

Does Kestrel server keep running even after IIS or app pool crashes because I want to make sure that if there is any operation that is in progress does not get impacted when IIS or app pool crashes?

_Copied from original issue: aspnet/IISIntegration#414_

**Comment by shirhatti** [comment]
No, the backend process does not keep running away when the worker process goes away.

Your backend application runs as child process of the IIS worker process. When we create the backend application, we assign it to a job object. This ensures the OS takes care of cleaning up child process and preventing orphaned processes.
https://github.com/aspnet/AspNetCoreModule/blob/a732b106f5ee4d17f74282ac28c50b0ef6fbd968/src/AspNetCore/Src/serverprocess.cxx#L996
