### ISSUE TITLE
How to host an ASP.NET Core app as sub-application of ASP.NET app in IIS

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCoreModule#150]
_From @elevate-andrewlock on September 11, 2017 14:42_

I've been trying to host an ASP.NET Core 2.0 app as a sub application of an ASP.NET app but I'm getting the following error when I try and browse the .net core site:

```
502.3 - Bad Gateway 
There was a connection error while trying to route the request
```

I can reproduce this with the "empty" .NET Core web app template.

I have installed installed the [.NET Core 2.0 Hosting bundle](https://aka.ms/dotnetcore.2.0.0-windowshosting), I have the .NET Core 2.0 SDK installed, and I'm just deploying to IIS locally at the moment. I've checked app pool configurations are correct.

I don't get an error if:
- I publish the .NET Core app to the local filesystem (e.g. _C:\Repos\testapp_)
- Create a new web site in IIS
- Set the physical path to the published app folder  (_C:\Repos\testapp_)

However, I _do_ get an error if: 
- I create a new web site in IIS  (e.g. _C:\Repos\testapp_)
- Set the physical path to  _%SystemDrive%\inetpub\wwwroot_
- Add a sub-application to the new web site
- Set the physical path to the published app folder  (_C:\Repos\testapp_)

Do I need to change anything in the _web.config_ file? [The documentation](https://docs.microsoft.com/en-us/aspnet/core/publishing/iis#configuration-of-sub-applications) describes hosting ASP.NET and ASP.NET Core apps as sub-apps of ASP.NET Core apps, but not the reverse configuration I'm attempting.

 I've tried adding `<clear />` to the `<system.webServer><handlers>` section before adding the `AspNetCoreModule`, but that resulted in other errors attempting to directly return a file etc).

I originally found this issue when trying to use [development time support](https://blogs.msdn.microsoft.com/webdev/2017/07/13/development-time-iis-support-for-asp-net-core-applications/), but that appears to have the same problem. 

_Copied from original issue: aspnet/IISIntegration#415_

**Comment by shirhatti** [comment]
It should *just* work. What issue are you observing? You shouldn't even have to clear the handlers section since ANCM is a greedy handler.

If I had to wager a guess, I'm going to say you have some issues with file permissions. Try checking your event log for more information

**Comment by ghost** [comment]
OK, I think I've narrowed this down to the IIS development time support for Visual Studio being broken and causing other issues. 

In short, attempting to use the development time debugging in VS resulted in the following _web.config_ being written to the root of the default app folder (_%SystemDrive%\inetpub\wwwroot_). 

This presumably was basically adding the ANCM to every app, so I was falling afoul of the issue [described in the docs](https://docs.microsoft.com/en-us/aspnet/core/publishing/iis#configuration-of-sub-applications) where the handler is added twice.

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <aspNetCore>
      <environmentVariables>
        <environmentVariable name="ASPNETCORE_ENVIRONMENT" value="Development" />
      </environmentVariables>
    </aspNetCore>
  </system.webServer>
</configuration>
```

Removing the web.config file means I can now host as a sub-application. 

Visual Studio dev time support for IIS seems to be completely broken however (giving the 502.3 - Bad Gateway error described above). Where should I file an issue for that?

**Comment by Tratcher** [comment]
The web.config you showed should not cause the issue described in the link, that issue was about inheriting the handlers section. @pan-wang does something bad happen in ANCM if the environmentVariables section is inherited?

**Comment by shirhatti** [comment]
@pan-wang **ping**

**Comment by pan-wang** [comment]
sorry, I did not receive the original notification from @Tratcher . it is not a good idea to deploy web.config to default app folder (%SystemDrive%\inetpub\wwwroot) which is mapped to IIS default website root. This will cause the handler inherit issue. IIS configuration will try to merge the handler and the environemntVariables and does not allow any duplicated name.

**Comment by ghost** [comment]
Just to be clear - I did not deploy the _web.config_ to the default app folder. Visual Studio did, when I enabled development-time debugging using IIS, and added an environment variable.

**Comment by Tratcher** [comment]
@BillHiebert

**Comment by John0King** [comment]
@Tratcher   Is there a way to config IIS Express in Visual Studio with a Asp.Net Core App to use a SubApplication Path ?
I try to set `"applicationUrl": "http://localhost:2820/subApp"`  in `iisSettings` node   but It doesn't work

**Comment by fabercs** [comment]
I do almost same things with the original question;
Differences are I am on production server, I have ASP.NET V4.0 application under `C:\WebApp`
I create new folder `C:\SubApp` and create new .net core subapp under this ASP.NET V4.0 webapp in IIS.

When I call my subapp endpoint, it gives  I get `500 - Internal Server Error`, and I can't get any stdout log or event log. 

Is it because of `web.config` inheritance, how can I solve this?

**Comment by Tratcher** [comment]
Share both web.configs

**Comment by fabercs** [comment]
@Tratcher So you mean to copy handler section from .net core sub app and paste it to asp.net main app's web.config. Then use this final web.config on both apps, am I right?

**Comment by Tratcher** [comment]
No, I meant show them to us so we can see if you have anything strange in them.

**Comment by fabercs** [comment]
Lol :)

Net core
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="dotnet" arguments=".\HalkWebServices.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" />
  </system.webServer>
</configuration>
```

Asp.Net

```
<?xml version="1.0"?>
<configuration>
  <configSections>
    <sectionGroup name="applicationSettings" type="System.Configuration.ApplicationSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" >
      <section name="MyApp.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
    </sectionGroup>
  </configSections>
  <system.web.extensions>
    <scripting>
      <webServices>
        <jsonSerialization maxJsonLength="50000000" />
      </webServices>
    </scripting>
  </system.web.extensions>
  <appSettings>
   ...
  </appSettings>
  <connectionStrings>
    ...
  </connectionStrings>
  <system.web>
    <sessionState timeout="20" mode="InProc" cookieName="_YDSid" regenerateExpiredSessionId="true" sessionIDManagerType="MyApp.CustomSessionIdManager"/>
   
    <httpCookies httpOnlyCookies="true"/>
    <pages validateRequest="false" enableSessionState="true">
      <controls>
        <add tagPrefix="CKEditor" assembly="CKEditor.NET" namespace="CKEditor.NET"/>
      </controls>
    </pages>
    <compilation debug="true" targetFramework="4.0">
      <assemblies>
        <add assembly="System.Web.Extensions.Design, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35"/>
        <add assembly="System.Design, Version=4.0.0.0, Culture=neutral, PublicKeyToken=B03F5F7F11D50A3A"/>
        <add assembly="System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=B77A5C561934E089"/>
        <add assembly="System.Data.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=B77A5C561934E089"/>
        <add assembly="mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=B77A5C561934E089"/>
      </assemblies>
    </compilation>
   
    <customErrors mode="RemoteOnly" defaultRedirect="Error.aspx">
      <error statusCode="400" redirect="Error.aspx?h=400"/>
      <error statusCode="401" redirect="Error.aspx?h=401"/>
      <error statusCode="403" redirect="Error.aspx?h=403"/>
      <error statusCode="404" redirect="Error.aspx?h=404"/>
      <error statusCode="405" redirect="Error.aspx?h=405"/>
      <error statusCode="406" redirect="Error.aspx?h=406"/>
      <error statusCode="407" redirect="Error.aspx?h=407"/>
      <error statusCode="410" redirect="Error.aspx?h=410"/>
      <error statusCode="408" redirect="Error.aspx?h=408"/>
      <error statusCode="409" redirect="Error.aspx?h=409"/>
      <error statusCode="500" redirect="Error.aspx?h=500"/>
      <error statusCode="501" redirect="Error.aspx?h=501"/>
      <error statusCode="505" redirect="Error.aspx?h=505"/>
    </customErrors>
    <httpRuntime maxRequestLength="81920" executionTimeout="300000" requestLengthDiskThreshold="35360" requestValidationMode="2.0"/>
    <httpHandlers>
      <add path="CaptchaImage.axd" verb="GET" type="MSCaptcha.CaptchaImageHandler, MSCaptcha"/>
    </httpHandlers>
    <httpModules>
      <add name="Session" type="System.Web.SessionState.SessionStateModule"/>
    </httpModules>
    <webServices>
      <protocols>
        <add name="HttpGet"/>
        <add name="HttpPost"/>
      </protocols>
    </webServices>
    <authentication mode="None"/>
    <trace enabled="false" localOnly="true"/>
  </system.web>

  <system.webServer>
    <urlCompression doDynamicCompression="true" doStaticCompression="true" dynamicCompressionBeforeCache="false"/>
    <caching>
      <profiles>
        <add extension=".png" policy="CacheUntilChange" varyByHeaders="User-Agent" location="Client"/>
        <add extension=".gif" policy="CacheUntilChange" varyByHeaders="User-Agent" location="Client"/>
        <add extension=".jpg" policy="CacheUntilChange" varyByHeaders="User-Agent" location="Client"/>
        <add extension=".jpeg" policy="CacheUntilChange" varyByHeaders="User-Agent" location="Client"/>
        <add extension=".js" policy="CacheUntilChange" varyByHeaders="User-Agent" location="Client"/>
        <add extension=".css" policy="CacheUntilChange" varyByHeaders="User-Agent" location="Client"/>
        <add extension=".axd" kernelCachePolicy="CacheUntilChange" varyByHeaders="User-Agent" location="Client"/>
      </profiles>
    </caching>
    <httpProtocol allowKeepAlive="true">
      <customHeaders>
        <add name="Access-Control-Allow-Origin" value="*"/>
      </customHeaders>
    </httpProtocol>
    <validation validateIntegratedModeConfiguration="false"/>
    <handlers accessPolicy="Read, Write, Script, Execute">
      <remove name="ChartImageHandler"/>
      <add name="MSCaptcha" verb="GET" path="CaptchaImage.axd" type="MSCaptcha.CaptchaImageHandler, MSCaptcha"/>
    </handlers>
    <staticContent>
      <remove fileExtension=".woff"/>
      <!-- In case IIS already has this mime type -->
      <mimeMap fileExtension=".woff" mimeType="application/x-font-woff"/>
    </staticContent>
  </system.webServer>
  <system.data>
    <system.transactions>
      <machineSettings maxTimeout="0:00:00"/>
    </system.transactions>
  </system.data>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="WebGrease" publicKeyToken="31bf3856ad364e35" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-1.5.2.14234" newVersion="1.5.2.14234"/>
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
  <system.serviceModel>
    <serviceHostingEnvironment multipleSiteBindingsEnabled="True" />
  </system.serviceModel>
    <MyApp.Properties.Settings>
      <setting name="MyApp_TegsoftDataProvider_DataProviderService"
        serializeAs="String">
        <value>http://172.21.67.200/Tobe/services/DataProvider</value>
      </setting>
      <setting name="MyApp_RequirementManagement_RequirementManagementService"
        serializeAs="String">
        <value>http://172.21.67.200/Tobe/services/RequirementManagement</value>
      </setting>
      <setting name="MyApp_RemoteCampaignManager_RemoteCampaignManagerService"
        serializeAs="String">
        <value>http://172.21.67.200/Tobe/services/RemoteCampaignManager</value>
      </setting>
    </MyApp.Properties.Settings>
  </applicationSettings>
</configuration>
```

**Comment by Tratcher** [comment]
That's a busy web.config. I don't see any obvious conflicts. @pan-wang ?

You may need to try simplifying the root web.config until you track down the conflict.

**Comment by pan-wang** [comment]
@fabercs IIS will show detailed error info (which configuration section is wrong) if you browse from locally or configure allowing remote details. I saw you turned on custom error. Could you please redefine 500 error in sub application to allow detailed error  https://docs.microsoft.com/en-us/iis/troubleshoot/diagnosing-http-errors/how-to-use-http-detailed-errors-in-iis

**Comment by John0King** [comment]
@fabercs  
1.  confirm you installed AspNetCoreModule aka. ANCM
2.  use different ApplicationPool for AspNet (v4) and AspNetCore ( no manage code )
3.  try use this config for AspNetCore
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <remove name="aspNetCore"/>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified"/>
    </handlers>
    <aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false"/>
    <modules>
      <remove name="WebDAVModule" />
    </modules>
  </system.webServer>
</configuration>

```
change the processPath and arguments in `aspNetCore` node to yours .

**Comment by carlowahlstedt** [comment]
The removal of the handler is what allowed me to run two asp.net core sites where one is a sub application of the other.

**Comment by shirhatti** [comment]
We've made a fix in the websdk that solves this problem. See https://github.com/aspnet/websdk/pull/377

You may need to upgrade you dotnet sdk if you aren't seeing this new publish behavior

**Comment by carlowahlstedt** [comment]
@shirhatti thanks, do you happen to know what version? I'm currently running 2.1.0 and I think 2.1.2 is current?

**Comment by shirhatti** [comment]
@vijayrkn Can you comment on which release the change is in?

**Comment by vijayrkn** [comment]
Stable CLI containing the fix is not released yet. 

You can try the preview version of the cli containing the fix from here - https://dotnetcli.blob.core.windows.net/dotnet/Sdk/release/2.1.4xx/dotnet-sdk-latest-win-x64.exe
