### ISSUE TITLE
Issue hosting site in IIS10 and Virtual Directory

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCoreModule#156]
_From @johncollinson2001 on September 14, 2017 11:9_

Hi,

I'm trying to host my .NET core 2.0 app in IIS 10, as a virtual directory of the default website. 

When browsing to the URL i get a 502.5 - Process Failure error. 

After looking in the event viewer, i see the following error: "Application 'MACHINE/WEBROOT/APPHOST/DEFAULT WEB SITE' with physical root 'C:\inetpub\wwwroot\' failed to start process with commandline ' ', ErrorCode = '0x80070057 : 0.", so dotnet.exe is not being called correctly.

I have set the app up as a website within IIS, which works just fine. It's only when using a virtual directory that it does not work.

Can anyone advise? Is there any known issues around setting up .net core apps as virtual directories?

Thanks,
John

_Copied from original issue: aspnet/Hosting#1206_

**Comment by Tratcher** [comment]
What's in the web.config's for the root site and your virtual directory? It's suspicious that the log says your command line args are missing.

There are some notes for common configurations in the docs:
https://docs.microsoft.com/en-us/aspnet/core/publishing/iis#configuration-of-sub-applications

**Comment by johncollinson2001** [comment]
The contents web.config is...

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <!-- To customize the asp.net core module uncomment and edit the following section. 
  For more info see https://go.microsoft.com/fwlink/?linkid=838655 -->
  <system.webServer>
    <handlers>
      <remove name="aspNetCore" />
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="dotnet" arguments=".\App.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="true" />
  </system.webServer>
</configuration>
```

I've got it working now as a sub website to the Default Web Site which gives me the structure I was hoping to achieve (e.g. http://host/app) . In the past I'd achieved this using virtual directories, however this was using IIS6 so quite a while ago.

Many thanks for the help :)

**Comment by Tratcher** [comment]
Indeed, people usually mistake virtual directories for sub applications. ASP.NET Core requires sub applications.

**Comment by jusefb** [comment]
Just in case somebody else stumbles across this issue, just removing the aspNetCore handler did not work for me. What worked is to disable inheritance for the `<system.webServer>`  section by adding the `<location path="." inheritInChildApplications="false">`. to the parent web.config element

```xml
<configuration>
    <location path="." inheritInChildApplications="false">
        <system.webServer>
            <!-- some content -->
        </system.webServer>
    </location>
</configuration>
```

hope this helps.
