### ISSUE TITLE
Handle app_offline.htm in in-process scenario

### ISSUE THREAD

**Issue by jkotalik** [aspnet/AspNetCoreModule#158]
In the inprocess mode, we should have a file watcher looking for app_offline.htm and shutdown the application when it is detected. See: https://github.com/aspnet/AspNetCoreModule/blob/bce531f61a051c09c9fc2b38a7e72cee6123c95f/src/AspNetCore/Src/application.cxx#L103-L110 for how it is handled in the out of process scenario.
@pan-wang @davidfowl

**Comment by davidfowl** [comment]
@jkotalik We'd use the file provider APIs to do this for the in process logic.

**Comment by pan-wang** [comment]
You don't need to create another one.  You can reuse the existing one.  I will take a look at how to refactor the code to make it easier for the inproc scenario





On 2017-09-19 21:35 , David Fowler<mailto:notifications@github.com> Wrote:


@jkotalik<https://github.com/jkotalik> We'd use the file provider APIs to do this for the in process logic.

**Comment by davidfowl** [comment]
> You don't need to create another one.  You can reuse the existing one.  I will take a look at how to refactor the code to make it easier for the inproc scenario

I rather not, I'd rather use managed code for this. We already have a file watcher that supports both polling and using the file system APIs wrapped up in a first class abstraction.

**Comment by muratg** [comment]
@pan-wang Your PR (https://github.com/aspnet/AspNetCoreModule/pull/174) should fix this, right?

**Comment by pan-wang** [comment]
Yes. It's in at native layer. With App_Offline, no managed code will be loaded so that we can support deployment scenario.

**Comment by jkotalik** [comment]
This was completed a while ago. app_offline logic is now shared between inprocess and out of process.
