### ISSUE TITLE
[InProc] Verify handling of two applications in same app pool. 

### ISSUE THREAD

**Issue by jkotalik** [aspnet/AspNetCoreModule#160]
After discussion, if a user tries to add two applications to the same app pool, we should error our (return 500s) on both applications. @davidfowl @pan-wang

**Comment by pan-wang** [comment]
You can only detect the existence of second application at runtime while the first application already started and served couple requests.  It will be wired the first app suddenly replies 500 error after returning couple 200 responses.





On 2017-09-19 22:58 , Justin Kotalik<mailto:notifications@github.com> Wrote:


After discussion, if a user tries to add two applications to the same app pool, we should error our (return 500s) on both applications. @davidfowl<https://github.com/davidfowl> @pan-wang<https://github.com/pan-wang>

**Comment by shirhatti** [comment]
If I'm not mistaken. This has already been resolved.
@jkotalik Feel free to re-open if that weren't the case.
