### ISSUE TITLE
AV if the old schema file which does not have hostingModel attribute is used

### ISSUE THREAD

**Issue by jhkimnew** [aspnet/AspNetCoreModule#171]
I ran into a worker process crash (AV) issue with the private ANCM file because I did not update the existing ANCM schema file with the new one which has the following new item:

<attribute name="hostingModel" type="string" />

The line of AV due to the config object is null: 

https://github.com/aspnet/AspNetCoreModule/blob/f130330db8d29e679eef70ee75b8d7f147489359/src/AspNetCore/Src/proxymodule.cxx#L89

**Comment by jkotalik** [comment]
This is done. @muratg can you add Working and Done labels to ANCM? 😄

**Comment by muratg** [comment]
Retroactively added the labels :)
