### ISSUE TITLE
Add necessary pInvokes for managed application

### ISSUE THREAD

**Issue by jkotalik** [aspnet/AspNetCoreModule#178]
Needed:
- Versioning
- Application triggering abort on the request
- Client abort
- User (for windows auth) and RequestIds from IIS
- Path and Pathbase (from virtual path)?
- Shutdown, Startup, and Abort cancellation token?
- Logging (providing the stdout file)

**Comment by jkotalik** [comment]
cc @pan-wang @shirhatti @Tratcher

**Comment by Tratcher** [comment]
We're unlikely to do these all at once. More likely we'll do the managed and native work for a single item at the same time, so I expect we'll want to track these as independent features.

**Comment by jkotalik** [comment]
Alright, I'll go ahead and make these individual issues on ANCM (most exist on IIS integration)

**Comment by pan-wang** [comment]
I think it will be good that for each feature we open one issue in ANCM to track native part and another one in IIS integration to track managed part.

**Comment by shirhatti** [comment]
Closing as this issue is now stale
