### ISSUE TITLE
AV on writing errors from ForwardingHandler::OnExecuteRequestHandler

### ISSUE THREAD

**Issue by jkotalik** [aspnet/AspNetCoreModule#187]
I think [the application manager](https://github.com/aspnet/AspNetCoreModule/blob/dev/src/AspNetCore/Src/forwardinghandler.cxx#L1399) needs a NULL check here. I ran this in testing full IIS with the in process mode.

**Comment by jhkimnew** [comment]
FYI, actually the pApplicationManager variable is never initialized in the problematic function.

**Comment by shirhatti** [comment]
I'm closing since it looks like this has been fixed.

**Comment by shirhatti** [comment]
https://github.com/aspnet/IISIntegration/blob/c3bc6fed9c38bb5f6003d56fe2537eee85085c18/src/AspNetCore/Src/proxymodule.cxx#L94
