### ISSUE TITLE
[PERF] Stream compressed responses

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCoreModule#19]
If the back-end process returns compressed responses (gzip) then ANCM/WinHttp will decompress the data and then the IIS compression module will re-compress it. This waists a lot of CPU.

Fix: disable automatic decompression on WinHttp (WinHttpHandler does it, so it should be possible) and stream the raw bytes back to the client.

**Comment by jhkimnew** [comment]
@Tratcher @pan-wang 

I tried to reproduce this issue but I can't. 
In the IIS Freb log, the dynamic compression is being skipped if the response is already encoded, which means that if the back-end compresses the response, the dynamic compression module does not re-compression.

FYI, attached the example of the freb log.
...
DYNAMIC_COMPRESSION_NOT_SUCCESS Reason="ALREADY_CONTENT_ENCODING" 23:27:28.178 
...

Would you give me the more detail information about this issue or the repro step?

**Comment by Tratcher** [comment]
This was filed based on a discussion with @pan-wang, I did not reproduce it. If WinHttp does not decompress the response then that's great.
