### ISSUE TITLE
Inprocess: AV when starting NativeIISSample app with out-of-process mode with full IIS server

### ISSUE THREAD

**Issue by jhkimnew** [aspnet/AspNetCoreModule#194]
STEPS TO REPRO:

1. Deploy debug build of aspnetcore.dll on full IIS server
2. Deploy the Inprocess AspnetCore web application of "NativeIISSample" which is available in IISIntegration repo to full IIS server.
3. Set the hostingModel attribute with empty string value as the following:

<aspNetCore processPath="dotnet" arguments=".\NativeIISSample.dll" stdoutLogEnabled="false" forwardWindowsAuthToken="false" hostingModel="" />

3. Send a request to the web application and check the Task Manager

EXPECTED:

No error.

ACTUAL:

You will see the werfault.exe process is shown.

**Comment by shirhatti** [comment]
#201
