### ISSUE TITLE
FREB: Usability: In PostStartCheck, we should not use ASPNETCORE_EVENT_PROCESS_START_ERROR_MSG 

### ISSUE THREAD

**Issue by jhkimnew** [aspnet/AspNetCoreModule#196]
Considering PostStartCheck() of the below attached code is to confirm if the process is successfully launched after the first success, we should use different error message when it fails. Currently we use the same error message between the first check and the second check and it will cause some confusion.

<><><>
HRESULT
SERVER_PROCESS::PostStartCheck(
    const STRU* const pStruCommandline,
    STRU*             pStruErrorMessage)
{

...
        if (GetExitCodeProcess(m_hProcessHandle, &processStatus))
        {
            // make sure the process is still running
            if (processStatus != STILL_ACTIVE)
            {
                hr = E_FAIL;
                pStruErrorMessage->SafeSnwprintf(
                    ASPNETCORE_EVENT_PROCESS_START_ERROR_MSG,

**Comment by muratg** [comment]
@shirhatti should we carry FREB related issues to a single issue elsewhere?

**Comment by pan-wang** [comment]
The code was changed and give more details about the failure.  Close the issue.
