### ISSUE TITLE
Inprocess: New feature request: Users should be able to switch hostingModel

### ISSUE THREAD

**Issue by jhkimnew** [aspnet/AspNetCoreModule#204]
STEPS TO REPRO:

1. Create an app with the NativeIISSample with setting outofprocess for the hostingModel property value
2. Send a request
3. Now switch to inprocess with setting inprocess for the hostingModel property value

EXPECTED:

The application now works in inprocess

ACTUAL:

Switching hostingModel is not implemented.

**Comment by jkotalik** [comment]
Open design question in https://github.com/aspnet/IISIntegration/issues/456. Closing in favor of that issue.
