### ISSUE TITLE
Inprocess: The Recycle() should be called only the application was successfully initialized

### ISSUE THREAD

**Issue by jhkimnew** [aspnet/AspNetCoreModule#205]
I ran into AV from the below stack because Recycle() is called without checking if the application was successfully created or not. The AV happened when the application fails to start, giving 502 error of mixed state of hosting model. 
_
IN_PROCESS_APPLICATION::~IN_PROCESS_APPLICATION()
{
    Recycle();
}

<><><>
0:003> kn
 # Child-SP          RetAddr           Call Site
00 000000a6`fab7e900 00007ffe`a9b513d6 aspnetcore!ASPNETCORE_CONFIG::QueryShutdownTimeLimitInMS+0xb [d:\gitroot\aspnetcoremodule\src\aspnetcore\inc\aspnetcoreconfig.h @ 99] 
01 000000a6`fab7e910 00007ffe`a9b511e0 aspnetcore!IN_PROCESS_APPLICATION::Recycle+0x46 [d:\gitroot\aspnetcoremodule\src\aspnetcore\src\inprocessapplication.cxx @ 479] 
02 000000a6`fab7e970 00007ffe`a9b54c1c aspnetcore!IN_PROCESS_APPLICATION::~IN_PROCESS_APPLICATION+0x40 [d:\gitroot\aspnetcoremodule\src\aspnetcore\src\inprocessapplication.cxx @ 207] 
03 000000a6`fab7e9b0 00007ffe`a9b58da8 aspnetcore!IN_PROCESS_APPLICATION::`scalar deleting destructor'+0x2c
04 000000a6`fab7e9e0 00007ffe`a9b587ab aspnetcore!APPLICATION::DereferenceApplication+0x68 [d:\gitroot\aspnetcoremodule\src\aspnetcore\inc\application.h @ 182] 
05 000000a6`fab7ea30 00007ffe`a9b6e58c aspnetcore!APPLICATION_MANAGER::GetApplication+0x4fb [d:\gitroot\aspnetcoremodule\src\aspnetcore\src\applicationmanager.cxx @ 136] 
06 000000a6`fab7f5d0 00007ffe`acd4d789 aspnetcore!CProxyModule::OnExecuteRequestHandler+0xcc [d:\gitroot\aspnetcoremodule\src\aspnetcore\src\proxymodule.cxx @ 98] 
07 000000a6`fab7f6a0 00007ffe`acd4d13b iiscore!NOTIFICATION_CONTEXT::RequestDoWork+0xb9 [inetsrv\iis\iisrearc\iis70\core\notificationcontext.cxx @ 1717] 
08 000000a6`fab7f6f0 00007ffe`acd4cf76 iiscore!NOTIFICATION_CONTEXT::CallModulesInternal+0x1ab [inetsrv\iis\iisrearc\iis70\core\notificationcontext.cxx @ 566] 
09 000000a6`fab7f800 00007ffe`acd4df64 iiscore!NOTIFICATION_CONTEXT::CallModules+0x36 [inetsrv\iis\iisrearc\iis70\core\notificationcontext.h @ 341] 
0a (Inline Function) --------`-------- iiscore!NOTIFICATION_MAIN::DoStateRequestExecuteHandler+0x5e [inetsrv\iis\iisrearc\iis70\core\mainnotification.cxx @ 742] 
0b 000000a6`fab7f860 00007ffe`acd51cd6 iiscore!NOTIFICATION_MAIN::DoWork+0x294 [inetsrv\iis\iisrearc\iis70\core\mainnotification.cxx @ 103] 
0c (Inline Function) --------`-------- iiscore!W3_CONTEXT_BASE::StartNotificationLoop+0x62 [inetsrv\iis\iisrearc\iis70\core\w3basecontext.cxx @ 1083] 
0d 000000a6`fab7fb90 00007ffe`af1c4c75 iiscore!W3_MAIN_CONTEXT::OnNewRequest+0x286 [inetsrv\iis\iisrearc\iis70\core\maincontext.cxx @ 107] 
0e (Inline Function) --------`-------- w3dt!UL_NATIVE_REQUEST::DoStateProcess+0x1b [inetsrv\iis\iisrearc\iisplus\w3dt\nativerequest.cxx @ 712] 
0f (Inline Function) --------`-------- w3dt!UL_NATIVE_REQUEST::DoWork+0x7c [inetsrv\iis\iisrearc\iisplus\w3dt\nativerequest.cxx @ 369] 
10 (Inline Function) --------`-------- w3dt!UL_RECEIVE_CONTEXT::DoWork+0x7c [inetsrv\iis\iisrearc\iisplus\w3dt\nativerequest.cxx @ 2305] 
11 000000a6`fab7fbd0 00007ffe`b39d1523 w3dt!WP_CONTEXT::OnCompletion+0xb5 [inetsrv\iis\iisrearc\iisplus\w3dt\wpcontext.cxx @ 340] 
12 000000a6`fab7fc10 00007ffe`b39d1490 W3TP!THREAD_POOL_DATA::ThreadPoolThread+0x73 [inetsrv\iis\iisrearc\iisplus\w3tp\thread_pool.cxx @ 1108] 
13 000000a6`fab7fc60 00007ffe`b39d1439 W3TP!THREAD_POOL_DATA::ThreadPoolThread+0x30 [inetsrv\iis\iisrearc\iisplus\w3tp\thread_pool.cxx @ 970] 
14 000000a6`fab7fca0 00007ffe`c55a2774 W3TP!THREAD_MANAGER::ThreadManagerThread+0x49 [inetsrv\iis\iisrearc\iisplus\w3tp\thread_manager.cxx @ 840] 
15 000000a6`fab7fce0 00007ffe`c5900d51 KERNEL32!BaseThreadInitThunk+0x14 [base\win32\client\thread.c @ 64] 
16 000000a6`fab7fd10 00000000`00000000 ntdll!RtlUserThreadStart+0x21 [minkernel\ntdll\rtlstrt.c @ 997]

**Comment by pan-wang** [comment]
this is fixed by #201
