### ISSUE TITLE
Inprocess: Wrong event warning message

### ISSUE THREAD

**Issue by jhkimnew** [aspnet/AspNetCoreModule#207]
STEPS TO REPRO:
1. Create two in-process application and make them running with a single worker process (w3wp.exe)
2. Send a request to each application, only the first request will give 200 OK and the other will give 500 error
3. Look at the event log and check the event log shows the right reason of the 500 error

EXPECTED:

The event log shows the right reason of the 500 error

ACTUAL:

Below event log message is shown. In this user scenario, there I no mixed hosting model. So, the error message should indicate that only a single inprocess mode application is allowed per worker process.

<><><>
Mixed hosting model is not supported. Application '/LM/W3SVC/3/ROOT' configured with different hostingModel value '' other than the one of running application(s).
<><><>

**Comment by pan-wang** [comment]
I could not repro it.
On my test box, it shows "Only one inprocess application is allowed per IIS application pool. Please assign the application '/LM/W3SVC/6/ROOT' to a different IIS application pool."

**Comment by jhkimnew** [comment]
This issue is not reproducible. There was a test issue and I got a wrong event. 
Closing issue.
