### ISSUE TITLE
Inprocess: Usability: Error handling required for the first request if the app is set with inprocess mode wrongly 

### ISSUE THREAD

**Issue by jhkimnew** [aspnet/AspNetCoreModule#215]
If users set the process mode incorrectly, setting inprocess mode even though the app does not support the inprocess mode.

The current behavior is to show error message after 2 minutes (the default request time-out) because we don't have error handling.

**Comment by jkotalik** [comment]
This was done in IISIntegration by 06348dded7c869b60459283fcb6cbe389a868ebf

**Comment by jkotalik** [comment]
@jhkimnew I am confused about what this issue was about. Can you clarify if it is still an issue?

**Comment by jhkimnew** [comment]
@jkotalik Here is the repro step. Please try this and resolve this issue if this is already fixed.

1. Create a app with the previous .Net Core SDK, which is not support the new inprocess feature of ANCM
2. Deploy the app to IIS
3. Set hostingModel with Inprocess even though the app does not support inprocess
4. Send a request to the newly deployed app

EXPECTED:

Users get an error message which tells that the app does not support inprocess mode hostingModel.

ACTUAL:

I got general error (5xx) after 2 minutes. Obviously the error message is not helpful to troubleshoot the issue.
