### ISSUE TITLE
Inprocess: While stress testing with NativeIISSample app, the memory usage keeps increasing

### ISSUE THREAD

**Issue by jhkimnew** [aspnet/AspNetCoreModule#217]
While stress testing with the NativeIISSample app, the memory usage keeps increasing. This might be a memory leak.

**Comment by jkotalik** [comment]
I'll put this under dotTrace when I get the chance. Good find.

**Comment by jkotalik** [comment]
I investigated recently and I didn't see any memory leaks. Dotnet will not aggressively garbage collect until around 400 MB of process memory. The amount of heap memory used never got above 7 MB and didn't grow after ~20 minutes. Closing for now.
