### ISSUE TITLE
Inprocess: Env variables specified in web.config aren't applied

### ISSUE THREAD

**Issue by shirhatti** [aspnet/AspNetCoreModule#218]
Setting environment variables in `web.config` doesn't work.

```xml
<aspNetCore ...>
  <environmentVariables>
    <environmentVariable name="foo" value="bar" />
  </environmentVariables>
</aspNetCore>
```

**Comment by shirhatti** [comment]
Whatever solution we devise for this issue should also keep https://github.com/aspnet/IISIntegration/issues/460 in mind

**Comment by Tratcher** [comment]
This has come up a few times. The overall plan is to honor every ANCM web.config setting possible. In this case setting the env vars on the worker process should be possible.

**Comment by jkotalik** [comment]
@shirhatti I think we will probably just add a pInvoke to add in the collection of environment variables. Then the server would read them and call UseSetting(). [Similar to what IISIntegration does today](https://github.com/aspnet/IISIntegration/blob/dev/src/Microsoft.AspNetCore.Server.IISIntegration/WebHostBuilderIISExtensions.cs#L57-L60) except the environment variables would be read via a pInvoke.
Something like this:
```csharp
  if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows) && NativeMethods.is_ancm_loaded())
            {
                hostBuilder.UseSetting(nameof(UseIISIntegration), "true");
                hostBuilder.CaptureStartupErrors(true);

                var applicationPath = NativeMethods.http_get_application_full_path();
                var environmentVariables = NativeMethods.http_get_environment_variables();
                foreach (var environmentVariable in environmentVariables)
                {
                      hostBuilder.UseSetting(environmentVariable);
                }
                hostBuilder.UseContentRoot(applicationPath);
                return hostBuilder.ConfigureServices(services =>
                {
                    services.AddSingleton<IServer, IISHttpServer>();
                    services.AddAuthenticationCore();
                });
            }
```

**Comment by Tratcher** [comment]
No, you want them set as proper env vars before Program.Main executes, app code may read them.

**Comment by shirhatti** [comment]
Closing as dupe of https://github.com/aspnet/IISIntegration/issues/536
