### ISSUE TITLE
Which module version for ASP.Net Core 2.0?

### ISSUE THREAD

**Issue by Tobias-08** [aspnet/AspNetCoreModule#219]
Hi,
I did not find any docs which version of the module is required for using ASP.NET Core 2.0 in IIS. Do I have to upgrade to version 2.0 of the module (https://download.microsoft.com/download/B/1/D/B1D7D5BF-3920-47AA-94BD-7A6E48822F18/DotNetCore.2.0.0-WindowsHosting.exe ) or is it fine to use version 1.1.2?

We are using the full .net framework (4.6.1) as our runtime so we do not need any .net core 2.0 runtime components for IIS.

Thanks!
Tobias

**Comment by Tratcher** [comment]
Thus far every version of ANCM it's compatible with every version of Asp.Net Core, but the 2.0 version adds addition functionality so I recommend installing it.

**Comment by Tobias-08** [comment]
Thanks! Are there any release notes that elaborate on the additional functionality?

**Comment by Tratcher** [comment]
@shirhatti @danroth27, does ANCM have its own release notes anywhere? It's not included in the ASP.NET Core list.

IISIntegration's notes cover features that were reactions to ANCM changes:
https://github.com/aspnet/IISIntegration/releases/tag/rel/2.0.0

**Comment by shirhatti** [comment]
The ANCM release notes were out of date. I've updated the https://github.com/aspnet/AspNetCoreModule/releases in this repo to reflect our public releases
