### ISSUE TITLE
Inprocess: when worker process (w3wp.exe) is started with 32 bit mode, inprocess app fails to start

### ISSUE THREAD

**Issue by jhkimnew** [aspnet/AspNetCoreModule#220]
STEPS TO REPRO:
1. Set enable32BitAppOnWin64 to true as the following example:

            <add name="DefaultAppPool" enable32BitAppOnWin64="true" />

2. Send a request to NativeIISSample app which is configured to run in Inprocess mode

EXPECTED:

No issue

ACTUAL:

500 error because the LoadManagedApplication() fails, the line "if (dwResult == WAIT_OBJECT_0)".

**Comment by shirhatti** [comment]
@jhkimnew Is this just a stale issue? If it no longer applies, can you go ahead and close this?

**Comment by jhkimnew** [comment]
@jkotalik Is this fixed?

**Comment by jkotalik** [comment]
This is finished for sure. 32 bit ANCM works.
