### ISSUE TITLE
Please allow static port assignment

### ISSUE THREAD

**Issue by borgdylan** [aspnet/AspNetCoreModule#222]
When using dynamic port assignment on App Service, we are getting cases where IIS ends up connecting to the kestrel process of another site running in the same App Service Plan. If ANCM allowed picking a port manually to make sure that once an application starts, no other site could take that port away from it/reuse it. This would solve the issue.

**Comment by ericgla** [comment]
You can set the environment variable ASPNETCORE_PORT to force ANCM to use a specific port.

`<aspNetCore ....>
    <environmentVariables>
        <environmentVariable name="ASPNETCORE_PORT" value="12345" 
    </environmentVariables>
    </aspNetCore>
`

**Comment by borgdylan** [comment]
AFAIK, it is given by ANCM. ANCM does not read that environment variable.

**Comment by jkotalik** [comment]
Yeah, ANCM selects a random port.  See https://github.com/aspnet/AspNetCoreModule/blob/dev/src/AspNetCore/Src/serverprocess.cxx#L81. 

We are making a few improvements to ANCM today such that the static port assignment will be less of an issue. The primary one will be a new inprocess model which will run dotnet in the same process as w3wp, removing the need to launch dotnet and select a new port. 

If you are seeing IIS connecting to another backend, would it be possible to share any logs or information?That is a serious issue that we would like to fix. If there is private material, you may send it to my personal email and omit any details.

**Comment by borgdylan** [comment]
I am using the desktop CLR, not CoreCLR. Can that be hosted like dotnet like Helios used to do?

**Comment by davidfowl** [comment]
No it will not work for full Framework. It’s core clr only.

**Comment by ericgla** [comment]
We use this environment variable is production, and the environment variable port takes precedence over selecting a random port as long as it's in the valid port range.  See
[https://github.com/aspnet/AspNetCoreModule/blob/dev/src/AspNetCore/Src/serverprocess.cxx#L129](https://github.com/aspnet/AspNetCoreModule/blob/dev/src/AspNetCore/Src/serverprocess.cxx#L129)

**Comment by shirhatti** [comment]
As pointed out by @ericgla, there is an unsupported way to do this by setting the `ASPNETCORE_PORT` environment variable.
Feel free to use this if you're can guarantee that the ephemeral port you chose will always be available.
