### ISSUE TITLE
502.3 An operation was attempted on a nonexistent network connection

### ISSUE THREAD

**Issue by halter73** [aspnet/AspNetCoreModule#235]
_From @cinaradem on November 6, 2017 22:15_

hi,
my application on azure web app is working.
asp.net core 2.0 version.
but I often encounter the 502.3 error that I do not know why. When I examine the freb logs, "An operation was attempted on a nonexistent network connection.
  (0x800704cd) "and" There was a connection error while trying to route the request.
"but I have no idea about these faults.
I have checked the previous 502.3 errors and wrote a problem with asp.net core 1.1, but the problem still continues.
The site is a high hit area.
I would appreciate your help.

[freblog.txt](https://github.com/aspnet/KestrelHttpServer/files/1447948/freblog.txt)

_Copied from original issue: aspnet/KestrelHttpServer#2148_

**Comment by albigi** [comment]
are you flushing the response progressively using Chunked Transfer Encoding in your dotnet app?

**Comment by cinaradem** [comment]
I am using the dotnet core compression library. I can not see the 502 faults on the application insight.
can this error be between acis iis and asp.net core?
its startup.cs



   public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
 app.UseMiddleware<ResponseCompressionQualityMiddleware>(new Dictionary<string, double>
                {
                    {"br", 1.0},
                    {"gzip", 0.9}
                })
                .UseResponseCompression();


            app.UseRequestLocalization(new RequestLocalizationOptions
            {
                DefaultRequestCulture = new RequestCulture("tr-TR"),
                // Formatting numbers, dates, etc.
                SupportedCultures = new List<CultureInfo>
                {
                    new CultureInfo("tr-TR")
                },
            });


            app.UseFileServer(new FileServerOptions()
            {

                FileProvider = new PhysicalFileProvider(Path.Combine(Directory.GetCurrentDirectory(), @"wwwroot")),
                RequestPath = new PathString("/v1"),
            });
            app.UseStaticFiles(new StaticFileOptions
            {
                OnPrepareResponse = ctx =>
                {
                    const int durationInSeconds = 60 * 60 * 24;
                    ctx.Context.Response.Headers[HeaderNames.CacheControl] =
                        "public,max-age=" + durationInSeconds;
                }
            });
   app.UseMiddleware<CacheMiddleware>();

            app.UseMvc(routes =>
                  {
                      routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
                  });
}

cachemiddleware.cs

 public class CacheMiddleware
    {
        private RequestDelegate _next;
        private HtmlMinificationOptions _minificationOptions;
        public CacheMiddleware(RequestDelegate next)
            : this(next, null)
        {
        }
        public CacheMiddleware(RequestDelegate next, HtmlMinificationOptions minificationOptions)
        {
            _next = next;
            _minificationOptions = minificationOptions;
        }
        public async Task Invoke(HttpContext context)
        {
            var stream = context.Response.Body;
            if (_minificationOptions != null)
            {
                var filter = _minificationOptions.ExcludeFilter;
                if (Regex.IsMatch(context.Request.Path, filter))
                {
                    await _next(context);
                    return;
                }
            }

            try
            {
                using (var buffer = new MemoryStream())
                {
                    context.Response.Body = buffer;
                    await _next(context);
                    var isHtml = context.Response.ContentType?.ToLower().Contains("text/html");

                    buffer.Seek(0, SeekOrigin.Begin);
                    using (var reader = new StreamReader(buffer))
                    {
                        string responseBody = await reader.ReadToEndAsync();
                        if (context.Response.StatusCode == 200 && isHtml.GetValueOrDefault())
                        {
                            responseBody = Regex.Replace(responseBody,
                                @">\s+<", "><", RegexOptions.Compiled);
                            responseBody = Regex.Replace(responseBody,
                                @")(.|\n))*-->", "", RegexOptions.Compiled);
                        }
                        var bytes = Encoding.UTF8.GetBytes(responseBody);
                        using (var memoryStream = new MemoryStream(bytes))
                        {
                            memoryStream.Seek(0, SeekOrigin.Begin);
                            await memoryStream.CopyToAsync(stream);
                        }
                    }

                }
            }
            finally
            {
                context.Response.Body = stream;
            }

        }
    }

**Comment by albigi** [comment]
the 502 error is surely coming from the IIS on App Service which is acting like a reverse proxy. what it is actually complaining about is an invalid response from the dotnet application it is proxying to.

what I observe in the failed request trace is initially data starts to flow just fine, then suddenly the connection to the backend application goes down.
do you have Kestrel logs from the application to match with the 502 errors? it could be the application faults at some point (HTTP error 500) or dotnet crashes and gets restarted for some reason.

another note: the failed request trace shows the response was of type text/html, therefore likely being processed by the CachingMiddleware. did you notice if the same problem happens for requests skipping that middleware in particular?

**Comment by shirhatti** [comment]
We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
