### ISSUE TITLE
Forward TLS token binding

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCoreModule#24]
_From @Tratcher on November 10, 2015 19:14_

http://tools.ietf.org/html/draft-popov-token-binding-00
http://tools.ietf.org/html/draftbalfanz-https-token-binding-00
http://www.ietf.org/proceedings/91/slides/slides-91-uta-2.pdf
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http.Features/ITlsTokenBindingFeature.cs
Win10+

_Copied from original issue: aspnet/IISIntegration#31_

**Comment by shirhatti** [comment]
@Eilon Is this what you were referring to when we spoke earlier today?

**Comment by Eilon** [comment]
@shirhatti I believe so, yes.

**Comment by shirhatti** [comment]
Tracked in IISIntegration. Closing this issue
