### ISSUE TITLE
Move CreateLogFile to a separate utility function

### ISSUE THREAD

**Issue by jkotalik** [aspnet/AspNetCoreModule#244]
https://github.com/aspnet/AspNetCoreModule/blob/9313710fd0e0dd31eaaa81ced6520bb0096bf917/src/AspNetCore/Inc/aspnetcoreconfig.h#L64-L68 should be moved to a shared location for inprocess and out of process applications. It doesn't logically fit with configuration.

**Comment by muratg** [comment]
Needed? We don't have a public API here, right? So we can do this anytime?

**Comment by pan-wang** [comment]
Old implementation. Not exist anymore
