### ISSUE TITLE
Support standalone applications for In-Process ANCM.

### ISSUE THREAD

**Issue by jkotalik** [aspnet/AspNetCoreModule#251]
Currently today we [always search for dotnet.exe ](https://github.com/aspnet/AspNetCoreModule/blob/dev/src/AspNetCore/Src/inprocessapplication.cxx#L449)without reading the processPath in web.config. We should read whether the processPath is for dotnet or not and handle standalone applications accordingly. hostfxr.dll should be in the standalone application, but we need to confirm that calling hostfxr_main with the standalone exe works correctly. 
cc/ @pan-wang @Tratcher

**Comment by shirhatti** [comment]
Blocked on https://github.com/dotnet/core-setup/issues/3458

**Comment by muratg** [comment]
This done in the other repo.
