### ISSUE TITLE
Verify in-process fails fast and logs error message when running with Full Framework.

### ISSUE THREAD

**Issue by jkotalik** [aspnet/AspNetCoreModule#255]
As we don't support full framework for in-process, we want to fail fast and make it very apparent that they must target core. This check would happen in the shim.

**Comment by muratg** [comment]
@jkotalik this should be good to go now, right?

**Comment by Eilon** [comment]
@muratg / @jkotalik - anything to do here for preview1?

**Comment by jkotalik** [comment]
Done by https://github.com/aspnet/IISIntegration/commit/e035d0ed96440e2b0f20374edcf37af9a9701497.
