### ISSUE TITLE
AspNetCoreModule needs to abort failed responses

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCoreModule#26]
_From @Tratcher on November 19, 2015 20:2_

https://github.com/aspnet/KestrelHttpServer/issues/341#issuecomment-155245802

If the back-end server fails while writing out the response body (after the first 8kb) and closes/resets the connection, platform handler does not correctly fail the response to the client.

For a chunked request that fails sometime before the final chunked terminator the handler mistakenly adds the missing terminator. This is problematic because it tells the client the response completed successfully. It should have just closed/reset the connection.

Content-Length responses that fail after sending 8kb just hang.

_Copied from original issue: aspnet/IISIntegration#39_

**Comment by Tratcher** [comment]
_From @muratg on February 8, 2016 18:26_

@Tratcher is this still pending?

**Comment by Tratcher** [comment]
I tested with private builds and the behavior has improved, but it is still intermittently incorrect, especially if only a small amount of data has been sent before the back-end connection closes.

**Comment by Tratcher** [comment]
@rynowak, @glennc said you keep running into this as a response truncation issue?

**Comment by Tratcher** [comment]
_From @glennc on August 5, 2016 20:16_

@rynowak When using IIS the problem of JSON.NET throwing on circular models is exacerbated by the ANCM not severing the connection appropriately.

I can use HTTPClient to grab data from a web api in my controller and send that to a view, and not know that anything is broken if I don't have much data. In my case it was happily showing a single result on my page, and leaving out the rest. I didn't even realize until I moved it to Linux and then I would get exceptions and the app would fail.

**Comment by Tratcher** [comment]
_From @muratg on August 17, 2016 16:42_

@shirhatti Is the change not in ANCM? Why assign it back to @Tratcher

**Comment by Tratcher** [comment]
_From @shirhatti on August 17, 2016 17:41_

Repro app https://github.com/shirhatti/ConnectionCloseRepro

**Comment by Tratcher** [comment]
_From @shirhatti on August 17, 2016 17:42_

@muratg I'll assign it to @jhkimnew to further investigate

**Comment by shirhatti** [comment]
Fixed in 4569d6d6d53aafd355da6acc91056f84e9f284a7
