### ISSUE TITLE
limit the number of log files

### ISSUE THREAD

**Issue by pan-wang** [aspnet/AspNetCoreModule#261]
When user enables stdout in web.config, ANCM will create a log file for each child process and never clean/remove it. This will leave too many log files. We need a mechanism to clean/remove stale log files.

**Comment by jkotalik** [comment]
This feature would be for both in-process and out-of-process applications. Proposal: add two configuration options called "MaxLogFileCount" and "MaxLogFileSize" to match IIS's behavior. On creation of a log file or exceeding the file size, we would check the number of log files and delete the oldest one if we exceed the maximum.

**Comment by shirhatti** [comment]
This is a lower priority than the diagnostics work

**Comment by shirhatti** [comment]
Since we've added the named pipe to capture stderr I'm going ahead and closing this since I expect usage of this feature to drop over time. Feel-free to re-open if you feel strongly about this.
