### ISSUE TITLE
AspNetCoreModuleX64Location and AspNetCoreModuleX86Location are wrong

### ISSUE THREAD

**Issue by pakrym** [aspnet/AspNetCoreModule#263]
During https://github.com/aspnet/AspNetCoreModule/commit/c12c938d4a69b08f7ea7a133f5139882c4f8caca `.props` wasn't updated:

https://github.com/aspnet/AspNetCoreModule/blob/dev/nuget/Microsoft.AspNetCore.AspNetCoreModule.props#L4

/cc @jkotalik

**Comment by jkotalik** [comment]
#264
