### ISSUE TITLE
ANCM in-process

### ISSUE THREAD

**Issue by glennc** [aspnet/AspNetCoreModule#265]
Uber issue for supporting in-process hosting in ANCM.

Initial testing has shown that an in-process hosting option in ANCM will provide significant performance and diagnostic gains when running with IIS.

In-process will not be the default hosting model for some time.

**Comment by glennc** [comment]
@jkotalik outside of not being able to have multiple apps in a single app pool I am not clear what all the downsides to in-proc are. Are there other limitations?

**Comment by DamianEdwards** [comment]
Clarification regarding "default": it **is** intended that in-process would become the default for new ASP.NET Core projects targeting 2.1 or higher.

**Comment by jkotalik** [comment]
@glennc I don't think there are other main downsides from a customer standpoint, besides being windows specific. 
@DamianEdwards are we still under the assumption that in-proc will be the default, but opt-in for 2.1?

**Comment by DamianEdwards** [comment]
The assumption is that **new** 2.1 projects use in-proc, existing apps or projects updated to 2.1 would not. We need to design how to make that happen.

**Comment by Tratcher** [comment]
It's a new project setting you would add to the template (launch settings?). New projects would get it but upgraded ones wouldn't have it.

On a different note, making this the default for 2.1 is aggressive from a quality perspective. The last schedule I saw did not include any public previews with a working tooling experience so we'll get minimal feedback before 2.1 releases.

The other new restriction is that the bitness of your app (and installed runtime) will now have to match the bitness of your app pool.

**Comment by John0King** [comment]
Does this allow us to direct copy/replace files without stop application pool first ?

**Comment by jkotalik** [comment]
@John0King Today you can drop an app_offline.htm in the application directory to stop your application. I'm assuming you are referring to shadow copying, which is not a change that will be done through this feature.

**Comment by shirhatti** [comment]
Closing this uber issue since this work is being tracked at https://github.com/aspnet/IISIntegration/projects/1

**Comment by muratg** [comment]
This is not finished. Keeping this open for this board's sake.

**Comment by tibitoth** [comment]
Will in-process hosting be available for Full CLR + ASP.NET Core applications too?

**Comment by jkotalik** [comment]
AspNetCore applications compiled to the Full CLR are not supported. We didn't have time to land that feature for 2.1. We will consider it for future releases.

**Comment by tibitoth** [comment]
I'm sad to hear that. Enterprise environments really need this feature with Full CLR support. Without this we can't migrate to ASP.NET Core because of the performance impact of out-proc IIS described in this blog post: https://odetocode.com/blogs/scott/archive/2016/10/25/asp-net-core-and-the-enterprise-part-2-hosting.aspx

**Comment by jkotalik** [comment]
With ANCM in-process, one of the main goals is to significantly improve the performance for AspNetCore applications behind IIS. Our preliminary performance results are showing around 4.4x better improvement for applications in IIS. What are the main blockers for switching from the core clr to the full clr?

**Comment by muratg** [comment]
@shirhatti Should we move this to RC1 to track the remaining work, or close this and file another one to track that?

**Comment by muratg** [comment]
Actually closing this bug. Tracking bugs are elsewhere.

**Comment by felipepessoto** [comment]
It does will be the default for 2.1?

**Comment by Tratcher** [comment]
No, this feature won't be available in 2.1.
