### ISSUE TITLE
Document install arguments

### ISSUE THREAD

**Issue by Styxxy** [aspnet/AspNetCoreModule#268]
Hi,

Are the command line arguments "OPT_INSTALL_LTS_REDIST" and "OPT_INSTALL_FTS_REDIST" still valid? What do they do?

Are there options to disable to "trying" to install the runtime and VC Redist?

**Comment by jkotalik** [comment]
@shirhatti

**Comment by shirhatti** [comment]
Oddly enough, this used to be part of the docs, but was removed.
I've created a new doc bug to track this https://github.com/aspnet/Docs/issues/5454
