### ISSUE TITLE
requestTimeout properties must be specified to in whole minutes

### ISSUE THREAD

**Issue by jkotalik** [aspnet/AspNetCoreModule#270]
We should consider updating the aspnetcore_schema to validate to the nearest second rather than nearest minute on the requestTimeout property. See https://github.com/aspnet/AspNetCoreModule/blob/dev/src/AspNetCore/aspnetcore_schema.xml#L22

**Comment by shirhatti** [comment]
This has been fixed https://github.com/aspnet/IISIntegration/pull/546
