### ISSUE TITLE
Add hook for middleware between IIS <-> AspNet Core application

### ISSUE THREAD

**Issue by ericgla** [aspnet/AspNetCoreModule#271]
We ran into an issue porting an existing web api application.  We expose a public API one one port, and an admin API on a separate port that is only accessible from behind the firewall.  After looking through the AspNetCoreModule code, I see that there is always a single binding between the module and the application.

I don't think it makes sense to have Kestrel listen on multiple ports based on the IIS site bindings, but I think there needs to be a way to determine which IIS site binding the request is using.  What would be ideal would be to have a middleware hook where I could inspect the IIS site binding, and inject a header so that the application knows the source of the incoming request.

This could be a nice alternative to adding a ton of configurable options for passing headers, etc...

**Comment by Tratcher** [comment]
The external port is already available in the Host header.

**Comment by ericgla** [comment]
Not sure how I missed that...  Thanks!
