### ISSUE TITLE
dotnet.exe restart

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCoreModule#278]
_From @ili on December 19, 2017 13:27_

Hello,

I've faced with strange situation - `dotnet.exe` hosted on IIS (Windows Server 2012 R2) is periodically shut down. 

While testing our application on high load we do see strange situations - periodically we do have long answer time from server (eg normal answer time is 300ms and long one is 15000 - 20000 ms).

While investigating this we've found out that at this times dotnet.exe is restarted (one process is stopped and another is started), no errors, no logs, nothing is saying about the reason.

Switching stdout logs on does not help much, while test we do see that new files like `stdout_9648_20171219125646.txt` are created, with mostly the same content:

```
Hosting environment: Production
Content root path: C:\inetpub\wwwroot
Now listening on: http://localhost:3214             --this line changes for each start
Application started. Press Ctrl+C to shut down. 
Application is shutting down...                     --this line appears on process stopped
```

Looking the documentation & IIS settings I can't find why process is stopped and why it can be stopped.

_Copied from original issue: aspnet/KestrelHttpServer#2227_

**Comment by nforysinski** [comment]
I am seeing some issues eerily similar to this - can anyone provide some insight?

Our issue is on a fairly high-request API hosted in an Azure App Service, randomly the app stops answering to requests and when looking at stdout logs, there is a random application shutdown and a new process is spun up. The problem is that this tends to cause threads to stack up and the process seems to not spin up without manually restarting the app, swapping the deployment slots, or changing the app service instance count.

**Comment by jkotalik** [comment]
We are still investigating this issue on our side too. The best help to us is to provide any logs of the behavior you are seeing, preferably a repro if you have it. If you have ETW and stdout logs you would like to share, you may email my email listed on my profile. Many people are hitting this issue (or a similar issue) and we want to identify a fix ASAP.

**Comment by nforysinski** [comment]
I've reviewed stdout logs several times and all we ever see is "Application Shutdown..." on all processes. However, we took dumps of all of the activity at that time, and I will email it over.

Additionally, we have been corresponding with Azure on this issue and they claim it MAY be part of a bug they are actively investigating as well.

**Comment by shirhatti** [comment]
We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Comment by ili** [comment]
After my resent research it looks like that server response time grows for some reason. From my side it looks like ANCM has some timeout and when got no (long) response from server it shuts process down and restarts it.

I'v gathered some statistics using MiniProfiler. The situation is: we'v started 40-50 instances of out client  emulator (it just executes simple scenario using HttpClient). The aim is to measure server response. 

Below is the table with some statistics (statistics is grouped by query duration rounded to 1000ms)

**ProcessId** - is dotnet.exe process Id
**MinDuration** - minimum query duration (in ms) for the group.
**AvgDuration** - average query duration (in ms) for the group.
**MaxDuration** - maximum query duration (in ms) for the group.
**QueryCount** - query count
**RoundedDuration** - 0.0 - queries between 0 and 1000ms, 1000 - queries between 1000 and 2000 ms and so on

As you can see most queries are done less then 1000ms but there are some strange queries having really awful duration (up to 20000ms). Also process restarts (you can see this in changing process id).

Total test duration is 6 minutes, query count - 8930, process was restarted 17 times (!!)

Process restart happens only with IIS, if I do start dotnet.exe it would never shut down. But the situation where response time would be dependent on number of clients would be the same (query duration goes from less then 50ms to 1000ms and more, in the same time I do not see any database query more then 100ms with SQL profiler, and mostly our API do simple database CRUD operations).

ProcessId|MinDuration|AvgDuration|MaxDuration|QueryCount|RoundedDuration
-|-|-|-|-|-
56|4.4|125.060622|850.1|739|0.0
56|1474.6|1632.200000|1969.7|4|1000.0
56|2218.4|2218.400000|2218.4|1|2000.0
56|3406.6|3406.600000|3406.6|1|3000.0
56|4186.4|4348.550000|4510.7|2|4000.0
612|12.6|333.306603|865.6|106|0.0
612|1056.4|1423.611111|1992.3|36|1000.0
612|2029.8|2254.325000|2393.1|8|2000.0
612|3697.2|3697.200000|3697.2|1|3000.0
612|4186.5|4186.500000|4186.5|1|4000.0
612|5344.7|5407.366666|5440.7|3|5000.0
612|6075.1|6170.550000|6266.0|2|6000.0
612|7749.3|7762.583333|7778.2|6|7000.0
612|8226.3|8430.376923|8873.4|13|8000.0
612|10281.8|10305.150000|10328.5|2|10000.0
1604|24.0|224.409859|978.6|71|0.0
1604|1112.7|1406.666666|1920.8|33|1000.0
1604|2005.3|2057.750000|2110.2|2|2000.0
1604|3548.1|3548.100000|3548.1|1|3000.0
1604|4250.9|4440.775000|4827.1|8|4000.0
1604|5609.1|5609.100000|5609.1|1|5000.0
1604|6801.0|6801.000000|6801.0|1|6000.0
1732|761.8|788.360000|844.9|5|0.0
1732|1059.0|1486.163333|1729.1|30|1000.0
1732|2063.4|2063.400000|2063.4|1|2000.0
1732|5332.8|5388.300000|5443.8|2|5000.0
1732|10280.0|10280.000000|10280.0|1|10000.0
1732|14367.3|14367.300000|14367.3|1|14000.0
2740|13.7|181.305797|898.3|207|0.0
2740|1033.3|1298.243902|1529.0|41|1000.0
2740|2143.5|2151.833333|2176.5|6|2000.0
2740|3832.6|3832.600000|3832.6|1|3000.0
2740|4237.4|4494.566666|4635.5|3|4000.0
2740|7852.9|7852.900000|7852.9|1|7000.0
2740|8158.5|8533.500000|8909.6|6|8000.0
2996|6.1|215.509445|994.1|974|0.0
2996|1008.0|1325.153191|1960.4|47|1000.0
2996|2053.1|2053.100000|2053.1|1|2000.0
2996|4234.7|4515.400000|4824.6|3|4000.0
2996|6148.7|6148.700000|6148.7|1|6000.0
2996|8219.1|8527.500000|8938.5|4|8000.0
3740|17.5|170.928300|999.0|1053|0.0
3740|1011.5|1319.207547|1992.3|53|1000.0
3740|2035.9|2319.883333|2899.0|6|2000.0
3740|3086.9|3157.666666|3223.4|3|3000.0
3740|4239.0|4415.966666|4757.3|3|4000.0
3740|5174.2|5250.900000|5327.6|2|5000.0
3740|6759.4|6759.400000|6759.4|1|6000.0
3740|7345.3|7796.900000|7967.2|4|7000.0
3740|8217.9|8608.860000|8999.1|10|8000.0
3740|9013.4|9013.400000|9013.4|1|9000.0
3828|13.3|248.763265|983.0|196|0.0
3828|1005.7|1223.014285|1864.1|21|1000.0
3828|2458.3|2645.600000|2832.9|2|2000.0
3828|3039.3|3281.840000|3775.4|5|3000.0
3888|17.3|220.512636|937.0|641|0.0
3888|1011.4|1369.561111|1973.8|54|1000.0
3888|2110.3|2207.800000|2305.3|2|2000.0
3888|3369.0|3369.000000|3369.0|1|3000.0
3888|4569.7|4645.700000|4721.7|2|4000.0
3888|8270.2|8425.291666|8772.6|12|8000.0
3888|9519.0|9519.000000|9519.0|1|9000.0
3948|16.4|170.680059|996.1|1008|0.0
3948|1005.5|1187.792000|1554.0|25|1000.0
3948|3187.5|3187.500000|3187.5|1|3000.0
3948|4438.2|4547.500000|4656.8|2|4000.0
4088|10.0|175.523574|923.4|263|0.0
4088|1004.3|1345.762857|1708.0|35|1000.0
4088|2136.0|2136.000000|2136.0|1|2000.0
4088|3474.2|3672.250000|3870.3|2|3000.0
4088|4109.5|4310.400000|4511.0|3|4000.0
4088|6741.3|6741.300000|6741.3|1|6000.0
4088|7786.8|7857.200000|7927.6|2|7000.0
4088|8172.1|8401.666666|8857.1|6|8000.0
4088|9317.8|9332.800000|9347.8|2|9000.0
4268|14.2|166.725471|997.1|1272|0.0
4268|1000.9|1328.453571|1999.0|56|1000.0
4268|2198.5|2286.800000|2520.0|4|2000.0
4268|3362.1|3362.100000|3362.1|1|3000.0
4268|4313.1|4518.000000|4722.9|2|4000.0
4268|5176.1|5228.050000|5280.0|2|5000.0
4268|6674.2|6698.125000|6713.9|4|6000.0
4268|8714.1|8714.100000|8714.1|1|8000.0
4268|9394.8|9579.800000|9683.9|3|9000.0
4268|10126.2|10133.766666|10141.5|3|10000.0
4356|1071.5|1457.166666|1997.4|21|1000.0
4356|3389.7|3634.220000|3969.4|5|3000.0
4356|4047.7|4047.700000|4047.7|1|4000.0
4356|5361.9|5570.900000|5779.9|2|5000.0
4356|6001.9|6013.750000|6025.6|2|6000.0
4356|10542.2|10542.200000|10542.2|1|10000.0
4356|13958.7|13958.700000|13958.7|1|13000.0
4356|14122.3|14496.466666|14686.6|3|14000.0
4356|16253.4|16253.400000|16253.4|1|16000.0
4356|17436.2|17436.200000|17436.2|1|17000.0
4680|867.0|892.500000|918.0|2|0.0
4680|1304.1|1529.980000|1879.7|30|1000.0
4680|2233.6|2354.100000|2474.6|2|2000.0
4680|3855.2|3878.400000|3901.6|2|3000.0
4680|4108.2|4108.200000|4108.2|1|4000.0
4680|8285.3|8285.300000|8285.3|1|8000.0
4680|11275.0|11275.000000|11275.0|1|11000.0
4680|12073.1|12073.100000|12073.1|1|12000.0
4704|4.9|197.462779|999.6|1029|0.0
4704|1009.0|1373.805172|1955.3|58|1000.0
4704|2429.0|2429.000000|2429.0|1|2000.0
4704|3431.9|3431.900000|3431.9|1|3000.0
4704|4159.1|4427.525000|4759.7|4|4000.0
4704|7997.6|7997.600000|7997.6|1|7000.0
4704|8243.3|8441.085714|8738.0|7|8000.0
4776|16.6|187.094397|911.3|357|0.0
4776|1068.9|1456.692105|1977.7|38|1000.0
4776|2100.9|2413.733333|2911.0|3|2000.0
4776|3674.8|3742.466666|3866.3|3|3000.0
4776|4297.0|4297.000000|4297.0|1|4000.0
4776|5077.1|5077.100000|5077.1|1|5000.0
4988|18.6|167.225663|838.0|113|0.0
4988|1050.0|1629.952631|1898.2|19|1000.0
4988|2003.9|2324.673333|2962.5|30|2000.0
4988|3009.6|3199.466666|3376.8|3|3000.0
4988|6190.4|6190.400000|6190.4|1|6000.0
4992|2365.7|2566.300000|2671.2|3|2000.0
4992|3006.9|3147.475000|3292.7|4|3000.0
4992|4715.5|4715.500000|4715.5|1|4000.0
4992|5349.4|5656.100000|5998.2|4|5000.0
4992|6307.3|6401.740000|6866.4|10|6000.0
4992|7246.8|7556.533333|7718.1|3|7000.0
4992|11336.9|11336.900000|11336.9|1|11000.0
4992|12549.5|12549.500000|12549.5|1|12000.0
4992|13969.4|13969.400000|13969.4|1|13000.0
4992|15097.9|15160.800000|15223.7|2|15000.0
4992|17561.5|17764.550000|17967.6|2|17000.0
4992|18168.3|18168.300000|18168.3|1|18000.0

**Comment by ili** [comment]
Here is very interesting situation, where PID 56 stopped, then started 4356, and it's queries are executed too long, and then 3828 process started. The interesting things are:

1. 4356 do have awful query duration without any visible reason
1. 4326 & 3828 run in parallel for some time (i'v marked this with bold process id)


ProcessId|Started|Name|DurationMilliseconds
-|-|-|-
56|2018-02-15 07:42:27.777|CashdeskServer/GetPrinterSettings|61.7
56|2018-02-15 07:42:27.780|CashdeskServer/GetPrinterSettings|59.0
56|2018-02-15 07:42:27.783|CashdeskServer/GetPrinterSettings|56.1
56|2018-02-15 07:42:27.787|CashdeskServer/GetPrinterSettings|54.1
56|2018-02-15 07:42:27.807|CashdeskServer/PutCheck|3406.6
56|2018-02-15 07:42:27.807|CashdeskServer/CalculatePrice|155.9
56|2018-02-15 07:42:27.817|CashdeskServer/GetPrinterSettings|40.5
56|2018-02-15 07:42:27.820|CashdeskServer/PutCheck|4186.4
56|2018-02-15 07:42:27.830|CashdeskServer/CalculatePrice|135.8
56|2018-02-15 07:42:27.870|CashdeskServer/CreateNewCard|163.4
56|2018-02-15 07:42:27.873|CashdeskServer/GetOrCreateRight|116.2
56|2018-02-15 07:42:27.877|CashdeskServer/CalculatePrice|127.9
56|2018-02-15 07:42:27.880|CashdeskServer/CalculatePrice|125.5
56|2018-02-15 07:42:27.883|CashdeskServer/CalculatePrice|123.9
56|2018-02-15 07:42:27.890|CashdeskServer/GetGoodTypeTrees|55.9
56|2018-02-15 07:42:27.907|CashdeskServer/CalculatePrice|100.5
56|2018-02-15 07:42:27.913|CashdeskServer/GetOrCreateRight|85.5
56|2018-02-15 07:42:27.920|CashdeskServer/PutCheck|4510.7
56|2018-02-15 07:42:27.977|CashdeskServer/GetOrCreateRight|295.8
56|2018-02-15 07:42:28.013|CashdeskServer/GetPrinterSettings|259.2
56|2018-02-15 07:42:28.020|CashdeskServer/GetPrinterSettings|254.6
56|2018-02-15 07:42:28.023|CashdeskServer/CalculatePrice|1969.7
56|2018-02-15 07:42:28.027|CashdeskServer/CalculatePrice|2218.4
4356|2018-02-15 07:42:31.017|CashdeskServer/CalculatePrice|17436.2
4356|2018-02-15 07:42:32.213|CashdeskServer/GetOrCreateRight|16253.4
4356|2018-02-15 07:42:33.533|CashdeskServer/GetReaderSettings|14122.3
4356|2018-02-15 07:42:33.773|CashdeskServer/CalculatePrice|14680.5
4356|2018-02-15 07:42:33.797|CashdeskServer/CalculatePrice|14686.6
4356|2018-02-15 07:42:33.807|CashdeskServer/GetReaderSettings|13958.7
4356|2018-02-15 07:42:37.943|CashdeskServer/CalculatePrice|10542.2
4356|2018-02-15 07:42:42.417|CashdeskServer/GetReaderSettings|5361.9
4356|2018-02-15 07:42:42.457|CashdeskServer/CalculatePrices|6025.6
4356|2018-02-15 07:42:42.490|CashdeskServer/CalculatePrice|6001.9
4356|2018-02-15 07:42:42.497|CashdeskServer/GetCards|5779.9
**3828**|2018-02-15 07:42:43.157|CashdeskServer/CalculatePrices|3775.4
**3828**|2018-02-15 07:42:43.330|CashdeskServer/CalculatePrices|3502.6
4356|2018-02-15 07:42:44.520|CashdeskServer/GetProcessings|3479.5
4356|2018-02-15 07:42:44.520|CashdeskServer/CalculatePrices|3969.4
4356|2018-02-15 07:42:44.523|CashdeskServer/GetProcessings|3389.7
4356|2018-02-15 07:42:44.523|CashdeskServer/GetProcessings|3454.6
4356|2018-02-15 07:42:44.587|CashdeskServer/CreateNewCard|4047.7
4356|2018-02-15 07:42:44.763|CashdeskServer/CalculatePrice|3877.9
4356|2018-02-15 07:42:46.000|CashdeskServer/GetPrinterSettings|1997.4
4356|2018-02-15 07:42:46.343|CashdeskServer/GetPrinterSettings|1656.8
4356|2018-02-15 07:42:46.567|CashdeskServer/GetPrinterSettings|1435.0
4356|2018-02-15 07:42:46.933|CashdeskServer/GetPrinterSettings|1071.5
4356|2018-02-15 07:42:46.953|CashdeskServer/CalculatePrice|1540.3
4356|2018-02-15 07:42:46.960|CashdeskServer/CalculatePrice|1541.4
4356|2018-02-15 07:42:46.967|CashdeskServer/GetOrCreateRight|1531.1
4356|2018-02-15 07:42:47.020|CashdeskServer/CalculatePrice|1486.4
4356|2018-02-15 07:42:47.027|CashdeskServer/GetOrCreateRight|1475.0
4356|2018-02-15 07:42:47.030|CashdeskServer/CalculatePrice|1482.3
4356|2018-02-15 07:42:47.037|CashdeskServer/GetOrCreateRight|1466.6
4356|2018-02-15 07:42:47.040|CashdeskServer/CalculatePrice|1483.2
4356|2018-02-15 07:42:47.090|CashdeskServer/CalculatePrice|1546.9
4356|2018-02-15 07:42:47.093|CashdeskServer/CalculatePrice|1550.5
4356|2018-02-15 07:42:47.100|CashdeskServer/GetOrCreateRight|1415.3
4356|2018-02-15 07:42:47.103|CashdeskServer/GetOrCreateRight|1414.5
4356|2018-02-15 07:42:47.110|CashdeskServer/GetCurrentUserInfo|1289.4
**3828**|2018-02-15 07:42:47.147|CashdeskServer/CalculatePrice|88.6
**3828**|2018-02-15 07:42:47.210|CashdeskServer/CalculatePrice|23.3
4356|2018-02-15 07:42:47.227|CashdeskServer/CalculatePrice|1419.8
4356|2018-02-15 07:42:47.237|CashdeskServer/CalculatePrice|1409.9
4356|2018-02-15 07:42:47.243|CashdeskServer/GetCurrentUserInfo|1213.9
4356|2018-02-15 07:42:47.470|CashdeskServer/CalculatePrices|1173.3
3828|2018-02-15 07:42:47.790|CashdeskServer/GetPrinterSettings|96.0
3828|2018-02-15 07:42:47.790|CashdeskServer/GetPrinterSettings|101.1
3828|2018-02-15 07:42:48.397|CashdeskServer/CalculatePrice|181.2
3828|2018-02-15 07:42:48.500|CashdeskServer/CalculatePrice|128.2
3828|2018-02-15 07:42:48.663|CashdeskServer/GetPrinterSettings|15.6
3828|2018-02-15 07:42:48.673|CashdeskServer/CalculatePrice|874.0
3828|2018-02-15 07:42:48.683|CashdeskServer/GetPrinterSettings|137.1
3828|2018-02-15 07:42:48.693|CashdeskServer/GetOrCreateRight|1148.3
3828|2018-02-15 07:42:48.697|CashdeskServer/GetOrCreateRight|1122.7
3828|2018-02-15 07:42:48.697|CashdeskServer/GetOrCreateRight|1137.8
3828|2018-02-15 07:42:48.697|CashdeskServer/CalculatePrice|1295.8
3828|2018-02-15 07:42:48.780|CashdeskServer/CalculatePrice|1213.2
3828|2018-02-15 07:42:48.820|CashdeskServer/GetPrinterSettings|109.8
3828|2018-02-15 07:42:48.823|CashdeskServer/CalculatePrice|1226.9
3828|2018-02-15 07:42:48.867|CashdeskServer/CalculatePrice|1209.0
3828|2018-02-15 07:42:48.877|CashdeskServer/GetOrCreateRight|1112.9
3828|2018-02-15 07:42:48.883|CashdeskServer/GetPrinterSettings|649.4
3828|2018-02-15 07:42:48.887|CashdeskServer/GetPrinterSettings|649.7
3828|2018-02-15 07:42:48.893|CashdeskServer/CalculatePrice|1185.0
3828|2018-02-15 07:42:48.900|CashdeskServer/CalculatePrice|1178.7
3828|2018-02-15 07:42:48.903|CashdeskServer/GetPrinterSettings|635.8
3828|2018-02-15 07:42:48.910|CashdeskServer/CalculatePrice|1178.6
3828|2018-02-15 07:42:48.923|CashdeskServer/CalculatePrice|1193.6
3828|2018-02-15 07:42:48.933|CashdeskServer/CreateNewCard|1181.9
3828|2018-02-15 07:42:49.107|CashdeskServer/CalculatePrice|1011.8
3828|2018-02-15 07:42:49.110|CashdeskServer/CalculatePrice|1030.6
3828|2018-02-15 07:42:49.110|CashdeskServer/CalculatePrice|1019.9
3828|2018-02-15 07:42:49.113|CashdeskServer/CalculatePrice|1029.9
3828|2018-02-15 07:42:49.120|CashdeskServer/CreateNewCard|1005.7
3828|2018-02-15 07:42:49.127|CashdeskServer/GetCurrentUserInfo|945.0
3828|2018-02-15 07:42:49.163|CashdeskServer/GetCurrentUserInfo|910.9
3828|2018-02-15 07:42:49.193|CashdeskServer/GetCards|786.8
3828|2018-02-15 07:42:49.350|CashdeskServer/GetPrinterSettings|481.7
3828|2018-02-15 07:42:49.463|CashdeskServer/CalculatePrice|679.3
3828|2018-02-15 07:42:49.603|CashdeskServer/CalculatePrice|546.1
3828|2018-02-15 07:42:49.610|CashdeskServer/CreateNewCard|531.8
3828|2018-02-15 07:42:49.660|CashdeskServer/CalculatePrice|492.9
3828|2018-02-15 07:42:49.667|CashdeskServer/CalculatePrice|487.8
3828|2018-02-15 07:42:49.680|CashdeskServer/CalculatePrice|474.5
3828|2018-02-15 07:42:49.690|CashdeskServer/CalculatePrice|463.5
3828|2018-02-15 07:42:49.697|CashdeskServer/CreateNewCard|454.6
3828|2018-02-15 07:42:49.700|CashdeskServer/CalculatePrice|453.7
3828|2018-02-15 07:42:49.707|CashdeskServer/GetCards|369.4
3828|2018-02-15 07:42:49.717|CashdeskServer/CalculatePrice|438.0
3828|2018-02-15 07:42:50.007|CashdeskServer/GetCurrentUserInfo|150.5
3828|2018-02-15 07:42:50.080|CashdeskServer/GetCurrentUserInfo|89.3
3828|2018-02-15 07:42:50.170|CashdeskServer/CalculatePrice|173.5
3828|2018-02-15 07:42:50.180|CashdeskServer/CalculatePrice|173.5
3828|2018-02-15 07:42:50.187|CashdeskServer/GetCurrentUserInfo|137.4
3828|2018-02-15 07:42:50.190|CashdeskServer/CalculatePrice|225.7
3828|2018-02-15 07:42:50.220|CashdeskServer/GetProcessings|118.0
3828|2018-02-15 07:42:50.263|CashdeskServer/CalculatePrice|195.3
3828|2018-02-15 07:42:50.270|CashdeskServer/CalculatePrice|188.8
3828|2018-02-15 07:42:50.280|CashdeskServer/CreateNewCard|190.4
3828|2018-02-15 07:42:50.283|CashdeskServer/CreateNewCard|190.7
3828|2018-02-15 07:42:50.293|CashdeskServer/CreateNewCard|187.8
3828|2018-02-15 07:42:50.313|CashdeskServer/GetCards|66.2
3828|2018-02-15 07:42:50.317|CashdeskServer/GetPrinterSettings|72.6
3828|2018-02-15 07:42:50.393|CashdeskServer/GetPrinterSettings|41.2
3828|2018-02-15 07:42:50.397|CashdeskServer/GetPrinterSettings|37.0
3828|2018-02-15 07:42:50.403|CashdeskServer/CalculatePrice|127.9
3828|2018-02-15 07:42:50.407|CashdeskServer/GetPrinterSettings|34.3
3828|2018-02-15 07:42:50.410|CashdeskServer/CalculatePrice|121.2

**Comment by ili** [comment]
Here are raw data in txt & xlsx
[raw_test_data.txt](https://github.com/aspnet/AspNetCoreModule/files/1735708/raw_test_data.txt)
[raw_test_data.xlsx](https://github.com/aspnet/AspNetCoreModule/files/1735709/raw_test_data.xlsx)

**Comment by ili** [comment]
Environment:
* .Net Core Runtime 2.0.5
* MS .Net Core 2.0.5 Windows Server Hosting
* Windows Server 2012 R2
* MS Sql Server Express 12.0.2000.8

Server is run under HyperV, HyperV is hosted in WS 2012 R2

Virtual machine do have:
* Intel Xeon E5620 @ 2.40 GHz (one core)
* 4GB RAM
* Regular HDD (no SSD)

**Comment by dombarnes** [comment]
@shirhatti I can see some new information has been provided on this issue in February. Is there any chance this will be looked at again? It seems like this is a fairly common issue with high traffic sites.
