### ISSUE TITLE
ANCM should set `X-Forwarder-Host header` 

### ISSUE THREAD

**Issue by muratg** [aspnet/AspNetCoreModule#280]
See the initial discussion at https://github.com/aspnet/AspNetCoreModule/issues/89

**Comment by Tratcher** [comment]
Not preserving the host header would be a severe breaking change. What problem is it solving?

**Comment by Tratcher** [comment]
Is the concern here that IIS forwards HTTP 1.0 request as 1.1 requests but does not add the required host header? In those scenarios ANCM should add a Host header with no value.
https://tools.ietf.org/html/rfc7230#section-5.4
> If the authority component is missing or undefined for the target URI, then a client MUST send a Host header field with an empty field-value.

We have another issue for dealing with empty hosts in the stack overall: https://github.com/aspnet/Hosting/issues/1289

**Comment by shirhatti** [comment]
@Tratcher Does setting `X-Forwarder-Host` imply that the `Host` header has also been changed? I'm confused why this can't just be an additive change

**Comment by Tratcher** [comment]
Let's take this offline, these issues are quite confused.

**Comment by Tratcher** [comment]
Closing this based on offline discussion. We could never change the host behavior without breaking back compat, and we wouldn't gain much by doing it anyways.
