### ISSUE TITLE
Allow sync/xcopy deploy

### ISSUE THREAD

**Issue by PaulHuizer** [aspnet/AspNetCoreModule#282]
I tested ASP.Net Core 2.0 on IIS. All my apps sofar written in WebApi2 are updated by simply copying (xcopy/sync/ftp) new version in the site folder. IIS takes care of loading new versions without further ado in the deployment scripts. Using ASP.NET Core 2.0 I could not get this to work, since the process is alive and keeps underlying files open/locked. I hope this deployment method can be achieved somehow.

**Comment by shirhatti** [comment]
There have been a few issues about this in the past. Given that there are no AppDomains in .NET Core, it seems contrived to re-introduce shadow copying in ANCM.
While not quite the same as xcopy deploying, I'd recommend using the [appOffline](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module#appofflinehtm) feature in ANCM instead.

1. Drop an appOffline.htm file and wait for your app to gracefully shutdown
2. Replace your app contents.
3. Remove appOffline
