### ISSUE TITLE
ANCM should suspend request timeouts when the debugger is attached

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/AspNetCoreModule#284]
Requests shouldn't time out during debugging.

**Comment by pan-wang** [comment]
is this for inprocess? I believe we already disabled timeout for out-of-process

**Comment by jkotalik** [comment]
Yeah most likely. It look like we don't set the timeout for requests at all for in-proc. @pan-wang for out of proc, I think you set the timeouts for requests on winhttp. What can we do for in-proc?

**Comment by pan-wang** [comment]
In the past, asp.net has some settings, e.g., https://msdn.microsoft.com/en-us/library/e1f13641(v=vs.85).aspx. IIS itself does not have a setting on request timeout.

**Comment by shirhatti** [comment]
For in-proc, we don't have a request timeout.
For out-of-proc, we unfortunately don't know that's there a debugger attached to the backend process.

Closing this issue as it's not actionable from ANCM.

**Comment by jkotalik** [comment]
@shirhatti this is going to be fixed by @BillHiebert  setting the request timeout to infinite when it is launched through IIS express.
