### ISSUE TITLE
Logs are not created if the log folder does not exist

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCoreModule#30]
_From @Tratcher on May 27, 2016 21:48_

The templates set `stdoutLogFile=".\logs\stdout"` by default, but do not include a logs directory in the project. ANCM will not create log files unless the logs directory already exists. ANCM should create the directory.

_Copied from original issue: aspnet/IISIntegration#196_

**Comment by Tratcher** [comment]
_From @GuardRex on May 29, 2016 18:3_

Great idea in the specified case, but it's also related to a side-issue with `dotnet cli` in that if we create a `Logs` folder in the app and include it for publishing in `publishOptions > include`, it will not appear in published output without a dummy file in it. https://github.com/dotnet/cli/issues/1396 cc/ @piotrpMSFT @blackdwarf

The possible problem here is that devs may want to put the logs anywhere [possibly putting logs from all apps in one folder and naming the log files to match their app (e.g., `stdoutLogFile="c:\logs\this_app_name"`)]; so, are you saying that ANCM could create the path anywhere? ... not just to `.\logs` ... but the full path of `.\funky_folder\nutty_folder\goofy_folder` or `f:\put_the_log_here` or `\\server\share\path` or whatever path the dev sticks in there?

Notwithstanding https://github.com/dotnet/cli/issues/1396, this doesn't feel like a "bug" as much as it is an "ID-10T Error." :smile:

**Comment by Tratcher** [comment]
~~Also fix the path logic so the `.\` isn't required, and so that even any empty path works.
https://github.com/aspnet/IISIntegration/issues/119#issuecomment-226005524~~
Moved this suggestion to #43

**Comment by Tratcher** [comment]
@shirhatti *ping* This is my biggest pet peve with ANCM. I turned logging on, specified where to put them, but nothing happens.
https://github.com/aspnet/IISIntegration/issues/406#issuecomment-324940297

**Comment by Tratcher** [comment]
https://github.com/aspnet/AspNetCoreModule/issues/142#issuecomment-326327247

**Comment by jkotalik** [comment]
We would need to add calls to CreateDirectory here: https://github.com/aspnet/AspNetCoreModule/blob/dev/src/AspNetCore/Src/serverprocess.cxx#L1198-L1227

**Comment by dasMulli** [comment]
This issue is requiring more and more complex workarounds for users in different deployment scenarios and the needed documentation seems overly complex for a simple deployment (@guardrex ?).

Right now, https://github.com/aspnet/websdk/issues/152#issuecomment-348569871 suggests the following target to be created in order to work for all publishing methods:

> ```xml
> <Target Name="CreateLogsFolder" AfterTargets="Publish">
>   <MakeDir Directories="$(PublishDir)Logs" Condition="!Exists('$(PublishDir)Logs')" />
>   <WriteLinesToFile File="$(PublishDir)Logs\.log" Lines="Generated file" Overwrite="True" Condition="!Exists('$(PublishDir)Logs\.log')" />
> </Target>
> ```

**Comment by guardrex** [comment]
My intention is to update the workaround in the *Directory Structure* topic. Otherwise, our advice would be 'you just need to create the folder' and leave the reader hanging on how to automate it. But yeah ... I've been very interested in this one for a long time (see: https://github.com/dotnet/cli/issues/1396 ... February of 2016).

**Comment by pan-wang** [comment]
Ack. It's in the list of improvements and will be ready soon. Note that the folder creation may still fail if worker process does not have the write permission to the target folder.

**Comment by guardrex** [comment]
> Note that the folder creation may still fail if worker process does not have the write permission to the target folder.

@pan-wang ~Seems like that's worth mentioning in the doc update, correct?~ I added it.

**Comment by muratg** [comment]
Thanks @guardrex for the doc update!  https://github.com/aspnet/websdk/issues/273 would also mitigate this in the publish case (causing the folder to be created at the time of publish.)  

Closing this. @shirhatti reminder:  please follow up with @vijayrkn on the status of the websdk bug.
