### ISSUE TITLE
ANCM Build Pains

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCoreModule#35]
@shirhatti Hey ... Had a problem with the build steps for ANCM as shown in the repo instructions (this is also the result if just performing a `build.cmd /target:clean`) ...
```
C:\Users\xxxxx\Documents\GitHub\AspNetCoreModule>build.cmd /property:platform=x64 
    /property:configuration=release
Building C:\Users\xxxxx\Documents\GitHub\AspNetCoreModule
dotnet-install: .NET SDK version 1.0.0-preview2-1-003171 is already installed.
Adding C:\Users\xxxxx\AppData\Local\Microsoft\dotnet\ to PATH
Using makefile: makefile.shade
fail: The given key was not present in the dictionary.
fail: Stack trace:
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.SakeEngine.Execute(Options options)
   at Sake.Engine.SakeEngine.Execute(String[] args)
   at Sake.Program.Main(String[] args)
```
Besides that exception, can't this build process by bypassed to just build the module for local use? Shouldn't I be able to just build the solution? It does build in VS, and I can get an `aspnetcore.dll` out of it.

However, then I try to use the module I've produced with local IIS, I end up with a 500.21 "bad module" error ...

![capture](https://cloud.githubusercontent.com/assets/1622880/20028059/0fe45d56-a2f5-11e6-894c-744cd64e7f97.PNG)

I haven't tried to determine the cause of the failure. I was just wondering if you recognized this result? If not, I'll dig deeper on it.

Last ?: The installed -3171 SDK went into `C:\Users\xxxxx\AppData\Local\Microsoft\dotnet\`, but I was expecting it to install it at `c:\Program Files\dotnet` with the rest of them on my dev box. It looks like the PS script is looking for a `DOTNET_INSTALL_DIR` env var to tell it where currently installed SDK's are located ...
```powershell
function Get-User-Share-Path() {
    Say-Invocation $MyInvocation

    $InstallRoot = $env:DOTNET_INSTALL_DIR
    if (!$InstallRoot) {
        $InstallRoot = "$env:LocalAppData\Microsoft\dotnet"
    }
    return $InstallRoot
}
```
... but that's not (apparently) set by normal dotnet CLI installs that I've been doing here, because I don't have that env var set on my system.

**Comment by shirhatti** [comment]
Can you try just `.\build.cmd` with no arguments?

**Comment by guardrex** [comment]
@shirhatti Yes, that worked, and the resultant module works in IIS. Thank you! (again) :smile:

I guess what happened was that when I executed the script with clean and it resulted in an exception, I stopped right there to ask you about it. I definitely should have moved down and tried to run without the argument.

It failed for clean ...

```
# Clean
.\build.cmd /target:clean
```

so I guess that was normal? ... or expected? 

Regarding the `DOTNET_INSTALL_DIR`env var, is it common practice there to set `DOTNET_INSTALL_DIR` to the path (in my case `c:\Program Files\dotnet`) where the rest of the CLI's are installed on the dev box, or are you not setting it to allow the script to install the CLI at `C:\Users\xxxxx\AppData\Local\Microsoft\dotnet\`?

**Comment by Tratcher** [comment]
We set DOTNET_INSTALL_DIR on CI machines where we've deployed the latest build of dotnet to a specific dir.

**Comment by guardrex** [comment]
@Tratcher I see. Thanks. I think I'm good now. I'll close, b/c I think the clean exception was/is either known or a local (ID-10T) error.

**Comment by shirhatti** [comment]
Ahh. It's my bad the build instructions are a little stale. They reference an earlier version of of the `build.cmd` that directly invoked MSBuild. We since then updated to use [`KoreBuild`](https://github.com/aspnet/KoreBuild) like most of our other repos.
I'll update the build instructions shortly. Thanks for catching that.
