### ISSUE TITLE
Fix build instructions in README.md

### ISSUE THREAD

**Issue by shirhatti** [aspnet/AspNetCoreModule#36]
Related: #35

**Comment by guardrex** [comment]
Also, the instruction for installing without the runtime is ...
```
DotNetCore.1.1.0.Preview1-WindowsHosting.exe OPT_INSTALL_LTS_REDIST=0 OPT_INSTALL_FTS_REDIST=0
```
but now past preview and for the current download, it should be ...

~DotNetCore.1.1.0-WindowsHosting.exe OPT_INSTALL_LTS_REDIST=0 OPT_INSTALL_FTS_REDIST=0~

**Comment by natemcmaster** [comment]
Related #73

**Comment by guardrex** [comment]
... and the current version for that instruction is actually ...
```
DotNetCore.1.0.3_1.1.0-WindowsHosting.exe OPT_INSTALL_LTS_REDIST=0 OPT_INSTALL_FTS_REDIST=0
```

**Comment by shirhatti** [comment]
Closing in favor of #168
