### ISSUE TITLE
Win7 / 2008R2 support

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCoreModule#40]
The public sources do not support building for Win7  / 2008R2, only the official releases support it. This prevents us from testing changes on Win7 before release.

**Comment by jkotalik** [comment]
This should pass now. Do we have any build agents on Win7 right now? I can try manually on a win7 machine but that isn't ideal.

**Comment by Tratcher** [comment]
yes we have an active Win7 CI agent. See https://github.com/aspnet/Hosting/pull/1235.

**Comment by jkotalik** [comment]
Finished by https://github.com/aspnet/Hosting/pull/1235
