### ISSUE TITLE
Move the ANCM nupkg from its own feed to all of the other feeds

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCoreModule#41]
@davidfowl has asked for us to remove the https://dotnet.myget.org/F/aspnetcoremodule/api/v3/index.json feed and push ANCM directly to all of the other feeds instead.

@Eilon @pranavkm ?

**Comment by pranavkm** [comment]
> to all of the other feeds instead.

What does that mean?

**Comment by Tratcher** [comment]
When ANCM builds he wants to publish it to every feed. ci-dev, ci-release, etc..

**Comment by pranavkm** [comment]
We have 5 regular feeds + one per LTS release. Seems like a lot of hassle to keep track of these here. Is the issue here that we have to list an additional feed in your repo?

**Comment by pranavkm** [comment]
Might be easier to just mirror this like other partner packages. I'm assuming the intent here is to always grab the latest and archive the ones we use as part of a shipping release to aspnetcore-master (similar to how we do .Sources packages)

**Comment by davidfowl** [comment]
YES, treat it like a partner package

**Comment by Tratcher** [comment]
Note partner packages do have their own feeds, we just don't reference them directly in our repos.

**Comment by davidfowl** [comment]
> Note partner packages do have their own feeds, we just don't reference them directly in our repos.

That's the entire point of this bug 😄. So if you want to, keep the ANCM feed then mirror it.

**Comment by pranavkm** [comment]
The package is on the dev feed now: https://dotnet.myget.org/feed/aspnetcore-ci-dev/package/nuget/Microsoft.AspNetCore.AspNetCoreModule.
