### ISSUE TITLE
Feature question: Expanded error logging from the ANCM

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCoreModule#47]
I was suggesting in https://github.com/aspnet/AzureIntegration/issues/4 better Azure reporting for process start failures. As it stands, an app doesn't require console logging to report a few reasons for process start failures from ANCM via the `stdout` log (when enabled).

There is an underlying problem with my suggestion, so the issue I opened was just about DOA. Note @pan-wang in [1](https://github.com/aspnet/IISIntegration/issues/228#issuecomment-247726905) and @shirhatti in [2]( https://github.com/aspnet/AspNetCoreModule/issues/32#issuecomment-261351019) comments ...

>ANCM calls CreateProcess() to launch Krestrel. It logs the error code from GetLastError() in case of CreateProcess failed. In this case, GetLastError() returns 0x80070002 and no way for ANCM to figure out the real root cause.

> Unfortunately there's no way for ANCM to figure out why CreateProcess() failed. I think adding it to the troubleshooting section in the doc was the best when we can do.

My gut says, "The keepers of `CreateProcess()` could do a bit more than a generic error code." Notwithstanding complex technical issues and turf wars in getting more than `GetLastError()` has to offer when Kestrel is started, I just wanted to ask about what the ANCM itself might be able to do to help devs out.

Check out at these error conditions under `0x80070002`, `-2147024894`, `0x800705b4` ...

* Bad processPath
* dotnet.exe not on the PATH
* dotnet.exe not accessible for AppPool user identity (permissions)
* Shared runtime not on the server
* IIS Integration middleware not implemented
* Directory structure is wrong (e.g., missing files)

Can the ANCM be enhanced so that if `stdout` logging is enabled it will figure out in each of these cases what went wrong and drop a specific exception in the log?

If that's something you'd be interested in doing, I further suggest that the level of troubleshooting advice that we have in the Pub IIS doc would be very helpful to show right after the exception.

**Comment by Tratcher** [comment]
Some follow up diagnostics for common errors would be nice. That said, I wouldn't expect the output to go to the log file, it would go to the event logs with all of ANCM's other data.
