### ISSUE TITLE
HTTP Error 502.3 - Bad Gateway when timeout.

### ISSUE THREAD

**Issue by shirhatti** [aspnet/AspNetCoreModule#48]
_From @Bartmax on December 4, 2016 21:0_

Executing this code:
```
public async Task<IActionResult> Test()
{
    await Task.Delay(TimeSpan.FromMinutes(5)); // simulate some time consuming process.
    System.IO.File.WriteAllText("testfile.txt", "some content");
    return Content("done");
}
```
returns a 502.3 Bad Gateway error.
![image](https://cloud.githubusercontent.com/assets/3386797/20869163/33c32e6a-ba4b-11e6-9639-c73891ead2e2.png)

The file **DOES GET GENERATED/CREATED**

How can I change the timeout (or whatever settings) that can help me avoid this ?
Can the error be more friendlier ? 

_Copied from original issue: aspnet/Home#1857_

**Comment by shirhatti** [comment]
_From @Tratcher on December 4, 2016 22:35_

See requestTimeout in https://docs.microsoft.com/en-us/aspnet/core/hosting/aspnet-core-module

**Comment by shirhatti** [comment]
_From @Bartmax on December 5, 2016 1:30_

@Tratcher thanks, it would be great if the error was shown as "timeout" instead of Bad Gateway error talking about something called CGI that has nothing to do with the real issue.

**Comment by shirhatti** [comment]
_From @davidfowl on December 5, 2016 1:38_

@Bartmax welcome to IIS error pages 😄

**Comment by shirhatti** [comment]
_From @Tratcher on December 5, 2016 4:44_

@pan-wang @shirhatti some user feedback

**Comment by shirhatti** [comment]
Looks like we should be returning a 504 instead of a 502

**Comment by salihigde** [comment]
setting requestTimeout attribute in aspnetCore tag works properly in my localhost when working with IIS Express but it doesn't work when i try it on production (when my application is hosted in IIS). You may see my web.config tag below. It is set to 10 minutes but keeps giving me "Uncaught 504 - Connection Timed Out Response with status: 504 Connection Timed Out for URL" error after 1 minute.

    <aspNetCore processPath=".\abc.exe" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false" requestTimeout="00:10:00" />

**Comment by MicheleRezk** [comment]
Hi @salihigde ,

I'm facing the same issue, requestTimeOut attribute working in localhost IIS Express and not working in Production hosted in IIS, Did you reach to a solution for this issue? (Thanks)

**Comment by pan-wang** [comment]
asp.net core module request time is just used to control the timeout value between IIS worker process and backend process. You also need to config IIS connection time out which is used between client/browser and IIS worker process. Such as those IIS settings  https://docs.microsoft.com/en-us/iis/configuration/system.applicationhost/sites/sitedefaults/limits

**Comment by gezzahead** [comment]
We are facing the same issue as @salihigde and @MicheleRezk. We also found that running the long-running call on the production server itself works (ie. no timeout), but from anywhere else (ie. not on the server) it times out.  We updated the connectionTimeout Website Default (as suggested by @pan-wang), and also the specific connection time-out on the site (under the 'Limits...' section) but none of this helps.  Interestingly, when we set this last site-specific time-out to only 10 seconds it still only times out after 2 minutes, so we're not sure whether this setting is really affecting anything (or perhaps we misunderstand what it affects).
Any help/ideas would be much appreciated!

**Comment by salihigde** [comment]
@gezzahead himm 2 minutes made me think about the timeout on Kestrel because its default value is 2 minutes. In the second link you will see _keepAliveTimeout parameter and its value is set to 2 minutes for default. maybe setting that parameter to bigger value might solve your problem?

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?tabs=aspnetcore2x#when-to-use-kestrel-with-a-reverse-proxy

https://github.com/aspnet/KestrelHttpServer/blob/rel/2.0.0/src/Microsoft.AspNetCore.Server.Kestrel.Core/KestrelServerLimits.cs

**Comment by gezzahead** [comment]
Thanks a lot @salihigde, an initial experiment seems to suggest this fixes it!! We added the options to UseKestrel
`                var host = new WebHostBuilder().UseKestrel(o =>
                    {
                        o.Limits.KeepAliveTimeout = TimeSpan.FromMinutes(30);
                    }
                )`
Will test further, but this looks like the answer we've spent all day trying to solve :)

**Comment by salihigde** [comment]
@gezzahead your welcome :)

**Comment by shirhatti** [comment]
Closing this bug due to inactivity.

**Comment by davidfowl** [comment]
@shirhatti we just need to get rid of the default timeout 😄

**Comment by shirhatti** [comment]
We can't eliminate it entirely. We still need to specify a receive timeout for WinHTTP https://github.com/aspnet/IISIntegration/blob/b70191fb82bef2346a931a3c645f5cb8132c8a79/src/RequestHandler/outofprocess/forwardinghandler.cpp#L1086

The WinHTTP receive timeout default is 30 seconds. Now surely we don't want that 😄

**Comment by brgrz** [comment]
This is still happening pretty much every time something timeouts, even locally on IIS Express with the 502.3 Bad Gateway response.

**Comment by jkotalik** [comment]
@brgrz what behavior do you expect instead? To return a 504? ANCM will timeout requests after 2 minutes by default and return a 502.3.

**Comment by brgrz** [comment]
@jkotalik 504 makes much more sense, since I just spent hours troubleshooting middleware and routing due to misleading Bad Gateway (it implies something's wrong with infrastructure or configuration instead of timeout error).

**Comment by MrSkiv** [comment]
I have similar problem. In production we have 10-20 requests per second. All are with pretty big post message in body: from 10kB to 500kB. (These messages is saved to disk without almost any processing) Pretty often we get timeout, also worth mention that client, which posts messages time outs after 5 seconds. In most cases its not a problem, but from time to time there is too much requests timeouts and then ANY NEW requests doesn't accepted: problem from network side is away, but server doesn't accept any new messages: 502.3 error. Server receives new requests, but it can't handle it, arrives new and new messages and they times out also. Everything stops for minutes and n0 minutes. (.Net core 4.1.4, IIS 8.5, Kestrel)

**Comment by eric-b** [comment]
I encountered the same issue with timeout leading to an http 502.3 error.
I have not yet found the cause of the issue but I found [this blog post (Logging for ASP.net CORE applications when you receive 502.3 and 500 status codes)](https://blogs.msdn.microsoft.com/friis/2018/02/07/logging-for-asp-net-core-applications-when-you-receive-502-3-and-500-status-codes/) enlightening. It explains why a 502.3 error on timeout in ASP.NET Core app out-of-process with IIS as a reverse proxy.

**Comment by spottedmahn** [comment]
Encountered this today, feel the same way as @brgrz, 502.3 is miss leading.

Is there another GitHub issue that I/we can track for switching from 502.3 to 504?  Is this change going to happen? Thanks! @jkotalik

**Comment by hugepanda** [comment]
I also encountered the same issue when a call to controller is time-consuming. I tried @gezzahead method by adding the time limit in Kestrel, but it still shows the same 502.3 error. I also tried to increase the time limit in IIS to 180 seconds, no result. Can anyone help please?
