### ISSUE TITLE
Consider passing request/headers with IPC 

### ISSUE THREAD

**Issue by benaadams** [aspnet/AspNetCoreModule#49]
Consider passing the pre-parsed headers and request data to Kestrel etc with [ReadProcessMemory](https://msdn.microsoft.com/en-us/library/windows/desktop/ms680553(v=vs.85).aspx) as a custom headers collection; or CreateFileMapping on the pagefile

**Comment by shirhatti** [comment]
@benaadams Can you elaborate? Not sure I understand what you have in mind.

**Comment by benaadams** [comment]
The headers are pre-parsed by HTTP.sys. Rather than encoding them back into strings and sending via TCP and reparsing them in the Asp.Net server a reference could be passed to them and read with ReadProcessMemory or a shared MemoryMappedFile, either via an alternate `IHeaderDictionary` concrete type; or pushed directly into `FrameRequestHeaders` via the explicit types e.g. `HeaderTransferEncoding`

**Comment by davidfowl** [comment]
> The headers are pre-parsed by HTTP.sys.

I'm not sure that's viable. Adding http.sys specific code to Kestrel seems like a non starter.  How would you even get access to the address?

**Comment by benaadams** [comment]
The HTTP.sys specific stuff would be in AspNetCoreModule as now?

The [HTTP_REQUEST](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364612(v=vs.85).aspx) and [HTTP_REQUEST_HEADERS](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364548(v=vs.85).aspx) from [GetRawHttpRequest](https://msdn.microsoft.com/en-us/library/ms694280(v=vs.90).aspx) could be written to a MemoryMapped file (I've gone off Read/Write Process; is mostly for debugging) - that could maybe be interperated by IISIntegration middleware and bypass the TCP/networking stack and re-parsing? 

So Kestrel would need hooks to short circuiting the frame start? But not need HTTP.sys specific stuff

/cc @Tratcher

**Comment by Tratcher** [comment]
Except Kestrel needs access to request headers to know what to do with the body, you couldn't skip straight to the IISMiddleware.

**Comment by benaadams** [comment]
I mean couldn't the IISMiddleware (or something similar - in ConfigureServices) provide the handle for the bypass? (So it wasn't included in Kestrel directly)

Not sure if you could do something similar with an ngnix module (as they have to be compiled in) - but a common bypass type system.

**Comment by muratg** [comment]
This is not needed as much with the in-proc model. Also stale bug :D
