### ISSUE TITLE
app_offline.htm is case sensitive

### ISSUE THREAD

**Issue by shirhatti** [aspnet/AspNetCoreModule#50]
Reported here https://github.com/aspnet/Home/issues/694#issuecomment-265233972

**Comment by asadsahi** [comment]
What is the workaround for this right now, manually stopping website before deploy?

**Comment by mrahhal** [comment]
@asadsahi you can manually call webdeploy to add the file with the correct case before deployment and then delete the file after that.

**Comment by asadsahi** [comment]
how to do that, currently I am only adding AppOffline rule in webdeploy command (deploying website using command line)

Like this:

-enableRule:AppOffline

**Comment by mrahhal** [comment]
In its raw form, you can do this (using powershell):

```ps1
$app_offline = "path/to/app_offline-template.htm"

# Deploy app_offline-template.htm as app_offline.htm (you should have
& msdeploy.exe -verb:sync -source:contentPath=$app_offline -dest:contentPath=$iisApp/app_offline.htm,ComputerName=$computerName,UserName=$username,Password=$password,IncludeAcls="False",AuthType="Basic" -allowUntrusted

# Deploy the website (without enabling the AppOffline rule)
& msdeploy.exe ...

# Delete app_offline.htm
& msdeploy.exe -verb:delete -dest:contentPath=$iisApp/app_offline.htm,ComputerName=$computerName,UserName=$username,Password=$password,IncludeAcls="False",AuthType="Basic" -allowUntrusted
```

Of course, you'll also have to define the other variables ($userName, $password, ...)

Now, how this fits in depends on how you deploy your app, whether you're using your own script or using Visual Studio's publishing methods. I use my own script as VS's for aspnetcore is lacking.

**Comment by asadsahi** [comment]
@mrahhal Interesting stuff. I am kind off new to powershell. But I am using VS code for asp.net core development. So what I am trying is to deploy using some automated script which I can run from command prompt or powershell as one shot.

So there are three steps involved:

# Builds client assets
1) **npm run build:prod** 

# publishes .net core app
2) **dotnet publish -c release**

# deploy

3) `"C:\\Program Files\\IIS\\Microsoft Web Deploy V3\\msdeploy.exe" -verb:sync -enableRule:AppOffline -source:contentPath="%USERPROFILE%\mywebsite\bin\release\netcoreapp1.1\publish" -dest:contentPath="mywebsite",ComputerName="https://mywebsite.scm.azurewebsites.net/msdeploy.axd",UserName='$myusername',Password='mypassword',AuthType='Basic'
`

Have you got any idea how to combine these three steps, so that they run in order?

**Comment by mrahhal** [comment]
I do something similar, but you'll have to take control of your whole build step. Let's say you have a script called `deploy.ps1` (ignored by source control). So that you'll only need to run `./deploy.ps1`, without depending on anything else.

Something like this would work:

```ps1
$webdeploy = "C:\Program Files (x86)\IIS\Microsoft Web Deploy V3\msdeploy.exe"
$location = Get-Location | Select-Object $_.Path
$packOutput = Join-Path $location "bin\Release\netcoreapp1.1\publish"
$app_offline = Join-Path $location "app_offline-template.htm"

$iisApp = "..."
$computerName = "..."
$username = "..."
$password = "..."

function DeletePublishFolder()
{
	if (Test-Path $packOutput)
	{
		WriteInfo "Removing publish folder..."
		Remove-Item -Force -Recurse $packOutput
	}
}

function RunNpm()
{
	npm run build:prod
	if ($LASTEXITCODE -ne 0)
	{
		WriteFailed "Failed with code $LASTEXITCODE. Exiting..."
		Exit
	}
}

function Publish()
{
	dotnet publish -c Release
	WriteSuccess "Published!"
}

function Deploy()
{
	& $webdeploy -verb:sync -source:contentPath=$app_offline -dest:contentPath=$iisApp/app_offline.htm,ComputerName=$computerName,UserName=$username,Password=$password,IncludeAcls="False",AuthType="Basic" -retryAttempts:5 -allowUntrusted

	& $webdeploy -verb:sync -source:IisApp=$packOutput -dest:IisApp=$iisApp,ComputerName=$computerName,UserName=$username,Password=$password,IncludeAcls="False",AuthType="Basic" -enableRule:DoNotDeleteRule -disablerule:BackupRule -enableLink:contentLibExtension -retryAttempts:5 -allowUntrusted

	& $webdeploy -verb:delete -dest:contentPath=$iisApp/app_offline.htm,ComputerName=$computerName,UserName=$username,Password=$password,IncludeAcls="False",AuthType="Basic" -retryAttempts:5 -allowUntrusted

	if ($LASTEXITCODE -ne 0)
	{
		WriteFailed "Failed with code $LASTEXITCODE. Exiting..."
		Exit
	}

	WriteSuccess "Deployment succeeded!"
}

function WriteFailed($text)
{
	Write-Host $text -ForegroundColor Red
}

function WriteInfo($text)
{
	Write-Host $text -ForegroundColor Cyan
}

function WriteSuccess($text)
{
	Write-Host $text -ForegroundColor Green
}

# -----------

DeletePublishFolder
RunNpm
Publish
Deploy
```

This is the simplest thing. With this setup, simply create an `app_offline-template.htm` in your project root folder and it will be used by the script. This has the added benefit of completely customizing the "App_Offline.htm" template. For an even more advanced usage, you can have arguments in your script so you can control what it does (for example a `-dry` argument that tells it to do all the steps except for deployment).

**Comment by asadsahi** [comment]
@mrahhal, One word, perfect script :) Thanks

I am trying to build an equivalent bash script, so that it can work cross platform. Interested in helping there? :)

**Comment by mrahhal** [comment]
Too bad I know very little about bash 😅 
The script I just wrote can actually be improved, I cut stuff out to keep it short. So I'd be willing to help anyway if you put that in a gist maybe (along with the ps1 script) since I'm interested in a bash version of it too.

**Comment by asadsahi** [comment]
@mrahhal here is the gist of bash script:

https://gist.github.com/asadsahi/461c23e28097ee4b0134f94b20ea29a6

lets work together to get it working.

**Comment by ozhelenkov** [comment]
Good day guys,
I am sorry, are there any ETA for this issue to be resolved?
Thanks!

**Comment by asadsahi** [comment]
@ozhelenkov above workaround from @mrahhal will always work  :)

@mrahhal see updated gist of bash script. Happy to have feedback. Thanks

**Comment by mrahhal** [comment]
@asadsahi check my comment there.

**Comment by asadsahi** [comment]
Thanks @mrahhal, comments make perfect sense. Updated. Have I missed anything else?

**Comment by mrahhal** [comment]
Great. Commented  there. [And this is my ps1 script here](https://gist.github.com/mrahhal/5d2016c4b4f1ce175b170f08abc190e9).

**Comment by mbuck** [comment]
This issue is super annoying so I looked into it and it seems that there are two places where this could be fixed:
1) Simply change the file name to "App_Offline.htm" here: https://github.com/aspnet/AspNetCoreModule/blob/dev/src/AspNetCore/Src/application.cxx#L110 
2) Change this to a case insensitive compare, which seems like the better fix since this is an IIS module that will only run on Windows where file names are case insensitive anyways:
https://github.com/aspnet/AspNetCoreModule/blob/dev/src/AspNetCore/Src/filewatcher.cxx#L269 

Happy to submit a PR if either one of these is helpful.

**Comment by shirhatti** [comment]
@mbuck Thanks for the suggestion. We are going with the second option. While I appreciate the offer for a PR, I think @pan-wang already has it fixed. We should re-release soon

**Comment by shirhatti** [comment]
Fixed in a4963aa6da4b6b840445ec7bf53803f70b4ea79b

**Comment by taspeotis** [comment]
Hi everyone, thanks for working to fix this issue. When will this fix be released?

**Comment by shirhatti** [comment]
The update is already available for download at https://www.microsoft.com/net/download/core#/runtime
[This is a direct link](https://go.microsoft.com/fwlink/?linkid=837808) to the download.

We have also begun the process of rolling out the update to Azure App Service. We expect everyone to get the fix by January 26th.

**Comment by matthieugd** [comment]
Thanks for the update, do you know if there's a quick way to know if a instance of App Service has the correct version ?

**Comment by shirhatti** [comment]
> Thanks for the update, do you need if there's a quick way to know if a instance of App Service has the correct version ?

@davidebbo Could you help answer this question?

**Comment by davidebbo** [comment]
No fix has been deployed yet.

**Comment by matthieugd** [comment]
ok but when it's going to be deployed how/where we can see the version of the dll of the IIS .NEt Core module used in our Azure App Service instance?

**Comment by davidebbo** [comment]
I think you could simply check the version of the relevant assembly from Kudu Console. @shirhatti do you know where that assembly goes?

The current (bad) one is version 1970, and the new one will be 1971.

**Comment by shirhatti** [comment]
`C:\Windows\System32\inetsrv\aspnetcore.dll`

**Comment by davidebbo** [comment]
@matthieugd here is a sort-of easy way to check:

- Run the app
- Go to Kudu, and go to Process Explorer
- Write click on the w3wp that does **not** have the `scm` tag and choose properties
- Go to the Modules tab and search for aspnetcore.dll

If you see `7.1.1970.0` you have the old version. The new one is 1971.

**Comment by matthieugd** [comment]
@davidebbo got it. thank you!

**Comment by sveinfid** [comment]
Anyone seeing the updated `7.1.1971.0` version for their Azure App Service instance yet?

**Comment by matthieugd** [comment]
nope still 1970

**Comment by davidebbo** [comment]
Deployment has not happened yet. It should be later in January.

**Comment by taspeotis** [comment]
Does the documentation have the right version? This links to `https://aka.ms/dotnetcore_windowshosting_1_1_0` which I just installed and it's `7.1.1970.0`. 

https://docs.microsoft.com/en-us/aspnet/core/publishing/iis#install-the-net-core-windows-server-hosting-bundle

At this link, if you choose "LTS" instead of "Current" here you get the newer version.

https://www.microsoft.com/net/download/core#/runtime/current

**Comment by guardrex** [comment]
@taspeotis I'm awaiting the release of the new aka.ms link for the doc, and that might coincide with the release of 1.1.1.

@shirhatti Do you think we should go with `https://go.microsoft.com/fwlink/?linkid=837808` temporarily?

**Comment by shirhatti** [comment]
@leecow Is there any reason why https://go.microsoft.com/fwlink/?linkid=837808 doesn't have an aka.ms link?

**Comment by leecow** [comment]
@shirhatti We just haven't been using the aka.ms infrastructure to this point. There is also some discussion around utilizing the raw url for better transparency into the download location.

**Comment by alexgritton** [comment]
I'm still running into this case sensitive issue on 7.1.1971.0. When I try to deploy I get a file locked error, so I looked to see if the app was still running and sure enough it was. I opened the Kudu command line to see what files where in the wwwroot directory and App_Offline.htm was in the folder but the process was still running. Then I typed touch app_offline.htm and the process stopped running as expected. I double checked the modules and my aspnetcore.dll version is 7.1.1971.0.

**Comment by xtomas** [comment]
Same problem as @alexgritton. Only difference is newer aspnetcore.dll version.

```
(Get-Item "$env:windir\System32\inetsrv\aspnetcore.dll").VersionInfo

ProductVersion   FileVersion      FileName                                     
--------------   -----------      --------                                     
7.1.1982.0       7.1.1982.0       D:\Windows\System32\inetsrv\aspnetcore.dll

(Get-Item "$env:windir\SysWOW64\inetsrv\aspnetcore.dll").VersionInfo

ProductVersion   FileVersion      FileName                                     
--------------   -----------      --------                                     
7.1.1982.0       7.1.1982.0       D:\Windows\SysWOW64\inetsrv\aspnetcore.dll
```

**Comment by nguyenquyhy** [comment]
I am using 7.1.1986.0 in my Azure App Service but the App_Offline.htm is still not detected after publishing from Visual Studio.

However, if I visit the scm site and edit and save the file (without any actual modification), the file is picked up by the module and the site is down.

**Comment by jkotalik** [comment]
@nguyenquyhy After publishing your app, was a request sent to your application? 

@pan-wang In the 1985 build, we still seem to be checking against app_offline.htm on startup. https://github.com/aspnet/AspNetCoreModule/blob/1.0.1985/src/AspNetCore/Src/application.cxx#L116. I believe we need to compare against this case insensitively.

**Comment by nguyenquyhy** [comment]
The publishing from Visual Studio failed because the application was not shut down. I checked scm and see App_Offline.htm file in wwwroot folder. I then open the site URL and see that the site is still up.

**Comment by jkotalik** [comment]
Thanks. @jhkimnew when you were verifying the out of process implementation, did you check different names for app_offline?

**Comment by jkotalik** [comment]
Seems I was incorrect on that assumption. All windows APIs are case insensitive. My best guess is we have a race on actually watching for App_Offline.htm and the creation of it. Right here I see we unlock and then start monitoring app_offline https://github.com/aspnet/AspNetCoreModule/blob/1.0.1985/src/AspNetCore/Src/applicationmanager.cxx#L68-L71. Between then, we can technically not detect app_offline in the folder, which would require touching/modifying the file for it to be detected again. 

@nguyenquyhy were you hitting this consistently or was this a one time thing? Also, after you touched the app_offline file, when you published again, did it fail for the same reason?

**Comment by nguyenquyhy** [comment]
Everytime I publish from Visual Studio when the app is running.

**Comment by pan-wang** [comment]
Does your application have any assembly used by IIS directly instead of kestrel process?

**Comment by nguyenquyhy** [comment]
No, it is a ASP.NET Core application with kestrel.
