### ISSUE TITLE
Modify the default value of forwardWindowsAuthToken="true" in the schema file

### ISSUE THREAD

**Issue by shirhatti** [aspnet/AspNetCoreModule#53]
Given that forwardWindowsAuthToken currently no-ops when there is no identity present, this change should allow us to simplify the templates.

**Comment by shirhatti** [comment]
Fixed in 87f808cc9d6904f01da2f97996203a243ccb460c

We still need to create an announcement for the schema change on https://github.com/aspnet/announcements/

**Comment by guardrex** [comment]
@shirhatti When do you want the ANCM reference doc to reflect this change?

[EDIT] ... and "simplify the templates" ... meaning that the `forwardWindowsAuthToken` attribute will be dropped from the `aspNetCore` element?

**Comment by GuardRex** [comment]
@shirhatti Is it ok to update the ANCM ref doc for this now?
