### ISSUE TITLE
Not expected Uri conversion between ANCM and backend process

### ISSUE THREAD

**Issue by jhkimnew** [aspnet/AspNetCoreModule#60]
@pan-wang  

If http://localhost/AspNetCoreApp%2fgetprocessid is sent to ANCM, it decodes the %2f to "/" and bypasses decoded URI to backend processes. 
This behavior is okay in most cases but if backend process expects the %2f instead of "/", the backend process won't work. So, we should make ANCM not to modify original URI.

**Comment by Tratcher** [comment]
This happens in http.sys, not ANCM.

**Comment by pan-wang** [comment]
http.sys does expose raw request url. ANCM can use it in forwarding.

________________________________

**Comment by Tratcher** [comment]
Only with extreme caution. Kestrel isn't ready to handle completely unfiltered input. @blowdart 

HttpListener had a feature where it would review the raw url and undo just the %2f's.

**Comment by blowdart** [comment]
Yea, this can't be on by default, at all. The backend process is here is *wrong*, but we have at least one customer that didn't understand that and now depends on it. Frankly I would rather core does not support this, and if they want to continue to be wrong they can continue on full framework.

**Comment by Tratcher** [comment]
Actually @blowdart %2f is not supposed to be un-escaped per spec. http.sys is over cautious in this case. This is one of the more common issues people have with http.sys/IIS.

**Comment by blowdart** [comment]
Oh. I thought the spec said to canonicalise the URL. My bad :(

**Comment by pan-wang** [comment]
@Tratcher could you please share the RFC spec details for "%2f is not supposed to be un-escaped"?

**Comment by Tratcher** [comment]
https://www.ietf.org/rfc/rfc3986.txt section 2.2. `/` is a reserved character and cannot be un-escaped without changing the value of the path. Only unreserved characters should be un-escaped (2.3). You can also look at 3.3 for Path specific allowed/reserved characters.

"URIs that differ in the replacement of a reserved character with its corresponding percent-encoded octet are not equivalent...characters in the reserved set are protected from normalization..."

**Comment by muratg** [comment]
@blowdart Is this OK to close?

**Comment by blowdart** [comment]
Sure
