### ISSUE TITLE
AppVerifier: Freeing heap block containing an active critical section. 

### ISSUE THREAD

**Issue by jhkimnew** [aspnet/AspNetCoreModule#61]
@pan-wang 

If ANCM is used with IISExpress, it does not call aspnetcore!ProcessHandleCallback() and therefore 
below destructor functions got never called.

aspnetcore!SERVER_PROCESS::~SERVER_PROCESS
aspnetcore!PROCESS_MANAGER::~PROCESS_MANAGER

This issue found from AppVerifier, which shows “Freeing heap block containing an active critical section” from IISExpress.exe process when stopping the IISexpress after sending requests to Aspnetcore app. 
The critical section is supposed be removed from the Process_Manager destructor. 

Attached below the AppVerifier report about this issue.

=======================================
VERIFIER STOP 0000000000000202: pid 0x58D4: Freeing heap block containing an active critical section. 

                0000008FD4624DC8 : Critical section address. Run !cs -s <address> to get more information.
                0000008FAC804E40 : Critical section initialization stack trace. Run dps <address> to dump the stack trace.
                0000008FD4624D50 : Heap block address.
                00000000000002B0 : Heap block size.

=======================================
This verifier stop is continuable.
After debugging it use `go' to continue.

=======================================

(58d4.4564): Break instruction exception - code 80000003 (first chance)
vrfcore!VerifierStopMessageEx+0x679:
00007ffe`19042129 cc              int     3
0:027> !cs -s 0000008FD4624DC8
-----------------------------------------
Critical section   = 0x0000008fd4624dc8 (+0x8FD4624DC8)
DebugInfo          = 0x0000008fdfc80fd0
NOT LOCKED
LockSemaphore      = 0x0
SpinCount          = 0x00000000020007d0

Stack trace for DebugInfo = 0x0000008fdfc80fd0:

0x00007ffe292338b6: ntdll!RtlInitializeCriticalSectionAndSpinCount+0x55526
0x00007ffe17327080: vfbasics!AVrfpInitializeCriticalSectionCommon+0x124
0x00007ffe0a1194f2: aspnetcore!SERVER_PROCESS::SERVER_PROCESS+0x12E
0x00007ffe0a11a030: aspnetcore!PROCESS_MANAGER::GetProcess+0x324
0x00007ffe0a11e481: aspnetcore!FORWARDING_HANDLER::OnExecuteRequestHandler+0x39D
0x00007ffe0a11699e: aspnetcore!CProxyModule::OnExecuteRequestHandler+0xD2
0x00007ffe0ae42369: iiscore!NOTIFICATION_CONTEXT::RequestDoWork+0x351
0x00007ffe0ae413f7: iiscore!NOTIFICATION_CONTEXT::CallModulesInternal+0x497
0x00007ffe0ae2ea14: iiscore!NOTIFICATION_CONTEXT::CallModules+0x48
0x00007ffe0ae42dbd: iiscore!NOTIFICATION_MAIN::DoWork+0x1FD
0x00007ffe0ae336d1: iiscore!W3_CONTEXT_BASE::StartNotificationLoop+0xE9
0x00007ffe0ae33cf0: iiscore!W3_MAIN_CONTEXT::OnNewRequest+0xE0
0x00007ffe12575970: w3dt!UL_NATIVE_REQUEST::DoWork+0x1E4
0x00007ffe125764d0: w3dt!UL_RECEIVE_CONTEXT::DoWork+0x20
0x00007ffe12574e42: w3dt!WP_CONTEXT::OnCompletion+0x32
0x00007ffe17312bbe: W3TP!THREAD_POOL_DATA::ThreadPoolThread+0xCE
0x00007ffe17311819: W3TP!THREAD_MANAGER::ThreadManagerThread+0x69
0x00007ffe1732f64c: vfbasics!AVrfpStandardThreadFunction+0x4C
0x00007ffe268613d2: KERNEL32!BaseThreadInitThunk+0x22
0x00007ffe291954e4: ntdll!RtlUserThreadStart+0x34
0:027> dps 0000008FAC804E40
0000008f`ac804e40  00000000`00000000
0000008f`ac804e48  001402bf`00009801
0000008f`ac804e50  00007ffe`292338b6 ntdll!RtlInitializeCriticalSectionAndSpinCount+0x55526 [d:\blue\minkernel\ntdll\resource.c @ 2447]
0000008f`ac804e58  00007ffe`17327080 vfbasics!AVrfpInitializeCriticalSectionCommon+0x124 [d:\rs2\onecore\base\avrf\vrfcommon\critsect.c @ 2132]
0000008f`ac804e60  00007ffe`0a1194f2 aspnetcore!SERVER_PROCESS::SERVER_PROCESS+0x12e [f:\iis_main\projects\aspnetcoremodule\dll\serverprocess.cxx @ 1668]
0000008f`ac804e68  00007ffe`0a11a030 aspnetcore!PROCESS_MANAGER::GetProcess+0x324 [f:\iis_main\projects\aspnetcoremodule\dll\processmanager.cxx @ 228]
0000008f`ac804e70  00007ffe`0a11e481 aspnetcore!FORWARDING_HANDLER::OnExecuteRequestHandler+0x39d [f:\iis_main\projects\aspnetcoremodule\dll\forwardinghandler.cxx @ 1145]
0000008f`ac804e78  00007ffe`0a11699e aspnetcore!CProxyModule::OnExecuteRequestHandler+0xd2 [f:\iis_main\projects\aspnetcoremodule\dll\proxymodule.cxx @ 90]
0000008f`ac804e80  00007ffe`0ae42369 iiscore!NOTIFICATION_CONTEXT::RequestDoWork+0x351 [d:\src\rs1\inetsrv\iis\iisrearc\iis70\core\notificationcontext.cxx @ 1678]
0000008f`ac804e88  00007ffe`0ae413f7 iiscore!NOTIFICATION_CONTEXT::CallModulesInternal+0x497 [d:\src\rs1\inetsrv\iis\iisrearc\iis70\core\notificationcontext.cxx @ 578]
0000008f`ac804e90  00007ffe`0ae2ea14 iiscore!NOTIFICATION_CONTEXT::CallModules+0x48 [d:\src\rs1\inetsrv\iis\iisrearc\iis70\core\notificationcontext.h @ 341]
0000008f`ac804e98  00007ffe`0ae42dbd iiscore!NOTIFICATION_MAIN::DoWork+0x1fd [d:\src\rs1\inetsrv\iis\iisrearc\iis70\core\mainnotification.cxx @ 103]
0000008f`ac804ea0  00007ffe`0ae336d1 iiscore!W3_CONTEXT_BASE::StartNotificationLoop+0xe9 [d:\src\rs1\inetsrv\iis\iisrearc\iis70\core\w3basecontext.cxx @ 1083]
0000008f`ac804ea8  00007ffe`0ae33cf0 iiscore!W3_MAIN_CONTEXT::OnNewRequest+0xe0 [d:\src\rs1\inetsrv\iis\iisrearc\iis70\core\maincontext.cxx @ 107]
0000008f`ac804eb0  00007ffe`12575970 w3dt!UL_NATIVE_REQUEST::DoWork+0x1e4 [d:\src\rs1\inetsrv\iis\iisrearc\iisplus\w3dt\nativerequest.cxx @ 369]
0000008f`ac804eb8  00007ffe`125764d0 w3dt!UL_RECEIVE_CONTEXT::DoWork+0x20 [d:\src\rs1\inetsrv\iis\iisrearc\iisplus\w3dt\nativerequest.cxx @ 2308]

Thanks,
Jeong Hwan Kim

**Comment by shirhatti** [comment]
@jhkimnew Please close if this issue is stale

**Comment by jhkimnew** [comment]
This was fixed with https://github.com/aspnet/AspNetCoreModule/commit/044648a21346d3c6782c13a4fcc4854c8782f7e2
