### ISSUE TITLE
Unexpected Request.Scheme when using Proxy -> IIS -> ASPNET

### ISSUE THREAD

**Issue by glatzert** [aspnet/AspNetCoreModule#62]
I observed some odd behaviour on an IIS 7.5 using the AspNetCore Module.

When I access the page directly via https, it will correctly issue an OpenIDConnect-Redirect_URI with https as scheme.
When the same page is accessed via a proxy (Arr) the issued Redirect_uri will be http - despite the Proxy using https for communicating with the target Server as well.

The Request- and Response-Headers for both requests:

**With Proxy**
-- Request --
```
RequestURL https://domain.de:443/ 
RequestVerb GET 
```
Headers
```
Connection: Keep-Alive
Accept: text/html, application/xhtml+xml, image/jxr, */*
Accept-Encoding: gzip, deflate
Accept-Language: de-DE,de;q=0.8,en-US;q=0.5,en;q=0.3
Host: <correct hostname>
Max-Forwards: 10
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393
DNT: 1
X-Original-URL: /
X-Forwarded-For: <myIPAddress>
X-ARR-SSL: 2048|256|C=BE, O=GlobalSign nv-sa, CN=AlphaSSL CA - SHA256 - G2|OU=Domain Control Validated, CN=*.domain.de
X-ARR-LOG-ID: 3e8c20ce-5bb1-4687-ad7e-0ba31b2281a5
```

-- Response headers -- (mind the redirect_uri-protocol)
```
Content-Length: 0
Location: https://login.domain.de/adfs/oauth2/authorize/?client_id=zdvapps%3Aweb&redirect_uri=http%3A%2F%2Fdomain.de%2Fsignin-oidc&resource=resource%3Aweb&response_type=id_token&scope=openid%20profile&response_mode=form_post&nonce=[...]&state=[...]
Server: Kestrel
Set-Cookie: .AspNetCore.OpenIdConnect.Nonce.[...]; expires=Thu, 19 Jan 2017 08:45:58 GMT; path=/; httponly
Set-Cookie: .AspNetCore.Correlation.OpenIdConnect.[...]; expires=Thu, 19 Jan 2017 08:45:58 GMT; path=/; httponly
```

**Direct Access**
-- Request --
```
RequestURL https://domain.de:443/ 
RequestVerb GET 
```
Headers
```
Connection: Keep-Alive
Accept: text/html, application/xhtml+xml, image/jxr, */*
Accept-Encoding: gzip, deflate
Accept-Language: de-DE,de;q=0.8,en-US;q=0.5,en;q=0.3
Host: apps.zdv.uni-mainz.de
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393
DNT: 1
```
-- Response headers--
```
Content-Length: 0
Location: https://login.domain.de/adfs/oauth2/authorize/?client_id=resource%3Aweb&redirect_uri=https%3A%2F%2Fdomain.de%2Fsignin-oidc&resource=zdvapps%3Aweb&response_type=id_token&scope=openid%20profile&response_mode=form_post&nonce=[...]&state=[...]
Server: Kestrel
Set-Cookie: .AspNetCore.OpenIdConnect.Nonce.[...]=N; expires=Thu, 19 Jan 2017 08:46:44 GMT; path=/; secure; httponly
Set-Cookie: .AspNetCore.Correlation.OpenIdConnect.[...]=N; expires=Thu, 19 Jan 2017 08:46:44 GMT; path=/; secure; httponly
X-Powered-By: ASP.NET
```

The OIDC implementation generates the redirect_uri, by using Request.Scheme + Request.Host (more or less). So I think something might be off there.

I can provide more of the request-trace, if you like, but would prefer email, since I do not want to disclose Domain names here.

**Comment by Tratcher** [comment]
This scenario is still getting documented, but here are the initial references: https://github.com/aspnet/Docs/issues/2384

The first issue is that UseForwardedHeaders is expecting x-forwarded-proto from the proxy. Failing that you need to set RequireHeaderSymmetry = false;

**Comment by glatzert** [comment]
Thanks for the insight.

So essentially the Options to resolve are:

1. Configuring the Proxy to send X-Forwarded-Proto (if possible)
2. services.Configure<ForwardedHeadersOptions>(opt => opt.RequireHeaderSymmetry = false)
