### ISSUE TITLE
Need a tip on location for httpTracing traces

### ISSUE THREAD

**Issue by muratg** [aspnet/AspNetCoreModule#65]
_From @GuardRex on January 6, 2017 18:51_

Researching for https://github.com/aspnet/Docs/issues/2367

Activating `httpTracing` with ...
```xml
<httpTracing>
    <traceUrls>
      <add value="/favicon.ico" />
    </traceUrls>
</httpTracing>
```
I wish they would state the location of the traces explicitly in https://www.iis.net/configreference/system.webserver/httptracing, but the doc doesn't say.

I'm expecting them to be elsewhere than the failed request tracing traces ... I know where those are. I don't see what I'm looking for in the vicinity of `C:\inetpub\logs`.

Anyone know where they go?

_Copied from original issue: aspnet/IISIntegration#314_

**Comment by muratg** [comment]
_From @Tratcher on January 6, 2017 19:6_

@pan-wang @shirhatti ?

**Comment by muratg** [comment]
@shirhatti could you follow-up?

**Comment by guardrex** [comment]
Yes, this is still relevant to the work on https://github.com/aspnet/Docs/pull/2609

**Comment by muratg** [comment]
Filed a doc bug here: https://github.com/MicrosoftDocs/iis-docs/issues/111

Closing this one.

**Comment by bangbingsyb** [comment]
Update is here: https://github.com/MicrosoftDocs/iis-docs/pull/201
Let me know if it is not sufficiently clear.
