### ISSUE TITLE
Question: How to make IIS respect an AbortAction in rewrite

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCoreModule#66]
_From @davidpeden3 on February 3, 2017 21:32_

I have created a catch-all rule to abort any/all requests not matched by earlier rewrite rules:

```csharp
	/// <summary>
	/// 	<rule name="AbortAllRequestsRule" patternSyntax="ECMAScript" stopProcessing="true">
	/// 		<match url=".*" />
	/// 		<action type="AbortRequest" />
	/// 	</rule>
	/// </summary>
	public class AbortAllRequestsRule : IRule
	{
		private readonly IISUrlRewriteRule _rule;

		public AbortAllRequestsRule()
		{
			// create rule builder
			var ruleBuilder = new UrlRewriteRuleBuilder
			{
				Name = nameof(AbortAllRequestsRule),
				Enabled = true
			};

			// add url match
			ruleBuilder.AddUrlMatch(
				".*",
				ignoreCase: true,
				negate: false,
				patternSyntax: PatternSyntax.ECMAScript);

			// add action
			var action = new AbortAction();
			ruleBuilder.AddUrlAction(action);

			// create rule
			_rule = ruleBuilder.Build(true);
		}

		public void ApplyRule(RewriteContext context)
		{
			_rule.ApplyRule(context);
		}
	}
```

In Kestrel, this properly aborts the request. However, IIS sees an aborted request, and without additional configuration, throws a very detailed 502 response (HTML page).

Adding the following snippet to `web.config`:

```
<httpErrors errorMode="Custom">
	<clear/>
</httpErrors>
```

Pares the verbose 502 response down to a more reasonable one:

```
HTTP/1.1 502 Bad Gateway
Content-Type: text/html
Server: Microsoft-IIS/8.5
Date: Fri, 03 Feb 2017 19:53:07 GMT
Content-Length: 89

The specified CGI application encountered an error and the server terminated the process.
```

But, is it possible to have IIS properly proxy the _lack of_ a response from Kestrel and, itself, abort the response rather than returning a 502?

_Copied from original issue: aspnet/BasicMiddleware#203_

**Comment by GuardRex** [comment]
@davidpeden3 Just curious: Why not return a 502? ... Were you only put off by the verbose 502? What I did here has nothing to do with how an aborted request is handled by ANCM, of course. As a side issue, I was just thinking that I could drop a 502 if no other rules matched with the rule overload and that would shoot right back thru IIS without a verbose error page or response ...
```c#
var options = new RewriteOptions()
    .AddRedirect("redirect-rule/(.*)", "redirected/$1")
    .AddRewrite(@"^rewrite-rule/(\d+)/(\d+)", "rewritten?var1=$1&var2=$2", skipRemainingRules: true)
    .AddApacheModRewrite(env.ContentRootFileProvider, "ApacheModRewrite.txt")
    .AddIISUrlRewrite(env.ContentRootFileProvider, "IISUrlRewrite.xml")
    .Add(RedirectXMLRequests)
    .Add(new RedirectImageRequests(".png", "/png-images"))
    .Add(new RedirectImageRequests(".jpg", "/jpg-images"))
    .Add(Drop502);
```
```c#
static void Drop502(RewriteContext context)
{
    var response = context.HttpContext.Response;
    response.StatusCode = StatusCodes.Status502BadGateway;
    context.Result = RuleResult.EndResponse;
}
```
![capture](https://cloud.githubusercontent.com/assets/1622880/22620179/36f568ea-eacb-11e6-8186-3b3b19f93e7a.PNG)

**Comment by shirhatti** [comment]
> is it possible to have IIS properly proxy the lack of a response from Kestrel

Not sure I follow what you mean by "lack of response". Could you care to explain what you expected to happen?

Since IIS+ANCM functions as a proxy, we are expected to respond with 502- Bad Gateway when the backend closes the connection.

**Comment by davidpeden3** [comment]
If Kestrel kills the response (i.e., literally closes the connection without sending any bytes to the client), it would be great for IIS to do the same instead of send a new, modified response (even if it's a 502). Sounds like you guys do that by design. Not a huge deal but not what I expected to happen.

**Comment by shirhatti** [comment]
I'll let @Tratcher and @pan-wang weigh in on what is expected behavior for a proxy server.

@davidpeden3 Beyond discussing semantics, is there something you are trying to do and are blocked by this behavior?

**Comment by davidpeden3** [comment]
Not blocked. I ended up returning a 502 with no response body rather than aborting the connection and leaving it up to IIS to decide what to do. Thanks!

**Comment by muratg** [comment]
:+1:
