### ISSUE TITLE
Connection reset when uploading large files (~4GB)

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/AspNetCoreModule#78]
Following the investigation in https://github.com/aspnet/HttpAbstractions/issues/766. 

While I am able upload a 4GB file when running on Kestrel only, trying to upload such a file while running in IIS fails. When I examined the logs, I see 

```
dbug: Microsoft.AspNetCore.Server.Kestrel[19]
      Connection id "0HL30U3770MSD" reset.
dbug: Microsoft.AspNetCore.Server.Kestrel[10]
      Connection id "0HL30U3770MSD" disconnecting.
dbug: Microsoft.AspNetCore.Server.Kestrel[2]
      Connection id "0HL30U3770MSD" stopped.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action FileUploadRepro.Controllers.StreamingController.Upload (FileUploadRepro) in 148486.9945ms
```

Seems like ANCM is resetting the connection but I'm not sure why. Note that to reproduce this issue, I turned off Request Filtering since the request allowed content length is bounded by the max value of unsigned int.

Is this expected for ANCM? Is there a hard limit on request size?

I have attached the repro project I was testing with at https://github.com/JunTaoLuo/FileUploadRepro. It mostly follows our documentation sample for file upload at https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads.

cc @pan-wang @Tratcher

**Comment by JunTaoLuo** [comment]
Spoke with @pan-wang and there is a limit on the request size. From trying a few different sizes of files, the limit seems to be 2GB though I didn't find the exact place this limit is set.

**Comment by ryanski44** [comment]
@JunTaoLuo, Why was this ticket closed? It sounds like you isolated the issue to the Asp.NET Core Module.

**Comment by ryanski44** [comment]
@JunTaoLuo, Nevermind, it seems this project was integrated to the mainline AspNetCore repo.
