### ISSUE TITLE
Frequent Autobahn Test Suite failures behind ANCM

### ISSUE THREAD

**Issue by analogrelay** [aspnet/AspNetCoreModule#80]
We're seeing flakiness in our Autobahn Test Suite runs for our WebSocket middleware, but only when running behind IIS/ANCM. It would be really helpful if the ANCM build could have some automated testing that used Autobahn in order to try to catch these issues directly at the source.

/cc @JunTaoLuo @Tratcher

**Comment by natemcmaster** [comment]
@shirhatti would anyone from you team be available to look at this?

**Comment by analogrelay** [comment]
Note that as far as we can tell this is about ANCM forwarding any WebSocket. The exact same tests run consistently on Kestrel alone. We don't really have a repro because it's all flaky occasional failures with no warning or context. So, what I'm suggesting here is setting up automation in here to run the Autobahn Suite against ANCM forwarding to a known-good WebSockets infrastructure (i.e. not ASP.NET Core; so ASP.NET 4 would be fine). That would give us two things: 1) additional testing of ANCM's WebSocket handling, which is always good and 2) a way to start tracking down these flaky failures (assuming they begin to occur on ASP.NET 4 apps).

Autobahn is a pretty straightforward test suite to set up (we've done it a few times in ASP.NET, see https://github.com/aspnet/WebSockets/tree/dev/test/Microsoft.AspNetCore.WebSockets.ConformanceTest)

**Comment by analogrelay** [comment]
It may also be good for IIS to have Autobahn suites running against a pure ASP.NET 4 app (i.e. without ANCM at all) to see if these issues repro. We have a sample Autobahn-compatible ASP.NET 4 app here: https://github.com/aspnet/WebSockets/tree/dev/samples/AutobahnTestAppAspNet4

**Comment by muratg** [comment]
@shirhatti is looking into this.

**Comment by shirhatti** [comment]
Closed in favor of https://github.com/aspnet/IISIntegration/issues/586
