### ISSUE TITLE
Set ASPNETCORE_HOSTINGSTARTUPASSEMBLIES to inject IISIntegration

### ISSUE THREAD

**Issue by shirhatti** [aspnet/AspNetCoreModule#81]
ANCM will set ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=Microsoft.AspNetCore.Server.IISIntegration and Hosting will load and add IIS.
Related: https://github.com/aspnet/IISIntegration/issues/348

**Comment by muratg** [comment]
cc @glennc @Tratcher

**Comment by muratg** [comment]
Fixed in https://github.com/aspnet/AspNetCoreModule/pull/102 in 2.0.0 timeline.
