### ISSUE TITLE
Question: Is it possible to configure IIS as a load balancer for two kestrel servers?

### ISSUE THREAD

**Issue by PonchoPowers** [aspnet/AspNetCoreModule#84]
This question has been reposted from SO:
http://stackoverflow.com/questions/41846050/configure-iis-as-a-load-balancer-for-two-kestrel-servers-for-the-same-website

ASP.NET Core cannot be run directly in IIS as it requires Kestrel.

This means it is not possible to update a website at runtime like in traditional ASP.NET sites, since the kestrel server have to be shut down during the update.

I want to avoid downtime without adding additional web servers and a load balancer. Is it possible to configure the ASP.NET Core module in IIS to connect to two different Kestrel servers? So if one of them is shut down all requests will go to the other one?

(I was thinking something like having two different folders on disk: C:\inetpub\wwwroot\mysite_instance1 and C:\inetpub\wwwroot\mysite_instance2, thus shutting one down will enable updates of that instance)

If it is possible, are there any considerations we need to be aware of? For example, do the anti forgery token need to be configured in some way? (I do not use sessions.)

**Comment by pan-wang** [comment]
This is requirement is very interesting. Unfortunately it is not possible with current ANCM design as it only support one backend application.

**Comment by PonchoPowers** [comment]
I can't imagine it being too difficult to get this to work, most of the code is already there.

- The config parser would need to be updated to read multiple aspNetCore declarations:
`<aspNetCore />`
- The process manager would need to be updated to round robin the processes (to give some sense of load balancing even though the load balancing isn't really the desire).

The main problem I see is what to do when some ASP.NET Core web applications have been updated and others haven't, as the outcome would need to be configurable and to support this the dll's would likely have to be signed.

Is there a specific reason as to why this module wasn't written in C# as I might attempt to create a module in C# that does specifically this.

**Comment by davidfowl** [comment]
> The main problem I see is what to do when some ASP.NET Core web applications have been updated and others haven't, as the outcome would need to be configurable and to support this the dll's would likely have to be signed.

I don't understand this. What would you expect to configure in this scenario and how would you detect this situation?

> Is there a specific reason as to why this module wasn't written in C# as I might attempt to create a module in C# that does specifically this.

It's an IIS module, IIS modules are native code. Why would we boot the CLR or CoreCLR inside of IIS to write a module in C# to then forward to another process running .NET? That sounds extremely inefficient.

**Comment by PonchoPowers** [comment]
> I don't understand this. What would you expect to configure in this scenario and how would you detect this situation?

By having signed dll's you could detect when the two applications are out of sync. The developer can then decide by configuration whether to keep existing sessions on the older application or force them onto the updated application.

> It's an IIS module, IIS modules are native code. Why would we boot the CLR or CoreCLR inside of IIS to write a module in C# to then forward to another process running .NET? That sounds extremely inefficient.

Thanks, as I thought was likely the reason, was just checking. I've never had a need to learn C++, C# does everything I need it to.

**Comment by davidfowl** [comment]
> By having signed dll's you could detect when the two applications are out of sync. The developer can then decide by configuration whether to keep existing sessions on the older application or force them onto the updated application.

You don't expect this module to check signatures do you? That seems like an awfully specific way to do things. I don't know of any other systems that depend on something like this. Anything that does this kind of update has an abstract notion of version and baking in signature detection seems like a harder way to deal with things.

**Comment by PonchoPowers** [comment]
What are the alternatives? Using the assembly manifest versioning which developers sometimes forget to update (I know they can be automatically generated), or timestamps that can suffer from NTFS caching issues.

**Comment by LK-Daniel** [comment]
Definitely need this!

**Comment by PonchoPowers** [comment]
Been learning C++ and it appears there are quite a few different ways to write it, do you have any guidelines for me to follow so that when I submit a pull request it has a better chance of being merged in?

**Comment by pan-wang** [comment]
This feature requires extending existing configuration. For instance, how to define two process paths, the load balance algorithm (or under what condition the second process should be create) and affinity mechanism, et al.
A workaround for your current requirement (zero downtime for updating application) is to update the web.config file with the new  'processPath' and/or 'arguments' values. Once web.config is updated, IIS will recycle the old application instance and create a new one. New requests will be routed to the new application instance automatically. Existing requests will still be  processed during gracefully shutdown for best effort.

**Comment by PonchoPowers** [comment]
Downtime and slow response times will still occur with the suggested solution.

IIS will have to create the new process and then caches need to be warmed up as a result.

I, and others, would like to avoid this so the suggested solution is not going to work.

See issue https://github.com/aspnet/AspNetCoreModule/issues/111.

**Comment by muratg** [comment]
cc @shirhatti

**Comment by shirhatti** [comment]
.NET Core does not have support for AppDomains and hence we cannot do what System.Web did where it shadow copied everything in the bin directory before creating a new AppDomain.

As for alternative solutions for the problem, use the AppOffline feature if your app can tolerate a few seconds of downtime. If not, I'd recommend creating a blue-green deployment pattern where you create multiple sites in IIS and atomically update the binding information to move all traffic from one site to another once you're done deploying.

While we'd be happy to continue a discussion on other practices to achieve zero (or close to zero) downtime deployment, I'm closing this bug as we don't have any plans that are currently actionable.
