### ISSUE TITLE
ANCM should not preserve Host header

### ISSUE THREAD

**Issue by shirhatti** [aspnet/AspNetCoreModule#89]
We are currently in violation of RFC 7230, Section 5.4 since we always preserve the host header.
Once Kestrel implements https://github.com/aspnet/KestrelHttpServer/issues/839 we will break them.

**Comment by Tratcher** [comment]
How is ANCM violating this clause? It's been working well.

**Comment by shirhatti** [comment]
>  When a proxy receives a request with an absolute-form of
   request-target, the proxy MUST ignore the received Host header field
   (if any) and instead replace it with the host information of the
   request-target.  A proxy that forwards such a request MUST generate a
   new Host field-value based on the received request-target rather than
   forward the received Host field-value.

We don't do that currently

**Comment by Tratcher** [comment]
IIS/Http.Sys does not tell you if you received an absolute-form request-target so you have no way of implementing this. Even the raw value it gives you is one it has already assembled with scheme, host, port, etc..

**Comment by Antaris** [comment]
@shirhatti How would I know what the incoming (pre-proxy) host header was, if that was important to me (think multi-tenant apps)?

**Comment by shirhatti** [comment]
As it stands today, we don't replace the HOST header.
If we ended up doing this change, we will add a [`X-Forwarder-Host` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host).

**Comment by muratg** [comment]
Tracking work in the linked issue
