### ISSUE TITLE
Client Certificate is not getting attached on Azure Web app or under IIS Express.

### ISSUE THREAD

**Issue by xavierjohn** [aspnet/AspNetCoreModule#91]
I have written a Client Certificate based  Authorization here
https://github.com/xavierjohn/ClientCertificateMiddleware
which works when run locally without IIS Express.

When run locally with IIS Express or  on Azure Web app, the client certificate is not attached.
https://github.com/xavierjohn/ClientCertificateMiddleware/blob/master/ClientCertificateMiddleware/ClientCertificateHandler.cs
var certificate = Context.Connection.ClientCertificate;
The certificate is always null.

Maybe I need a web.config as described in http://anthonychu.ca/post/aspnet-core-hosting-azure-app-service/
If so, what should it look like for asp.net core 1.1?

I tired web.config mentioned here
https://docs.microsoft.com/en-us/aspnet/core/hosting/aspnet-core-module

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="%LAUNCHER_PATH%"
        arguments="%LAUNCHER_ARGS%"
        stdoutLogEnabled="false"
        stdoutLogFile=".\logs\stdout" />
  </system.webServer>
</configuration>

```
And ran under VS 2017 in IIS Express but calling the endpoint gives error "The underlying connection was closed: An unexpected error occurred on a send."

**Comment by xavierjohn** [comment]
What should the web.config look like to use Certificate Based auth in IIS Express and Azure Web app?

```
.UseKestrel(options =>
{
    var httpsOptions = new HttpsConnectionFilterOptions();
    httpsOptions.ServerCertificate = certificate;
    httpsOptions.ClientCertificateMode = ClientCertificateMode.AllowCertificate;
    httpsOptions.SslProtocols = System.Security.Authentication.SslProtocols.Tls;
    options.UseHttps(httpsOptions);
})
```

**Comment by Tratcher** [comment]
When using IIS you should not have any HTTPS config for Kestrel. IIS terminates HTTPS and forwards requests to kestrel as HTTP.

IIS Express client cert setup:
http://stackoverflow.com/questions/14752386/iisexpress-clientcertificate-setup-steps

Azure Web sites:
https://docs.microsoft.com/en-us/azure/app-service-web/app-service-web-configure-tls-mutual-auth

**Comment by xavierjohn** [comment]
The link to IIS Express info has no results. http://www.jasonrshaver.com/?tag=/IIS+Express

For Azure, is the cert located in a header? certHeader = headers["X-ARR-ClientCert"];  So code needs to have a different behavior between local dev machine and azure?
On Local dev machine, the cert is available at var certificate = Context.Connection.ClientCertificate; when it is not run under IIS Express.

**Comment by Tratcher** [comment]
I expect Context.Connection.ClientCertificate to be set even in Azure. Need to verify.

**Comment by xavierjohn** [comment]
Finally I got this to work. Thanks. Cert is attached to   Context.Connection.ClientCertificate

Here is a much better document on how to enable client cert
https://msftplayground.com/2016/06/azure-app-service-and-client-certificate-authentication/
