### ISSUE TITLE
Anonymous user identity

### ISSUE THREAD

**Issue by shirhatti** [aspnet/AspNetCoreModule#92]
_From @antonGritsenko on April 20, 2017 14:16_

With IIS we can set identity for application pool account and **for anonymous user**, so access we can use low privilege account for anonymous access. This really helpful to protect apps with anonymous access allowed in local networks (based on Active Directory permissions). But this doesn't work in case of Kestrel and integration with IIS. Any plan to implement this and any way to workaround this right now?

_Copied from original issue: aspnet/IISIntegration#358_

**Comment by shirhatti** [comment]
_From @Tratcher on April 20, 2017 14:54_

It's worth noting that IISIntegration does not do any impersonation for you, even for authenticated users. All actions are performed with the app pool identity unless you do explicit impersonation.

How do your permissions to differ between the app pool and your anonymous identities? Does anonymous get more, or less?

**Comment by shirhatti** [comment]
_From @antonGritsenko on April 20, 2017 15:4_

> It's worth noting that IISIntegration does not do any impersonation for you

I know. But I can use impersonation manually in ASP.NET Core. So it will be great to transfer anonymous identity to Kestrel somehow.
>do your permissions to differ between the app pool and your anonymous identities

Of course. Anonymous user usually very stricted account, but pool account had access to network, local files etc.

**Comment by shirhatti** [comment]
_From @Tratcher on April 20, 2017 15:36_

Is there anything stopping you from doing the impersonation directly in the app?

@blowdart

**Comment by shirhatti** [comment]
_From @Tratcher on April 20, 2017 15:49_

@shirhatti

**Comment by shirhatti** [comment]
_From @antonGritsenko on April 20, 2017 15:57_

OK, may be I have to explain a scenario. For instance, we have app that had access to some data. All data are stored in database\remote location etc that can be accessed only with valid active directory account. No problem here, we just setup application pool account with required AD permissions and it works fine. 
But now we have to protect all other thing from being executed from this account, so we setup Anonymous User Identity with very low privileged account (IUSR by default), and only execute code which needs to communicate with remote machine under application pool account.
In case of Kestrel all code needs to be executed under application pool account.

An another example (an more important): we are using ASP.NET Core web site (WS) to access remote system (RS) to get\update some data. RS requires different access level to do different things. For instance, to check users permission inside RS we have to use admin account inside RS. And again, in "pure" IIS this is not a problem: we setup application pool account with admin account, but Anonymous User Identity (AUI) is low privilege account. Regular communication made using AUI, but when we need to do some "admin" thing we just switch context to application pool and everything work well.

This is very similar with Windows Authentication: we have two Windows contexts: context of application pool and context of the logged in user. Will be great to have the same for anonymous access.

**Comment by shirhatti** [comment]
_From @Tratcher on April 20, 2017 16:6_

This would require a change to our overall impersonation story (or lack there of).

**Comment by shirhatti** [comment]
_From @antonGritsenko on April 20, 2017 16:8_

So it's hard from your side to "emulate" this by just pass-through the anonymous context like you did for Windows Authentication? I thought it's almost the same :(

**Comment by shirhatti** [comment]
_From @Tratcher on April 20, 2017 16:19_

The WindowsAuth user is passed through and assigned to HttpContext.User, but it's not impersonated. Do you do the impersonation yourself?

It may be possible to flow the anonymous user config from IIS to HttpContext.User, but impersonating that user would still be a separate concern.

**Comment by shirhatti** [comment]
_From @antonGritsenko on April 20, 2017 16:29_

>Do you do the impersonation yourself?

Yes, we did it manually. I do not expect automatic impersonation.

>It may be possible to flow the anonymous user config from IIS to HttpContext.User

This's exactly what I'm talking about. But that must be WindowsIdentity object to able to impersonate.

**Comment by shirhatti** [comment]
_From @Tratcher on April 20, 2017 16:45_

@pan-wang @shirhatti I think this is actually an ANCM request. I don't think anything would have to change in IISIntegration.

**Comment by shirhatti** [comment]
The IUSR account has a well-known SID that is consistent across all OSes. Forgive my naivety, but can you not just use this identity when doing the impersonation manually? Why do you need ANCM to flow this identity?,

**Comment by shirhatti** [comment]
_From @antonGritsenko on April 20, 2017 17:16_

Because IUSR rarely used in case of AD world. We almost always change it to some domain account (see case 2 from [comment above](https://github.com/aspnet/IISIntegration/issues/358#issuecomment-295790327))

**Comment by shirhatti** [comment]
I want to leave the issue open to solicit more feedback from the community and see how people are blocked or working around this.
We will definitely consider this as a candidate for our next release.

**Comment by blowdart** [comment]
In order to impersonate manually you'd have to store the password for the account somewhere, which is bad. And it excludes service accounts. I had thought that Kestrel was spawned under the app pool credentials. Is this not the case?

**Comment by shirhatti** [comment]
Ahh, my bad. You're right.

IIS currently stores the password in encrypted config and the key used to encrypt it is ACLed so that only WAS has access to it.
So Kestrel won't have a way to decrypt the password.

**Comment by blowdart** [comment]
But Kestrel should be started as the app pool user, right? @antonGritsenko's original post indicates this isn't the case? is that right Anton?

**Comment by antonGritsenko** [comment]
@blowdart Kestrel started under app pool user, there is no other options AFAIK.
>IIS currently stores the password in encrypted config and the key used to encrypt it is ACLed so that only WAS has access to it

That's the point. And that's why I thought what this is task for IISIntegration. Am I right that IIS sending user context to Kestrel in case of Windows Authentication? So my thought it can be done with Anonymous Identity as well.

**Comment by antonGritsenko** [comment]
By "manual impersonation" I means nothing more than this (this sample works for Windows Authentication only of course):
`var wi = (WindowsIdentity)this.httpContextAccessor.HttpContext.User.Identity;
using (var impersonatedUser = wi.Impersonate())
               {
                    action.Invoke();
                }`

So my expectation will be to have in case of Anonymous access the Anonymous User Identity here `this.httpContextAccessor.HttpContext.User.Identity`
but IsAuthenticated == false

**Comment by Tratcher** [comment]
For anonymous requests ANCM could instantiate and pass the identity to IISIntegration the same way it does for WindowsAuth. IISIntegration would not require access to the config.

**Comment by antonGritsenko** [comment]
@Tratcher thanks for info, all this things about context passing is still dark territory.
BTW, is there any articles describes pass identity in .net core with IIS and WindowsAuth?

**Comment by shirhatti** [comment]
@antonGritsenko I understand that you are trying to achieve here, but after giving it more thought what you are trying to do is achievable without impersonation. I'd recommend looking into running your AppPool as a GMSA and granting access to that low-privilege GMSA to your network resources.

I would love to hear more about what you are trying to achieve, and let's make sure you're scenario is  actually achievable without us having to build out this feature.

**Comment by antonGritsenko** [comment]
@shirhatti I can't use low privileged account. The goal is to have application pool as high privileged account to do some internal things in the system, but use special account to other things (see some sample above https://github.com/aspnet/AspNetCoreModule/issues/92#issuecomment-295837563). 
An another things is make parity between using ASP.NET (old) and Core no IIS with same experience.

BTW, I was able to make it work with some "magic". Right now I'm loading anonymous credentials from IIS directly and then using them for anonymous requests. I believe this must be in the Core OOB. The worst things that I have to store site name in the configuration to make it work.

**Comment by muratg** [comment]
Based on our triage discussion I'm closing this one.  We'll revisit if there's more interest.
