### ISSUE TITLE
Improve process port selection

### ISSUE THREAD

**Issue by samuelec** [aspnet/AspNetCoreModule#94]
We recently hit a problem in some of our servers where dotnet.exe might pick a port that is *reserved* to another service. All our Windows Servers back end machines set dynamic port range so that applications use ports in that range.

Currently, ACNM does not read the dynamic port range set on the server and does not allow setting a different port range (now hardcoded to 1025-48000).

**Comment by shirhatti** [comment]
@samuelec As best I understand, the dynamic port range is for ephemeral ports that aren't loopback connections. Are there concerns that arise from this that I'm failing to acknowledge?
For the most part, we've tried to make the port ANCM uses transparent to your experience using ASP.NET Core with IIS and I'd like to avoid adding knobs and switches if we can avoid it.

**Comment by muratg** [comment]
@shirhatti will be collecting all port issues in a single uber-issue to drive the higher level requirements and design.  He'll link this bug and close it.

**Comment by shirhatti** [comment]
I'm closing this bug to inactivity.

There is an unsupported way to force a static port assignment by setting the `ASPNETCORE_PORT` environment variable. Feel free to use this if you can guarantee that the ephemeral port you chose will always be available.

If you continue to see issues around port collision feel free to open a new bug.
