### ISSUE TITLE
Graceful shutdown is not working in Azure App Service

### ISSUE THREAD

**Issue by wimex** [aspnet/AspNetCoreModule#95]
Currently, it's impossible to gracefully shutdown a .NET Core based App Service in Azure. Whenever the stop button is clicked (or the application unloads itself or detects the app_offline.htm) the process gets killed with an error (visible under the Application Events area): Failed to gracefully shutdown process '<PID>'. This is true for the most basic template (created with dotnet new).

The .NET version seems to be up to date, but I'm not 100% sure:

```
> dotnet --version
1.0.1

> dotnet --info
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.2.9200
 OS Platform: Windows
 RID:         win8-x86
 Base Path:   D:\Program Files (x86)\dotnet\sdk\1.0.1
```

**Comment by shirhatti** [comment]
Acknowledging this issue. We're working with folks on Azure App Service to resolve this.

**Comment by shirhatti** [comment]
Fixed with https://github.com/aspnet/AspNetCoreModule/pull/118
